;;; ai-test.el --- Disposable AI candidates and real Org writes -*- lexical-binding: t; -*-
;; Set the optional package's data location before any require can load it.
(unless (boundp 'superchat-data-directory)
  (setq superchat-data-directory
        (expand-file-name "superchat/" (or (getenv "SUPERTAG_TEST_TMP")
                                           (make-temp-file "supertag-ai-runtime-" t)))))
(require 'ert)
(require 'cl-lib)
(require 'document-fixture)
(require 'supertag-ai)
(require 'supertag-view-node)
(require 'supertag-embark)
(defvar superchat-data-directory)
(defvar superchat-llm-backend)
(declare-function make-llm-fake "llm-fake" (&rest args))

(defmacro supertag-ai-test-with-request (&rest body)
  "Run BODY with captured REQUEST, isolated candidates and a stub transport."
  (declare (indent 0))
  `(let ((supertag-ai--candidates (make-hash-table :test 'equal)) request)
     (cl-letf (((symbol-function 'superchat-runtime-submit) #'ignore)
               ((symbol-function 'supertag-ai--submit)
                (lambda (value) (setq request value) (list :run-id "run" :turn-id "turn"))))
       ,@body)))

(defun supertag-ai-test-deliver (request text &optional status)
  (funcall (plist-get request :delivery-function) text (or status 'completed) "tape"))

(defun supertag-ai-test-snapshot (file)
  (list (supertag-document-test-disk file)
        (with-current-buffer (find-file-noselect file) (buffer-string))
        (with-current-buffer (find-file-noselect file) (buffer-modified-p))
        (prin1-to-string supertag--store)))

(ert-deftest supertag-ai-request-uses-live-own-body-and-custom-prompts ()
  (supertag-document-test-with-vault
    (supertag-ai-test-with-request
      (with-current-buffer (find-file-noselect file)
        (goto-char (point-max))
        (insert "written by Ada\n** Child\nDo not send child.\n")
        (goto-char (point-min))
        (let ((before (supertag-ai-test-snapshot file)))
          (supertag-ai-extract-properties)
          (should (equal before (supertag-ai-test-snapshot file)))))
      (should (string-match-p "Property Node" (plist-get request :prompt)))
      (should (string-match-p "ZETA: last" (plist-get request :prompt)))
      (should (string-match-p "written by Ada" (plist-get request :prompt)))
      (should-not (string-match-p "Child\\|:PROPERTIES:\\|document-node" (plist-get request :prompt)))
      (should (eq (plist-get request :type) :llm-query))
      (should (eq (plist-get request :tools) 'none))
      (should-not (plist-get request :record-conversation))
      (should (equal (buffer-name (plist-get request :buffer)) " *supertag-ai*"))
      (should (equal (plist-get request :system-prompt)
                     (plist-get (alist-get 'extract-properties supertag-ai-prompts) :system)))
      (should (equal (plist-get (gethash "document-node" supertag-ai--candidates) :run-id) "run"))
      (should (equal (plist-get (gethash "document-node" supertag-ai--candidates) :turn-id) "turn"))
      (supertag-ai-discard "document-node")
      (let ((supertag-ai-prompts '((alternate :system "System X" :user "%t|%p|%b")))
            (supertag-ai-max-body-chars 4))
        (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "alternate")))
          (with-current-buffer (find-file-noselect file)
            (supertag-ai-extract-properties t)))
        (should (equal (plist-get request :system-prompt) "System X"))
        (should (string-match-p "Body(truncated)" (replace-regexp-in-string "\n" "" (plist-get request :prompt))))))))

(ert-deftest supertag-ai-fresh-id-to-accepted-property-without-early-save ()
  (supertag-document-test-with-vault
    (supertag-ai-test-with-request
      (with-current-buffer (find-file-noselect plain)
        (goto-char (point-min))
        (let ((disk (supertag-document-test-disk plain)))
          (should-not (org-entry-get nil "ID"))
          (supertag-ai-extract-properties)
          (let ((id (org-entry-get nil "ID")))
            (should id)
            (should (supertag-node-get id))
            (should request)
            (should (buffer-modified-p))
            (should (equal disk (supertag-document-test-disk plain)))
            (should (eq 'pending (plist-get (gethash id supertag-ai--candidates) :status)))
            (should-error (supertag-ai-extract-properties) :type 'user-error)
            (supertag-ai-test-deliver request "{\"AUTHOR\":{\"value\":\"Ada\",\"source\":null}}")
            (should (supertag-ai-accept id "AUTHOR"))
            (should-not (buffer-modified-p))
            (should (string-match-p ":AUTHOR: +Ada" (supertag-document-test-disk plain)))
            (should (equal (plist-get (plist-get (supertag-node-get id) :properties) :AUTHOR) "Ada"))))))))

(ert-deftest supertag-ai-preflight-rejects-unsaved-and-file-level-without-writes ()
  (supertag-document-test-with-vault
    (supertag-ai-test-with-request
      (dolist (path (list nil (expand-file-name "never-saved.org" tmp)))
        (with-temp-buffer
          (org-mode) (setq buffer-file-name path) (insert "* Unsaved\nBody.\n")
          (goto-char (point-min))
          (let ((text (buffer-string)) (store (prin1-to-string supertag--store)))
            (should (equal (cadr (should-error (supertag-ai-extract-properties) :type 'user-error))
                           "Save this file before extracting properties"))
            (should (equal text (buffer-string)))
            (should (equal store (prin1-to-string supertag--store))))))
      (with-current-buffer (find-file-noselect plain)
        (goto-char (point-min)) (insert "Preamble\n") (goto-char (point-min))
        (let ((before (supertag-ai-test-snapshot plain)))
          (should-error (supertag-ai-extract-properties) :type 'user-error)
          (should (equal before (supertag-ai-test-snapshot plain)))))
      (should-not request)
      (should (= 0 (hash-table-count supertag-ai--candidates))))))

(ert-deftest supertag-ai-parser-normalizes-and-drops-invalid-or-equal-values ()
  (cl-multiple-value-bind (candidates dropped)
      (supertag-ai--parse-candidates
       "prefix\n```json\n{\" author \":{\"value\":\" Ada \",\"source\":\"written by Ada\"},\"AUTHOR\":{\"value\":\"Other\"},\"YEAR\":{\"value\":2020,\"source\":null},\"ID\":{\"value\":\"bad\"},\"CUSTOM_ID\":{\"value\":\"bad\"},\"CATEGORY\":{\"value\":\"bad\"},\"TODO\":{\"value\":\"bad\"},\"bad key\":{\"value\":\"bad\"},\"MULTI\":{\"value\":\"a\\nb\"},\"EMPTY\":{\"value\":\" \"},\"SAME\":{\"value\":\"same\"},\"LIST\":{\"value\":[1,2]}}\n```\nsuffix"
       '(("author" . "Before") ("same" . "same")))
    (should (= 10 dropped))
    (should (equal (mapcar (lambda (c) (plist-get c :name)) candidates) '("AUTHOR" "YEAR")))
    (should (equal (plist-get (car candidates) :current) "Before"))
    (should (equal (plist-get (car candidates) :value) "Ada"))
    (should (equal (plist-get (cadr candidates) :value) "2020"))
    (should-not (plist-get (cadr candidates) :source)))
  (cl-multiple-value-bind (candidates dropped)
      (supertag-ai--parse-candidates "prose {\"OK\":{\"value\":\"yes\"}} after" nil)
    (should (equal (plist-get (car candidates) :name) "OK"))
    (should (zerop dropped)))
  (should (supertag-ai--parse-candidates "```\n{\"OK\":{\"value\":\"yes\"}}\n```" nil))
  (dolist (text '("garbage" "```json\n[]\n```" "[]" "{broken}"))
    (should-error (supertag-ai--parse-candidates text nil))))

(ert-deftest supertag-ai-delivery-failures-skip-and-discard-are-zero-write ()
  (supertag-document-test-with-vault
    (supertag-ai-test-with-request
      (with-current-buffer (find-file-noselect file)
        (goto-char (point-min)) (supertag-ai-extract-properties))
      (let ((before (supertag-ai-test-snapshot file)))
        (dolist (response '("[]" "garbage"))
          (supertag-ai-test-deliver request response)
          (should (eq 'failed (plist-get (gethash "document-node" supertag-ai--candidates) :status))))
        (supertag-ai-test-deliver request "provider failed" 'failed)
        (should (equal "provider failed" (plist-get (gethash "document-node" supertag-ai--candidates) :message)))
        (supertag-ai-test-deliver request "{\"AUTHOR\":{\"value\":\"Ada\"},\"YEAR\":{\"value\":2020}}")
        (supertag-ai-skip "document-node" "AUTHOR")
        (should (= 1 (length (plist-get (gethash "document-node" supertag-ai--candidates) :candidates))))
        (supertag-ai-discard "document-node")
        (should-not (gethash "document-node" supertag-ai--candidates))
        (should (equal before (supertag-ai-test-snapshot file)))))))

(ert-deftest supertag-ai-accept-all-stops-at-failed-writer-and-retains-candidate ()
  (supertag-document-test-with-vault
    (supertag-ai-test-with-request
      (with-current-buffer (find-file-noselect file)
        (goto-char (point-min)) (supertag-ai-extract-properties))
      (supertag-ai-test-deliver request "{\"AUTHOR\":{\"value\":\"Ada\"},\"YEAR\":{\"value\":2020}}")
      (let ((calls 0) (before (supertag-ai-test-snapshot file)))
        (cl-letf (((symbol-function 'supertag-service-org-set-property)
                   (lambda (&rest _) (cl-incf calls) (error "write failed"))))
          (supertag-ai-accept-all "document-node"))
        (should (= calls 1))
        (should (= 2 (length (plist-get (gethash "document-node" supertag-ai--candidates) :candidates))))
        (should (equal before (supertag-ai-test-snapshot file))))
      (supertag-ai-accept-all "document-node")
      (should (string-match-p ":AUTHOR: +Ada" (supertag-document-test-disk file)))
      (should (string-match-p ":YEAR: +2020" (supertag-document-test-disk file)))
      (should-not (plist-get (gethash "document-node" supertag-ai--candidates) :candidates))
      (should (eq 'done (plist-get (gethash "document-node" supertag-ai--candidates) :status))))))

(ert-deftest supertag-ai-node-view-review-and-button-write ()
  (supertag-document-test-with-vault
    (supertag-ai-test-with-request
      (let ((view (with-current-buffer (find-file-noselect file)
                    (supertag-view-node-open "document-node"))))
        (with-current-buffer view
          (should-not (string-match-p "Property candidates" (buffer-string)))
          (supertag-ai-extract-properties)
          (should (string-match-p "Extracting with prompt extract-properties" (buffer-string))))
        (supertag-ai-test-deliver request "{\"AUTHOR\":{\"value\":\"Ada\",\"source\":\"written by Ada\"},\"ALPHA\":{\"value\":\"changed\"}}")
        (with-current-buffer view
          (should (string-match-p " PROPERTY CANDIDATES / 02 " (buffer-string)))
          (should (string-match-p "ALPHA: first → changed" (buffer-string)))
          (should (string-match-p "Not found in the body" (buffer-string)))
          (goto-char (point-min)) (search-forward "[Accept]")
          (button-activate (button-at (1- (point)))))
        (should (string-match-p ":AUTHOR: +Ada" (supertag-document-test-disk file)))
        (with-current-buffer view
          (goto-char (point-min)) (search-forward "[Skip]")
          (button-activate (button-at (1- (point))))
          (should (string-match-p "All candidates handled" (buffer-string))))
        (supertag-ai-test-deliver request "bad" 'failed)
        (with-current-buffer view
          (should (string-match-p "Failed: bad" (buffer-string)))
          (goto-char (point-min)) (search-forward "[Discard]")
          (button-activate (button-at (1- (point)))))
        (should-not (gethash "document-node" supertag-ai--candidates))))))

(ert-deftest supertag-ai-submit-error-is-visible-and-synchronous-delivery-survives ()
  (supertag-document-test-with-vault
    (supertag-ai-test-with-request
      (with-current-buffer (find-file-noselect file)
        (goto-char (point-min))
        (cl-letf (((symbol-function 'supertag-ai--submit) (lambda (_) (error "bad request"))))
          (should-error (supertag-ai-extract-properties)))
        (should (eq 'failed (plist-get (gethash "document-node" supertag-ai--candidates) :status)))
        (cl-letf (((symbol-function 'supertag-ai--submit)
                   (lambda (request)
                     (supertag-ai-test-deliver request "{}")
                     '(:run-id "synchronous"))))
          (supertag-ai-extract-properties))
        (should (eq 'done (plist-get (gethash "document-node" supertag-ai--candidates) :status)))
        (should (equal "synchronous" (plist-get (gethash "document-node" supertag-ai--candidates) :run-id)))))))

(ert-deftest supertag-ai-missing-runtime-is-actionable ()
  (let ((original (symbol-function 'fboundp)))
    (cl-letf (((symbol-function 'fboundp)
               (lambda (symbol) (and (not (eq symbol 'superchat-runtime-submit))
                                     (funcall original symbol)))))
      (should (equal (cadr (should-error (supertag-ai-extract-properties) :type 'user-error))
                     "Supertag AI needs the superchat package loaded first (see README)")))))

(ert-deftest supertag-ai-embark-adapter-is-not-command ()
  (should-not (commandp 'supertag-embark-node-extract-properties))
  (should (eq (lookup-key supertag-embark-node-map "x") #'supertag-embark-node-extract-properties)))

(ert-deftest supertag-ai-real-runtime-with-llm-fake ()
  (unless (and (getenv "SUPERTAG_TEST_TMP")
               (file-in-directory-p superchat-data-directory (getenv "SUPERTAG_TEST_TMP")))
    (ert-skip "Runtime data directory must be inside SUPERTAG_TEST_TMP"))
  (skip-unless (and (require 'superchat nil t) (require 'llm-fake nil t)))
  (supertag-document-test-with-vault
    (let* ((supertag-ai--candidates (make-hash-table :test 'equal))
           (output (generate-new-buffer " *llm-fake*"))
           (superchat-llm-backend
            (make-llm-fake :output-to-buffer output
                          :chat-action-func
                          (lambda () "```json\n{\"AUTHOR\":{\"value\":\"Ada\",\"source\":\"written by Ada\"}}\n```"))))
      (unwind-protect
          (progn
            (with-current-buffer (find-file-noselect file)
              (goto-char (point-max)) (insert "written by Ada\n")
              (goto-char (point-min)) (supertag-ai-extract-properties))
            (let ((deadline (+ (float-time) 15)))
              (while (and (eq 'pending (plist-get (gethash "document-node" supertag-ai--candidates) :status))
                          (< (float-time) deadline))
                (accept-process-output nil 0.05)))
            (should (eq 'done (plist-get (gethash "document-node" supertag-ai--candidates) :status)))
            (should (equal "Ada" (plist-get (car (plist-get (gethash "document-node" supertag-ai--candidates) :candidates)) :value)))
            (should (supertag-ai-accept "document-node" "AUTHOR"))
            (should (string-match-p ":AUTHOR: +Ada" (supertag-document-test-disk file))))
        (kill-buffer output)))))

(ert-deftest supertag-ai-save-failure-needs-user-save-and-projection-before-accept ()
  (supertag-document-test-with-vault
    (supertag-ai-test-with-request
      (with-current-buffer (find-file-noselect file)
        (goto-char (point-min))
        (supertag-ai-extract-properties))
      (supertag-ai-test-deliver request "{\"AUTHOR\":{\"value\":\"Ada\"}}")
      (cl-letf (((symbol-function 'save-buffer)
                 (lambda (&rest _) (error "isolated save failure"))))
        (should-not (supertag-ai-accept "document-node" "AUTHOR")))
      (should (plist-get (gethash "document-node" supertag-ai--candidates) :candidates))
      (let ((before (supertag-ai-test-snapshot file)) messages)
        (cl-letf (((symbol-function 'message)
                   (lambda (format-string &rest args)
                     (push (apply #'format format-string args) messages))))
          (should-not (supertag-ai-accept "document-node" "AUTHOR")))
        (should (member "Supertag AI: AUTHOR is in the Org buffer but not saved yet; save node.org, then accept again" messages))
        (should (equal before (supertag-ai-test-snapshot file))))
      (should (plist-get (gethash "document-node" supertag-ai--candidates) :candidates))
      (should-not (string-match-p ":AUTHOR:" (supertag-document-test-disk file)))
      (should-not (plist-get (plist-get (supertag-node-get "document-node") :properties) :AUTHOR))
      ;; Recovery is explicitly performed by the user/test, never the AI action.
      (with-current-buffer (find-file-noselect file) (save-buffer))
      (supertag-service-org-retry-node-projection "document-node" file)
      (should (supertag-ai-accept "document-node" "AUTHOR"))
      (should-not (plist-get (gethash "document-node" supertag-ai--candidates) :candidates))
      (should (string-match-p ":AUTHOR: +Ada" (supertag-document-test-disk file)))
      (should (equal "Ada" (plist-get (plist-get (supertag-node-get "document-node") :properties) :AUTHOR))))))

(ert-deftest supertag-ai-live-projection-is-not-disk-proof ()
  (supertag-document-test-with-vault
    (supertag-ai-test-with-request
      (with-current-buffer (find-file-noselect file)
        (goto-char (point-min)) (supertag-ai-extract-properties)
        (supertag-ai-test-deliver request "{\"AUTHOR\":{\"value\":\"Ada\"}}")
        (org-entry-put nil "AUTHOR" "Ada")
        (supertag-node-sync-at-point)
        (let ((before (supertag-ai-test-snapshot file)))
          (should-not (supertag-ai-accept "document-node" "AUTHOR"))
          (should (equal before (supertag-ai-test-snapshot file))))
        (should (plist-get (gethash "document-node" supertag-ai--candidates) :candidates))
        (should-not (string-match-p ":AUTHOR:" (supertag-document-test-disk file)))
        (save-buffer)
        (should (supertag-ai-accept "document-node" "AUTHOR"))))))

(ert-deftest supertag-ai-conflict-requires-another-review-and-stops-batch ()
  (supertag-document-test-with-vault
    (supertag-ai-test-with-request
      (with-current-buffer (find-file-noselect file)
        (goto-char (point-min)) (supertag-ai-extract-properties))
      (supertag-ai-test-deliver request "{\"ALPHA\":{\"value\":\"Proposed\"},\"AUTHOR\":{\"value\":\"Ada\"}}")
      (supertag-service-org-set-property "document-node" "ALPHA" "User changed")
      (let ((before (supertag-ai-test-snapshot file)))
        (supertag-ai-accept-all "document-node")
        (should (equal before (supertag-ai-test-snapshot file))))
      (let ((candidates (plist-get (gethash "document-node" supertag-ai--candidates) :candidates)))
        (should (= 2 (length candidates)))
        (should (equal "User changed" (plist-get (car candidates) :current)))
        (should (plist-get (car candidates) :stale)))
      (with-temp-buffer
        (supertag-ai-insert-section "document-node")
        (should (string-match-p "changed since extraction: first → User changed" (buffer-string))))
      (should (supertag-ai-accept "document-node" "ALPHA"))
      (should (string-match-p ":ALPHA: +Proposed" (supertag-document-test-disk file)))
      (should (= 1 (length (plist-get (gethash "document-node" supertag-ai--candidates) :candidates)))))))

(ert-deftest supertag-ai-nonobject-responses-fail-without-writes ()
  (supertag-document-test-with-vault
    (supertag-ai-test-with-request
      (with-current-buffer (find-file-noselect file)
        (goto-char (point-min)) (supertag-ai-extract-properties))
      (let ((before (supertag-ai-test-snapshot file)))
        (dolist (text (list "[{\"AUTHOR\":{\"value\":\"Ada\"}}]"
                           (json-serialize "{\"AUTHOR\":{\"value\":\"Ada\"}}")
                           "Result: [{\"AUTHOR\":{\"value\":\"Ada\"}}]"
                           "null" "17" "```json\n[{}]\n```"))
          (supertag-ai-test-deliver request text)
          (should (eq 'failed (plist-get (gethash "document-node" supertag-ai--candidates) :status)))
          (should (equal before (supertag-ai-test-snapshot file)))))
      (dolist (text '("```json\n{\"AUTHOR\":{\"value\":\"Ada\"}}\n```"
                      "Here you go: {\"AUTHOR\":{\"value\":\"Ada\"}} done"))
        (supertag-ai-test-deliver request text)
        (should (eq 'done (plist-get (gethash "document-node" supertag-ai--candidates) :status)))))))

(ert-deftest supertag-ai-source-quotes-are-verified-against-sent-body ()
  (supertag-document-test-with-vault
    (supertag-ai-test-with-request
      (let ((supertag-ai-max-body-chars 25))
        (with-current-buffer (find-file-noselect file)
          (goto-char (point-max)) (insert "written by\nAda\nBeyond sent body\n")
          (goto-char (point-min)) (supertag-ai-extract-properties)))
      (supertag-ai-test-deliver request "{\"AUTHOR\":{\"value\":\"Ada\",\"source\":\"written by Ada\"},\"FAKE\":{\"value\":\"x\",\"source\":\"Invented quote\"},\"EMPTY\":{\"value\":\"x\",\"source\":\"  \"},\"BEYOND\":{\"value\":\"x\",\"source\":\"Beyond sent body\"}}")
      (let* ((entry (gethash "document-node" supertag-ai--candidates))
             (candidates (plist-get entry :candidates)))
        (should (= 25 (length (plist-get entry :body))))
        (should (plist-get (car candidates) :source-verified))
        (dolist (candidate (cdr candidates)) (should-not (plist-get candidate :source-verified))))
      (with-temp-buffer
        (supertag-ai-insert-section "document-node")
        (should (string-match-p "      written by Ada" (buffer-string)))
        (should (string-match-p "      Invented quote" (buffer-string)))
        (should (string-match-p "      Beyond sent body" (buffer-string)))
        (should-not (string-match-p "⚠ Not found in the body\\|unverified:" (buffer-string)))
        (should-not (string-match-p "      [[:space:]]*\n" (buffer-string)))))))

(ert-deftest supertag-ai-late-response-cannot-replace-a-new-request ()
  (supertag-document-test-with-vault
    (supertag-ai-test-with-request
      (with-current-buffer (find-file-noselect file)
        (goto-char (point-min)) (supertag-ai-extract-properties)
        (let ((a request))
          (supertag-ai-discard "document-node")
          (supertag-ai-extract-properties)
          (supertag-ai-test-deliver request "{\"AUTHOR\":{\"value\":\"B\"}}")
          (let ((before (copy-tree (gethash "document-node" supertag-ai--candidates))))
            (supertag-ai-test-deliver a "{\"AUTHOR\":{\"value\":\"A\"}}")
            (should (equal before (gethash "document-node" supertag-ai--candidates))))))))
)

(ert-deftest supertag-ai-disk-reader-ignores-example-id-before-real-target ()
  (supertag-document-test-with-vault
    (supertag-ai-test-with-request
      (with-current-buffer (find-file-noselect file)
        (goto-char (point-min)) (supertag-ai-extract-properties)
        (supertag-ai-test-deliver request "{\"AUTHOR\":{\"value\":\"Ada\"}}")
        (goto-char (point-min))
        (insert "* Example\n:PROPERTIES:\n:ID: decoy\n:AUTHOR: Ada\n:END:\n#+begin_src org\n:ID: document-node\n#+end_src\n")
        (save-buffer)
        (goto-char (point-min)) (re-search-forward "^\\* Property Node")
        (org-back-to-heading t) (org-entry-put nil "AUTHOR" "Ada")
        (let ((disk (supertag-document-test-disk file)))
          (should-not (supertag-ai--disk-value "document-node" "AUTHOR"))
          (should-not (supertag-ai-accept "document-node" "AUTHOR"))
          (should (plist-get (gethash "document-node" supertag-ai--candidates) :candidates))
          (should (equal disk (supertag-document-test-disk file))))
        (save-buffer)
        (should (equal "Ada" (supertag-ai--disk-value "document-node" "AUTHOR")))
        (should (supertag-ai-accept "document-node" "AUTHOR"))))))

(ert-deftest supertag-ai-disk-reader-rejects-only-examples-and-ambiguous-ids ()
  (supertag-document-test-with-vault
    (with-current-buffer (find-file-noselect file)
      (goto-char (point-min)) (org-entry-delete nil "ID")
      (org-entry-put nil "AUTHOR" "Ada")
      (goto-char (point-max))
      (insert "\n:ID: document-node\n#+begin_src org\n:ID: document-node\n#+end_src\n")
      (save-buffer)
      (should-not (supertag-ai--disk-value "document-node" "AUTHOR"))
      (goto-char (point-min)) (org-entry-put nil "ID" "document-node")
      (goto-char (point-max))
      (insert "* Duplicate\n:PROPERTIES:\n:ID: document-node\n:AUTHOR: Other\n:END:\n")
      (save-buffer)
      (should-not (supertag-ai--disk-value "document-node" "AUTHOR")))))(ert-deftest supertag-ai-cancelled-is-terminal-and-ignores-late-completion ()
  (supertag-document-test-with-vault
    (supertag-ai-test-with-request
      (with-current-buffer (find-file-noselect file)
        (goto-char (point-min)) (supertag-ai-extract-properties))
      (let ((before (supertag-ai-test-snapshot file)))
        (supertag-ai-test-deliver request "[Cancelled by user]" 'cancelled)
        (should (eq 'cancelled (plist-get (gethash "document-node" supertag-ai--candidates) :status)))
        (supertag-ai-test-deliver request "{\"AUTHOR\":{\"value\":\"Ada\"}}" 'completed)
        (should (eq 'cancelled (plist-get (gethash "document-node" supertag-ai--candidates) :status)))
        (should-not (plist-get (gethash "document-node" supertag-ai--candidates) :candidates))
        (should (equal before (supertag-ai-test-snapshot file)))))))

(ert-deftest supertag-ai-node-view-shows-cancelled-and-retry-resubmits ()
  (supertag-document-test-with-vault
    (supertag-ai-test-with-request
      (let ((view (with-current-buffer (find-file-noselect file)
                    (supertag-view-node-open "document-node")))
            (submits 0))
        (cl-letf* ((original (symbol-function 'supertag-ai--submit))
                   ((symbol-function 'supertag-ai--submit)
                    (lambda (value) (cl-incf submits) (funcall original value))))
          (with-current-buffer view (supertag-ai-extract-properties))
          (should (= submits 1))
          (with-current-buffer view
            (should (string-match-p "\\[Cancel\\]" (buffer-string))))
          (supertag-ai-test-deliver request "[Cancelled by user]" 'cancelled)
          (with-current-buffer view
            (should (string-match-p "Cancelled\\." (buffer-string)))
            (should (string-match-p "\\[Retry\\]" (buffer-string)))
            (should-not (string-match-p "Failed:" (buffer-string)))
            (goto-char (point-min)) (search-forward "[Retry]")
            (button-activate (button-at (1- (point)))))
          (should (= submits 2))
          (should (eq 'pending (plist-get (gethash "document-node" supertag-ai--candidates) :status)))
          (should (eq 'extract-properties (plist-get (gethash "document-node" supertag-ai--candidates) :prompt)))
          (with-current-buffer view
            (should (string-match-p "Extracting with prompt extract-properties" (buffer-string)))))))))

(ert-deftest supertag-ai-cancel-extraction-command-cancels-the-runtime-run ()
  (supertag-document-test-with-vault
    (supertag-ai-test-with-request
      (let ((view (with-current-buffer (find-file-noselect file)
                    (supertag-view-node-open "document-node")))
            cancelled)
        (cl-letf (((symbol-function 'superchat-runtime-cancel)
                   (lambda (run-id &rest _) (push run-id cancelled) t)))
          (with-current-buffer view
            (should-error (supertag-ai-cancel-extraction) :type 'user-error)
            (supertag-ai-extract-properties)
            (supertag-ai-cancel-extraction)
            (should (equal cancelled '("run")))
            (should (eq 'cancelled (plist-get (gethash "document-node" supertag-ai--candidates) :status)))
            (should-error (supertag-ai-cancel-extraction) :type 'user-error))
          (supertag-ai-test-deliver request "[Cancelled by user]" 'cancelled)
          (should (equal cancelled '("run")))
          (should (eq 'cancelled (plist-get (gethash "document-node" supertag-ai--candidates) :status))))))))

(ert-deftest supertag-ai-show-raw-exposes-the-unparsable-response ()
  (supertag-document-test-with-vault
    (supertag-ai-test-with-request
      (let ((view (with-current-buffer (find-file-noselect file)
                    (supertag-view-node-open "document-node"))))
        (with-current-buffer view (supertag-ai-extract-properties))
        (supertag-ai-test-deliver request "garbage" 'completed)
        (should (eq 'failed (plist-get (gethash "document-node" supertag-ai--candidates) :status)))
        (should (equal "garbage" (plist-get (gethash "document-node" supertag-ai--candidates) :raw)))
        (with-current-buffer view
          (should (string-match-p "\\[Show raw\\]" (buffer-string)))
          (goto-char (point-min)) (search-forward "[Show raw]")
          (button-activate (button-at (1- (point)))))
        (should (equal "garbage" (with-current-buffer "*Supertag AI Raw*" (buffer-string))))
        (should-not (commandp #'supertag-ai-show-raw))
        (should-not (commandp #'supertag-ai-cancel))
        (should (commandp #'supertag-ai-cancel-extraction))
        (kill-buffer "*Supertag AI Raw*")))))


(defun supertag-ai-test--three-tagged-nodes (file)
  "Write three nodes tagged #batch into FILE; return the tag id."
  (supertag-tag-create '(:name "batch"))
  (with-temp-file file
    (insert "* One #batch\n:PROPERTIES:\n:ID: n1\n:END:\nBody one.\n"
            "* Two #batch\n:PROPERTIES:\n:ID: n2\n:END:\nBody two.\n"
            "* Three #batch\n:PROPERTIES:\n:ID: n3\n:END:\nBody three.\n"
            "* Untagged\n:PROPERTIES:\n:ID: n4\n:END:\nBody four.\n"))
  (supertag-reindex-org)
  (supertag-tag-resolve-occurrence "batch"))

(defun supertag-ai-test--pending-count ()
  (let ((n 0))
    (maphash (lambda (_ e) (when (eq (plist-get e :status) 'pending) (cl-incf n)))
             supertag-ai--candidates)
    n))

(ert-deftest supertag-ai-tag-batch-submits-serially-and-finishes ()
  (supertag-document-test-with-vault
    (let ((supertag-ai--candidates (make-hash-table :test 'equal))
          (supertag-ai--batch nil)
          (tag (supertag-ai-test--three-tagged-nodes file))
          requests max-pending)
      (cl-letf (((symbol-function 'superchat-runtime-submit) #'ignore)
                ((symbol-function 'supertag-ai--submit)
                 (lambda (value) (push value requests)
                   (setq max-pending (max (or max-pending 0) (supertag-ai-test--pending-count)))
                   (list :run-id (format "run%d" (length requests)) :turn-id "turn")))
                ((symbol-function 'supertag-ui-read-tag) (lambda (&rest _) tag))
                ((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
        (supertag-ai-extract-tag-properties)
        (should (= 1 (length requests)))
        (should (equal "n1" (plist-get (plist-get (car requests) :origin) :node-id)))
        (should supertag-ai--batch)
        (supertag-ai-test-deliver (car requests) "{\"KIND\": {\"value\": \"one\"}}")
        (should (= 2 (length requests)))
        (should (equal "n2" (plist-get (plist-get (car requests) :origin) :node-id)))
        (should (= 1 (supertag-ai-test--pending-count)))
        (supertag-ai-test-deliver (car requests) "garbage")
        (should (= 3 (length requests)))
        (should (equal "n3" (plist-get (plist-get (car requests) :origin) :node-id)))
        (supertag-ai-test-deliver (car requests) "{\"KIND\": {\"value\": \"three\"}}")
        (should (= 3 (length requests)))
        (should-not supertag-ai--batch)
        (should (= 1 max-pending))
        (should (eq 'done (plist-get (gethash "n1" supertag-ai--candidates) :status)))
        (should (eq 'failed (plist-get (gethash "n2" supertag-ai--candidates) :status)))
        (should (eq 'done (plist-get (gethash "n3" supertag-ai--candidates) :status)))
        (should-not (gethash "n4" supertag-ai--candidates))
        (should (commandp #'supertag-ai-extract-tag-properties))
        (should (commandp #'supertag-ai-cancel-batch))))))

(ert-deftest supertag-ai-tag-batch-skips-nodes-already-pending-and-refuses-a-second-batch ()
  (supertag-document-test-with-vault
    (let ((supertag-ai--candidates (make-hash-table :test 'equal))
          (supertag-ai--batch nil)
          (tag (supertag-ai-test--three-tagged-nodes file))
          requests)
      (cl-letf (((symbol-function 'superchat-runtime-submit) #'ignore)
                ((symbol-function 'supertag-ai--submit)
                 (lambda (value) (push value requests) (list :run-id "run" :turn-id "turn")))
                ((symbol-function 'supertag-ui-read-tag) (lambda (&rest _) tag))
                ((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
        (supertag-ai--start "n2" 'extract-properties)
        (let ((single (car requests)))
          (supertag-ai-extract-tag-properties)
          (should-error (supertag-ai-extract-tag-properties) :type 'user-error)
          (should (equal "n1" (plist-get (plist-get (car requests) :origin) :node-id)))
          (supertag-ai-test-deliver (car requests) "{}")
          ;; n2 was already pending, so the batch moved straight on to n3.
          (should (equal "n3" (plist-get (plist-get (car requests) :origin) :node-id)))
          (should (eq 'pending (plist-get (gethash "n2" supertag-ai--candidates) :status)))
          (supertag-ai-test-deliver (car requests) "{}")
          (should-not supertag-ai--batch)
          (should (= 3 (length requests)))
          (supertag-ai-test-deliver single "{}")
          (should (eq 'done (plist-get (gethash "n2" supertag-ai--candidates) :status))))))))

(ert-deftest supertag-ai-cancel-batch-cancels-the-run-and-clears-the-queue ()
  (supertag-document-test-with-vault
    (let ((supertag-ai--candidates (make-hash-table :test 'equal))
          (supertag-ai--batch nil)
          (tag (supertag-ai-test--three-tagged-nodes file))
          requests cancelled)
      (cl-letf (((symbol-function 'superchat-runtime-submit) #'ignore)
                ((symbol-function 'superchat-runtime-cancel) (lambda (id) (push id cancelled)))
                ((symbol-function 'supertag-ai--submit)
                 (lambda (value) (push value requests)
                   (list :run-id (format "run%d" (length requests)) :turn-id "turn")))
                ((symbol-function 'supertag-ui-read-tag) (lambda (&rest _) tag))
                ((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
        (should-error (supertag-ai-cancel-batch) :type 'user-error)
        (supertag-ai-extract-tag-properties)
        (supertag-ai-cancel-batch)
        (should-not supertag-ai--batch)
        (should (equal '("run1") cancelled))
        (should (eq 'cancelled (plist-get (gethash "n1" supertag-ai--candidates) :status)))
        (should (= 1 (length requests)))
        ;; A late completion for the cancelled run neither revives it nor restarts the batch.
        (supertag-ai-test-deliver (car requests) "{}")
        (should (= 1 (length requests)))
        (should (eq 'cancelled (plist-get (gethash "n1" supertag-ai--candidates) :status)))
        (should-not (gethash "n2" supertag-ai--candidates))
        ;; Cancelling a single batch node from its own section moves the batch along.
        (supertag-ai-extract-tag-properties)
        (supertag-ai-cancel "n1")
        (should (equal "n2" (plist-get (plist-get (car requests) :origin) :node-id)))
        (should (equal "n2" (plist-get supertag-ai--batch :current)))
        (supertag-ai-cancel-batch)))))
(defun supertag-ai-test--run-batch-to-plan (file)
  "Run a batch over FILE's #batch nodes with fixed answers; return the plan buffer."
  (let ((tag (supertag-ai-test--three-tagged-nodes file))
        requests)
    (cl-letf (((symbol-function 'superchat-runtime-submit) #'ignore)
              ((symbol-function 'supertag-ai--submit)
               (lambda (value) (push value requests) (list :run-id "run" :turn-id "turn")))
              ((symbol-function 'supertag-ui-read-tag) (lambda (&rest _) tag))
              ((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
      (supertag-ai-extract-tag-properties)
      (supertag-ai-test-deliver (car requests) "{\"KIND\": {\"value\": \"one\", \"source\": \"Body one.\"}}")
      (supertag-ai-test-deliver (car requests) "{\"KIND\": {\"value\": \"two\", \"source\": \"Body two.\"}}")
      (supertag-ai-test-deliver (car requests) "{\"KIND\": {\"value\": \"three\", \"source\": \"Body three.\"}}"))
    (let ((plan (get-buffer supertag-ai-plan-buffer-name)))
      (should plan)
      plan)))

(ert-deftest supertag-ai-plan-opens-after-the-batch-and-applies-unskipped-lines ()
  (supertag-document-test-with-vault
    (let ((supertag-ai--candidates (make-hash-table :test 'equal))
          (supertag-ai--batch nil))
      (save-window-excursion
        (let ((plan (supertag-ai-test--run-batch-to-plan file)))
          (unwind-protect
              (with-current-buffer plan
                (should (derived-mode-p 'supertag-ai-plan-mode))
                (should (string-match-p "3 candidate(s) across 3 node(s)" (buffer-string)))
                (should (string-match-p "  One\n    \\[write\\] KIND: one" (buffer-string)))
                (should (string-match-p "  Three\n    \\[write\\] KIND: three" (buffer-string)))
                (goto-char (point-min)) (search-forward "KIND: three")
                (supertag-ai-plan-toggle-skip)
                (should (string-match-p "\\[skip\\] KIND: three" (buffer-string)))
                (supertag-ai-plan-apply)
                (let ((disk (supertag-document-test-disk file)))
                  (should (string-match-p ":ID: n1\n:KIND: +one\n" disk))
                  (should (string-match-p ":ID: n2\n:KIND: +two\n" disk))
                  (should-not (string-match-p ":KIND: three" disk)))
                (should-not (plist-get (gethash "n1" supertag-ai--candidates) :candidates))
                (should (plist-get (gethash "n3" supertag-ai--candidates) :candidates))
                (should (string-match-p "1 candidate(s)" (buffer-string)))
                (should (string-match-p "\\[write\\] KIND: three" (buffer-string))))
            (kill-buffer plan)))))))

(ert-deftest supertag-ai-plan-refuses-lines-whose-candidate-changed-since-the-snapshot ()
  (supertag-document-test-with-vault
    (let ((supertag-ai--candidates (make-hash-table :test 'equal))
          (supertag-ai--batch nil)
          (before (supertag-document-test-disk file)))
      (save-window-excursion
        (let ((plan (supertag-ai-test--run-batch-to-plan file)))
          (unwind-protect
              (progn
                ;; The model answer for n2 is replaced behind the plan's back.
                (let* ((entry (gethash "n2" supertag-ai--candidates))
                       (candidate (car (plist-get entry :candidates))))
                  (plist-put candidate :value "TWO"))
                (supertag-ai-skip "n3" "KIND")
                (with-current-buffer plan
                  (let (summary)
                    (cl-letf (((symbol-function 'message)
                               (lambda (fmt &rest args)
                                 (when (string-prefix-p "Supertag AI plan:" fmt)
                                   (setq summary (apply #'format fmt args))))))
                      (supertag-ai-plan-apply))
                    (should (equal summary "Supertag AI plan: 1 written, 0 skipped, 2 plan changed, 0 unsaved file")))
                  (let ((disk (supertag-document-test-disk file)))
                    (should (string-match-p ":ID: n1\n:KIND: +one\n" disk))
                    (should-not (string-match-p "KIND: two\\|KIND: TWO\\|KIND: three" disk)))
                  (should (string-match-p "\\[write\\] KIND: TWO" (buffer-string)))
                  (should-not (string-match-p "KIND: three" (buffer-string)))))
            (kill-buffer plan)))
        (should-not (equal before (supertag-document-test-disk file)))))))

(ert-deftest supertag-ai-plan-skips-nodes-whose-file-has-unsaved-drafts ()
  (supertag-document-test-with-vault
    (let ((supertag-ai--candidates (make-hash-table :test 'equal))
          (supertag-ai--batch nil))
      (save-window-excursion
        (let ((plan (supertag-ai-test--run-batch-to-plan file))
              (before (supertag-document-test-disk file))
              (org (find-file-noselect file)))
          (unwind-protect
              (progn
                (with-current-buffer org (goto-char (point-max)) (insert "draft\n"))
                (with-current-buffer plan
                  (let (summary)
                    (cl-letf (((symbol-function 'message)
                               (lambda (fmt &rest args)
                                 (when (string-prefix-p "Supertag AI plan:" fmt)
                                   (setq summary (apply #'format fmt args))))))
                      (supertag-ai-plan-apply))
                    (should (equal summary "Supertag AI plan: 0 written, 0 skipped, 0 plan changed, 3 unsaved file")))
                  (should (string-match-p "3 candidate(s)" (buffer-string))))
                (should (equal before (supertag-document-test-disk file)))
                (should (buffer-modified-p org))
                (should (string-suffix-p "draft\n" (with-current-buffer org (buffer-string))))
                (should (commandp #'supertag-ai-plan-apply))
                (should (commandp #'supertag-ai-plan-toggle-skip))
                (should (eq #'supertag-ai-plan-apply (lookup-key supertag-ai-plan-mode-map "a")))
                (should (eq #'supertag-ai-plan-toggle-skip (lookup-key supertag-ai-plan-mode-map "k"))))
            (kill-buffer plan)))))))



(defmacro supertag-ai-test-with-batch (&rest body)
  `(supertag-document-test-with-vault
    (let ((supertag-ai--candidates (make-hash-table :test 'equal))
          (supertag-ai--batch nil)
          (tag (supertag-ai-test--three-tagged-nodes file)) requests)
      (unwind-protect
        (cl-letf (((symbol-function 'superchat-runtime-submit) #'ignore)
                  ((symbol-function 'supertag-ui-read-tag) (lambda (&rest _) tag))
                  ((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
          ,@body)
        (when (get-buffer supertag-ai-plan-buffer-name)
          (kill-buffer supertag-ai-plan-buffer-name))))))
(ert-deftest supertag-ai-review-sync-completion ()
  (supertag-ai-test-with-batch
    (cl-letf (((symbol-function 'supertag-ai--submit)
               (lambda (req)
                 (push req requests)
                 (supertag-ai-test-deliver req "{\"KIND\": {\"value\": \"one\"}}")
                 (list :run-id "sync" :turn-id "turn"))))
      (supertag-ai-extract-tag-properties)
      (princ (format "SYNC requests=%d batch=%S n1=%S\n" (length requests)
                     supertag-ai--batch (plist-get (gethash "n1" supertag-ai--candidates) :status)))
      (should (= 3 (length requests)))
      (should-not supertag-ai--batch))))
(ert-deftest supertag-ai-review-plan-inplace-change ()
  (supertag-document-test-with-vault
    (let ((supertag-ai--candidates (make-hash-table :test 'equal)) (supertag-ai--batch nil))
      (let ((plan (supertag-ai-test--run-batch-to-plan file)))
        (unwind-protect
          (with-current-buffer plan
            (let* ((candidate (car (plist-get (gethash "n1" supertag-ai--candidates) :candidates)))
                   (value (plist-get candidate :value)))
              (princ (format "PLAN shared=%S displayed-one=%S\n"
                (eq value (plist-get (car supertag-ai-plan--items) :value))
                (not (null (string-match-p "KIND: one" (buffer-string))))))
              (aset value 0 ?X)
              (should (string-match-p "KIND: one" (buffer-string)))
              (supertag-ai-plan-apply)
              (princ (format "PLAN disk-Xne=%S\n"
                 (not (null (string-match-p ":KIND: +Xne" (supertag-document-test-disk file))))))
              (should-not (string-match-p ":KIND: +Xne" (supertag-document-test-disk file)))))
          (kill-buffer plan))))))
(ert-deftest supertag-ai-review-sync-cancel-and-late-response-control ()
  (supertag-ai-test-with-batch
    (cl-letf (((symbol-function 'supertag-ai--submit)
               (lambda (req) (push req requests) (list :run-id (format "r%d" (length requests))))))
      (supertag-ai-extract-tag-properties)
      (let ((first (car requests)))
        (cl-letf (((symbol-function 'superchat-runtime-cancel)
                   (lambda (_) (supertag-ai-test-deliver first "cancelled" 'cancelled))))
          (supertag-ai-cancel "n1"))
        (should (= 2 (length requests)))
        (should (equal "n2" (plist-get supertag-ai--batch :current)))
        (supertag-ai-test-deliver first "{}")
        (should (eq 'cancelled (plist-get (gethash "n1" supertag-ai--candidates) :status)))
        (let ((second (car requests)))
          (cl-letf (((symbol-function 'superchat-runtime-cancel)
                     (lambda (_) (supertag-ai-test-deliver second "cancelled" 'cancelled))))
            (supertag-ai-cancel-batch))
          (supertag-ai-test-deliver second "{}")
          (should-not supertag-ai--batch)
          (should (= 2 (length requests))))))))
(ert-deftest supertag-ai-review-submit-error-control ()
  (supertag-ai-test-with-batch
    (cl-letf (((symbol-function 'supertag-ai--submit)
               (lambda (req) (push req requests)
                 (when (= 1 (length requests)) (error "probe-submit-failure"))
                 (list :run-id "run"))))
      (supertag-ai-extract-tag-properties)
      (should (= 2 (length requests)))
      (should (eq 'failed (plist-get (gethash "n1" supertag-ai--candidates) :status)))
      (supertag-ai-test-deliver (car requests) "{}")
      (supertag-ai-test-deliver (car requests) "{}")
      (should (= 3 (length requests)))
      (should-not supertag-ai--batch))))
(ert-deftest supertag-ai-review-vault-reset-clears-batch ()
  (supertag-ai-test-with-batch
    (cl-letf (((symbol-function 'supertag-ai--submit)
               (lambda (req) (push req requests) (list :run-id "run"))))
      (supertag-ai-extract-tag-properties)
      (let ((old (car requests)))
        (supertag-ai--reset-runtime)
        (supertag-ai-test-deliver old "{}")
        (princ (format "RESET candidates=%d batch=%S\n" (hash-table-count supertag-ai--candidates)
                       supertag-ai--batch))
        (should-not supertag-ai--batch)))))

(ert-deftest supertag-ai-review-sync-failure-error-and-mixed-delivery ()
  (supertag-ai-test-with-batch
    (cl-letf (((symbol-function 'supertag-ai--submit)
               (lambda (req)
                 (push req requests)
                 (pcase (length requests)
                   (1 (supertag-ai-test-deliver req "failed" 'failed))
                   (2 (error "submit rejected")))
                 (list :run-id "run"))))
      (supertag-ai-extract-tag-properties)
      (should (= 3 (length requests)))
      (should (equal "n3" (plist-get supertag-ai--batch :current)))
      (should (eq 'failed (plist-get (gethash "n1" supertag-ai--candidates) :status)))
      (should (eq 'failed (plist-get (gethash "n2" supertag-ai--candidates) :status)))
      (supertag-ai-test-deliver (car requests) "{}")
      (should-not supertag-ai--batch))))

(ert-deftest supertag-ai-review-long-synchronous-queue ()
  (supertag-ai-test-with-batch
    (with-temp-file file
      (dotimes (i 300)
        (insert (format "* Node %d #batch\n:PROPERTIES:\n:ID: long-%03d\n:END:\nBody.\n" i i))))
    (supertag-reindex-org)
    (cl-letf (((symbol-function 'supertag-ai--submit)
               (lambda (req)
                 (push req requests)
                 (should (= 1 (supertag-ai-test--pending-count)))
                 (supertag-ai-test-deliver req "{}")
                 (list :run-id "sync"))))
      (supertag-ai-extract-tag-properties)
      (should (= 300 (length requests)))
      (should-not supertag-ai--batch)
      (with-current-buffer supertag-ai-plan-buffer-name
        (should (= 300 (length supertag-ai-plan--nodes)))))))

(ert-deftest supertag-ai-review-plan-inplace-change-is-row-local ()
  (supertag-document-test-with-vault
    (let ((supertag-ai--candidates (make-hash-table :test 'equal))
          (supertag-ai--batch nil))
      (let ((plan (supertag-ai-test--run-batch-to-plan file)))
        (unwind-protect
            (with-current-buffer plan
              (let* ((candidate (car (plist-get (gethash "n1" supertag-ai--candidates) :candidates)))
                     (snapshot (car supertag-ai-plan--items))
                     (disk (supertag-document-test-disk file)) summary)
                (dolist (key '(:name :value))
                  (should-not (eq (plist-get snapshot key) (plist-get candidate key))))
                (should-not (plist-get snapshot :current))
                (aset (plist-get candidate :value) 0 ?X)
                (should (string-match-p "KIND: one" (buffer-string)))
                (should (equal (plist-get snapshot :value) "one"))
                (cl-letf (((symbol-function 'message)
                           (lambda (fmt &rest args)
                             (when (string-prefix-p "Supertag AI plan:" fmt)
                               (setq summary (apply #'format fmt args))))))
                  (supertag-ai-plan-apply))
                (should (equal summary "Supertag AI plan: 2 written, 0 skipped, 1 plan changed, 0 unsaved file"))
                ;; The affected subtree is byte-identical; other rows really save.
                (should (equal (car (split-string disk "\\* Two"))
                               (car (split-string (supertag-document-test-disk file) "\\* Two"))))
                (should-not (supertag-ai--disk-value "n1" "KIND"))
                (should (equal "two" (supertag-ai--disk-value "n2" "KIND")))
                (should (equal "three" (supertag-ai--disk-value "n3" "KIND")))))
          (kill-buffer plan))))))

(ert-deftest supertag-ai-review-plan-string-fields-are-independent ()
  (supertag-ai-test-with-batch
    (let* ((id (copy-sequence "n1"))
           (name (copy-sequence "KIND"))
           (value (copy-sequence "new"))
           (current (copy-sequence "old"))
           (path (plist-get (supertag-node-get id) :file)))
      (puthash id (list :status 'done :candidates
                       (list (list :name name :value value :current current)))
               supertag-ai--candidates)
      (let ((row (car (supertag-ai--plan-items (list id)))))
        (cl-mapc (lambda (key original)
                   (should (equal (plist-get row key) original))
                   (should-not (eq (plist-get row key) original)))
                 '(:node-id :name :value :current :file)
                 (list id name value current path))))))

(ert-deftest supertag-ai-review-reset-invalidates-callbacks-and-old-plan ()
  (supertag-ai-test-with-batch
    (cl-letf (((symbol-function 'supertag-ai--submit)
               (lambda (req) (push req requests) (list :run-id "run"))))
      (supertag-ai-extract-tag-properties)
      (let ((old (car requests)) cancelled)
        (with-current-buffer (get-buffer-create supertag-ai-plan-buffer-name)
          (supertag-ai-plan-mode)
          (setq supertag-ai-plan--nodes '("n1")
                supertag-ai-plan--items '((:node-id "n1" :name "KIND" :value "old"))))
        (cl-letf (((symbol-function 'superchat-runtime-cancel)
                   (lambda (run)
                     (push run cancelled)
                     (should-not supertag-ai--batch)
                     (should (= 0 (hash-table-count supertag-ai--candidates)))
                     (supertag-ai-test-deliver old "cancelled" 'cancelled)
                     (should (= 1 (length requests)))
                     (error "cancel transport failed"))))
          (supertag-ai--reset-runtime))
        (should (equal cancelled '("run")))
        (should-not supertag-ai--batch)
        (with-current-buffer supertag-ai-plan-buffer-name
          (should-not supertag-ai-plan--nodes)
          (should-not supertag-ai-plan--items))
        (supertag-ai-extract-tag-properties)
        (should (= 2 (length requests)))
        (let ((new-entry (gethash "n1" supertag-ai--candidates))
              (disk (supertag-document-test-disk file)))
          (supertag-ai-test-deliver old "{\"KIND\": {\"value\": \"old\"}}")
          (should (eq new-entry (gethash "n1" supertag-ai--candidates)))
          (should (eq 'pending (plist-get new-entry :status)))
          (with-current-buffer supertag-ai-plan-buffer-name (supertag-ai-plan-apply))
          (should (equal disk (supertag-document-test-disk file))))
        (supertag-ai-cancel-batch)))))

(ert-deftest supertag-ai-review-reset-during-submit-cannot-clobber-new-batch ()
  (supertag-ai-test-with-batch
    (cl-letf (((symbol-function 'supertag-ai--submit)
               (lambda (req)
                 (push req requests)
                 (when (= 1 (length requests))
                   (supertag-ai--reset-runtime)
                   (supertag-ai-extract-tag-properties)
                   (error "old submit failed after reset"))
                 (list :run-id "new"))))
      (supertag-ai-extract-tag-properties)
      (should (= 2 (length requests)))
      (should (equal "n1" (plist-get supertag-ai--batch :current)))
      (should (eq 'pending (plist-get (gethash "n1" supertag-ai--candidates) :status)))
      (should (equal "new" (plist-get (gethash "n1" supertag-ai--candidates) :run-id)))
      (supertag-ai-test-deliver (cadr requests) "{}")
      (should (= 2 (length requests)))
      (supertag-ai-cancel-batch))))

(ert-deftest supertag-ai-review-cancel-during-submit-preserves-new-owner ()
  (supertag-ai-test-with-batch
    (cl-letf (((symbol-function 'supertag-ai--submit)
               (lambda (req)
                 (push req requests)
                 (if (= 1 (length requests))
                     (progn
                       (supertag-ai-cancel-batch)
                       (supertag-ai-extract-tag-properties)
                       (list :run-id "old"))
                   (list :run-id "new")))))
      (supertag-ai-extract-tag-properties)
      (should (= 2 (length requests)))
      (should (equal "n1" (plist-get supertag-ai--batch :current)))
      (should (equal "new" (plist-get (gethash "n1" supertag-ai--candidates) :run-id)))
      (supertag-ai-test-deliver (cadr requests) "{}")
      (should (= 2 (length requests)))
      (should (eq 'pending (plist-get (gethash "n1" supertag-ai--candidates) :status)))
      (supertag-ai-cancel-batch))))

(ert-deftest supertag-ai-cancel-return-preserves-replacement-batch-owner ()
  (supertag-ai-test-with-batch
    (cl-letf (((symbol-function 'supertag-ai--submit)
               (lambda (req)
                 (push req requests)
                 (list :run-id (format "run%d" (length requests))))))
      (supertag-ai-extract-tag-properties)
      (let* ((old (car requests))
             (old-token (plist-get (gethash "n1" supertag-ai--candidates) :token))
             (disk (supertag-document-test-disk file))
             new-entry new-token new-batch)
        (cl-letf (((symbol-function 'superchat-runtime-cancel)
                   (lambda (run)
                     (should (equal run "run1"))
                     (should-not supertag-ai--batch)
                     (supertag-ai-test-deliver old "cancelled" 'cancelled)
                     (supertag-ai-extract-tag-properties)
                     (setq new-entry (gethash "n1" supertag-ai--candidates)
                           new-token (plist-get new-entry :token)
                           new-batch supertag-ai--batch))))
          (supertag-ai-cancel-batch))
        (should (eq new-entry (gethash "n1" supertag-ai--candidates)))
        (should (eq new-token (plist-get new-entry :token)))
        (should-not (eq old-token new-token))
        (should (equal "run2" (plist-get new-entry :run-id)))
        (should (eq 'pending (plist-get new-entry :status)))
        (should (eq new-batch supertag-ai--batch))
        (should (equal "n1" (plist-get new-batch :current)))
        (should (equal '("n2" "n3") (plist-get new-batch :queue)))
        (should (= 2 (length requests)))
        (supertag-ai-test-deliver old "{\"KIND\": {\"value\": \"late\"}}")
        (should (eq new-entry (gethash "n1" supertag-ai--candidates)))
        (should (eq 'pending (plist-get new-entry :status)))
        (should (= 2 (length requests)))
        (should (equal disk (supertag-document-test-disk file)))))))

(ert-deftest supertag-ai-cancel-sync-delivery-is-not-finalized-twice ()
  (supertag-ai-test-with-batch
    (cl-letf (((symbol-function 'supertag-ai--submit)
               (lambda (req) (push req requests) (list :run-id "run"))))
      (supertag-ai-extract-tag-properties)
      (let* ((old (car requests))
             (refreshes 0)
             (record-refresh (lambda (id) (when (equal id "n1") (cl-incf refreshes)))))
        ;; Observe real refresh calls; do not replace the renderer or delivery.
        (advice-add 'supertag-ai--refresh :after record-refresh)
        (unwind-protect
            (cl-letf (((symbol-function 'superchat-runtime-cancel)
                       (lambda (_run)
                         (supertag-ai-test-deliver old "cancelled" 'cancelled))))
              (supertag-ai-cancel "n1"))
          (advice-remove 'supertag-ai--refresh record-refresh))
        (should (= 1 refreshes))
        (should (= 2 (length requests)))
        (should (equal "n2" (plist-get supertag-ai--batch :current)))
        (should (eq 'cancelled (plist-get (gethash "n1" supertag-ai--candidates) :status)))
        (supertag-ai-test-deliver old "{}")
        (should (= 2 (length requests)))))))

(ert-deftest supertag-ai-cancel-without-callback-keeps-order-and-error-semantics ()
  (supertag-ai-test-with-batch
    (cl-letf (((symbol-function 'supertag-ai--submit)
               (lambda (req) (push req requests) (list :run-id "run"))))
      (supertag-ai-extract-tag-properties)
      (let ((entry (gethash "n1" supertag-ai--candidates))
            (batch supertag-ai--batch))
        (cl-letf (((symbol-function 'superchat-runtime-cancel)
                   (lambda (_run)
                     (should (eq 'pending (plist-get entry :status)))
                     (should (= 1 (length requests)))
                     (error "cancel rejected"))))
          (should-error (supertag-ai-cancel "n1")))
        (should (eq entry (gethash "n1" supertag-ai--candidates)))
        (should (eq 'pending (plist-get entry :status)))
        (should (eq batch supertag-ai--batch))
        (should (equal "n1" (plist-get batch :current)))
        (cl-letf (((symbol-function 'superchat-runtime-cancel)
                   (lambda (_run)
                     (should (eq 'pending (plist-get entry :status)))
                     (should (= 1 (length requests))))))
          (supertag-ai-cancel "n1"))
        (should (eq 'cancelled (plist-get entry :status)))
        (should (= 2 (length requests)))
        (should (equal "n2" (plist-get batch :current)))
        (cl-letf (((symbol-function 'superchat-runtime-cancel) #'ignore))
          (supertag-ai-cancel-batch))
        (should-not supertag-ai--batch)
        (should (= 2 (length requests)))))))

(ert-deftest supertag-ai-cancel-refresh-reentry-cannot-notify-new-owner ()
  (supertag-ai-test-with-batch
    (cl-letf (((symbol-function 'supertag-ai--submit)
               (lambda (req)
                 (push req requests)
                 (list :run-id (format "run%d" (length requests)))))
              ((symbol-function 'superchat-runtime-cancel) #'ignore))
      (supertag-ai-extract-tag-properties)
      (let* ((old (car requests)) new-entry new-batch reentered
             (during-refresh
              (lambda (id)
                (when (and (not reentered) (equal id "n1")
                           (eq 'cancelled (plist-get (gethash id supertag-ai--candidates) :status)))
                  (setq reentered t)
                  (supertag-ai--reset-runtime)
                  (supertag-ai-extract-tag-properties)
                  (setq new-entry (gethash "n1" supertag-ai--candidates)
                        new-batch supertag-ai--batch)))))
        ;; Reenter after the actual refresh, exercising the cancel caller's seam.
        (advice-add 'supertag-ai--refresh :after during-refresh)
        (unwind-protect (supertag-ai-cancel "n1")
          (advice-remove 'supertag-ai--refresh during-refresh))
        (should reentered)
        (should (eq new-entry (gethash "n1" supertag-ai--candidates)))
        (should (eq new-batch supertag-ai--batch))
        (should (equal "n1" (plist-get new-batch :current)))
        (should (eq 'pending (plist-get new-entry :status)))
        (should (equal "run2" (plist-get new-entry :run-id)))
        (should (= 2 (length requests)))
        (supertag-ai-test-deliver old "{}")
        (should (eq new-entry (gethash "n1" supertag-ai--candidates)))
        (should (= 2 (length requests)))))))

(defun supertag-ai-test--terminal-refresh-reentry (status)
  "Deliver STATUS through the real refresh/reset seam into a replacement batch."
  (supertag-ai-test-with-batch
    (cl-letf (((symbol-function 'supertag-ai--submit)
               (lambda (req)
                 (push req requests)
                 (list :run-id (format "run%d" (length requests))))))
      (supertag-ai-extract-tag-properties)
      (let* ((old (car requests))
             (old-token (plist-get (gethash "n1" supertag-ai--candidates) :token))
             (disk (supertag-document-test-disk file))
             new-entry new-batch reentered
             (after-refresh
              (lambda (id)
                (when (and (not reentered) (equal id "n1")
                           (memq (plist-get (gethash id supertag-ai--candidates) :status)
                                 '(done failed cancelled)))
                  (setq reentered t)
                  (supertag-ai--reset-runtime)
                  (supertag-ai-extract-tag-properties)
                  (setq new-entry (gethash "n1" supertag-ai--candidates)
                        new-batch supertag-ai--batch)))))
        (advice-add 'supertag-ai--refresh :after after-refresh)
        (unwind-protect
            (if (eq status 'cancelled)
                (cl-letf (((symbol-function 'superchat-runtime-cancel)
                           (lambda (_run)
                             (supertag-ai-test-deliver old "cancelled" 'cancelled))))
                  (supertag-ai-cancel "n1"))
              (supertag-ai-test-deliver old "{}" status))
          (advice-remove 'supertag-ai--refresh after-refresh))
        (should reentered)
        (should (eq new-entry (gethash "n1" supertag-ai--candidates)))
        (should (eq new-batch supertag-ai--batch))
        (should-not (eq old-token (plist-get new-entry :token)))
        (should (equal "run2" (plist-get new-entry :run-id)))
        (should (eq 'pending (plist-get new-entry :status)))
        (should (= 2 (length requests)))
        (should (equal "n1" (plist-get new-batch :current)))
        (should (equal '("n2" "n3") (plist-get new-batch :queue)))
        (should-not (plist-get new-batch :done))
        ;; Duplicate and late old terminal callbacks cannot notify the new owner.
        (dolist (late-status '(completed failed cancelled))
          (supertag-ai-test-deliver old "{}" late-status)
          (should (= 2 (length requests)))
          (should (eq new-entry (gethash "n1" supertag-ai--candidates)))
          (should (eq 'pending (plist-get new-entry :status)))
          (should (equal "n1" (plist-get new-batch :current))))
        (should (equal disk (supertag-document-test-disk file)))))))

(ert-deftest supertag-ai-cancel-delivery-refresh-preserves-replacement-owner ()
  (supertag-ai-test--terminal-refresh-reentry 'cancelled))

(ert-deftest supertag-ai-completed-delivery-refresh-preserves-replacement-owner ()
  (supertag-ai-test--terminal-refresh-reentry 'completed))

(ert-deftest supertag-ai-failed-delivery-refresh-preserves-replacement-owner ()
  (supertag-ai-test--terminal-refresh-reentry 'failed))

(ert-deftest supertag-ai-terminal-deliveries-advance-once-without-reentry ()
  (supertag-ai-test-with-batch
    (cl-letf (((symbol-function 'supertag-ai--submit)
               (lambda (req)
                 (push req requests)
                 (list :run-id (format "run%d" (length requests))))))
      (supertag-ai-extract-tag-properties)
      (let ((batch supertag-ai--batch) (completed (car requests)))
        (supertag-ai-test-deliver completed "{}" 'completed)
        (should (= 2 (length requests)))
        (should (equal '("n1") (plist-get batch :done)))
        (supertag-ai-test-deliver completed "{}" 'completed)
        (should (= 2 (length requests)))
        (should (equal '("n1") (plist-get batch :done)))
        (let ((failed (car requests)))
          (supertag-ai-test-deliver failed "failed" 'failed)
          (should (= 3 (length requests)))
          (should (equal "n3" (plist-get batch :current)))
          (supertag-ai-test-deliver failed "failed" 'failed)
          (should (= 3 (length requests))))
        (let ((cancelled (car requests)))
          (cl-letf (((symbol-function 'superchat-runtime-cancel)
                     (lambda (_run)
                       (supertag-ai-test-deliver cancelled "cancelled" 'cancelled))))
            (supertag-ai-cancel "n3"))
          (should-not supertag-ai--batch)
          (should (= 3 (length requests)))
          (should (equal '("n1") (plist-get batch :done)))
          (supertag-ai-test-deliver cancelled "{}")
          (should-not supertag-ai--batch)
          (should (= 3 (length requests))))))))

(ert-deftest supertag-ai-batch-note-requires-terminal-token-and-batch-slot ()
  (supertag-ai-test-with-batch
    (cl-letf (((symbol-function 'supertag-ai--submit)
               (lambda (req) (push req requests) (list :run-id "run"))))
      (supertag-ai-extract-tag-properties)
      (let* ((request (car requests))
             (batch supertag-ai--batch)
             (token (plist-get (gethash "n1" supertag-ai--candidates) :token))
             checked
             (after-refresh
              (lambda (id)
                (when (and (equal id "n1")
                           (eq 'done (plist-get (gethash id supertag-ai--candidates) :status)))
                  ;; Actual delivery has set terminal status; none of these
                  ;; notifications owns both its request and the original slot.
                  (dolist (args (list (list id (gensym "wrong-token") batch)
                                     (list id token (copy-tree batch))
                                     (list id token nil)
                                     (list "n2" token batch)))
                    (apply #'supertag-ai--batch-note args)
                    (should (= 1 (length requests)))
                    (should (equal "n1" (plist-get batch :current)))
                    (should-not (plist-get batch :done)))
                  (setq checked t)))))
        ;; A matching owner is insufficient while its request is still pending.
        (supertag-ai--batch-note "n1" token batch)
        (should (= 1 (length requests)))
        (should (equal "n1" (plist-get batch :current)))
        (advice-add 'supertag-ai--refresh :after after-refresh)
        (unwind-protect (supertag-ai-test-deliver request "{}")
          (advice-remove 'supertag-ai--refresh after-refresh))
        (should checked)
        (should (= 2 (length requests)))
        (should (equal '("n1") (plist-get batch :done)))
        (should (equal "n2" (plist-get batch :current)))
        ;; The former owner cannot terminate another current slot a second time.
        (supertag-ai--batch-note "n1" token batch)
        (should (= 2 (length requests)))
        (should (equal '("n1") (plist-get batch :done)))
        (should (equal "n2" (plist-get batch :current)))))))
