;;; document-query-contract-test.el --- Q document contracts -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'supertag-query)
(require 'document-fixture)

(ert-deftest supertag-document-query-normalization-and-validation ()
  "Q validates its two inputs without implicitly initializing a library."
  (should (eq :STAGE (supertag-note-query-normalize-property-key "sTaGe")))
  (dolist (bad '(nil 12 "" :STAGE))
    (should-error (supertag-note-query-normalize-property-key bad))
    (should-error (supertag-note-query-read-node bad)))
  (let ((supertag--store nil))
    (should-error (supertag-note-query-read-node "absent"))
    (should-not supertag--store)))

(ert-deftest supertag-document-query-real-projection-empty-missing-and-zero-write ()
  "Read real document values without changing text, identities or Store."
  (supertag-document-test-with-vault
    (with-current-buffer (find-file-noselect plain)
      (goto-char (point-max)) (insert "Unsent draft.\n")
      (let ((live (buffer-string)) (disk (supertag-document-test-disk plain))
            (store (prin1-to-string supertag--store)))
        (let* ((result (supertag-note-query-read-node "document-node"))
               (entries (plist-get result :properties)))
          (should (equal "Property Node" (plist-get (plist-get result :node) :title)))
          (should (equal '("ALPHA" "EMPTY" "ZETA")
                         (mapcar (lambda (e) (plist-get e :name)) entries)))
          (should (equal '("first" "" "last")
                         (mapcar (lambda (e) (plist-get e :value)) entries)))
          (should (= 3 (plist-get result :property-count)))
          (should-not (supertag-note-query-read-node "missing")))
        (should (equal store (prin1-to-string supertag--store)))
        (should (equal live (buffer-string)))
        (should (equal disk (supertag-document-test-disk plain)))
        (should (buffer-modified-p))
        (should-not (org-entry-get nil "ID"))))))

(ert-deftest supertag-document-query-return-isolation ()
  "Mutating returned nested containers and strings cannot mutate Store."
  (supertag-document-test-with-vault
    (let* ((raw (supertag-store-get-entity :nodes "document-node"))
           (nested (make-hash-table :test 'equal)))
      (puthash "key" (vector (list "original")) nested)
      (put-text-property 0 1 'payload (list "kept") (plist-get raw :title))
      (supertag-store-put-entity :nodes "document-node"
                                 (plist-put raw :test-payload nested))
      (let* ((before (prin1-to-string supertag--store))
             (result (supertag-note-query-read-node "document-node"))
             (node (plist-get result :node)))
        (should (equal-including-properties (plist-get raw :title) (plist-get node :title)))
        (setcar (get-text-property 0 'payload (plist-get node :title)) "changed")
        (aset (plist-get node :title) 0 ?X)
        (setcar (aref (gethash "key" (plist-get node :test-payload)) 0) "changed")
        (aset (plist-get (car (plist-get result :properties)) :value) 0 ?X)
        (aset (plist-get result :id) 0 ?X)
        (should (equal before (prin1-to-string supertag--store)))))))

(ert-deftest supertag-document-query-distinguishes-disk-and-live-projections ()
  "Queue input is saved S1; explicit live projection reads unsaved S2."
  (supertag-document-test-with-vault
    (supertag-document-test-save-property file "ALPHA" "saved-S1")
    (with-current-buffer (find-file-noselect file)
      (goto-char (point-min)) (org-entry-put nil "ALPHA" "live-S2"))
    (supertag-document-test-drain)
    (should (equal "saved-S1" (plist-get (car (plist-get
                  (supertag-note-query-read-node "document-node") :properties)) :value)))
    (with-current-buffer (find-file-noselect file)
      (let ((live (buffer-string)))
        (goto-char (point-min)) (supertag-node-sync-at-point)
        (should (equal live (buffer-string)))
        (should (buffer-modified-p))))
    (should (equal "live-S2" (plist-get (car (plist-get
                  (supertag-note-query-read-node "document-node") :properties)) :value)))
    (should (string-match-p "saved-S1" (supertag-document-test-disk file)))))

(provide 'document-query-contract-test)

(ert-deftest supertag-document-query-independent-source-load ()
  "A fresh unified Query retains initialized Store reads without heavy providers."
  (supertag-document-query--a-cold 'after 'leaf))

(ert-deftest supertag-document-query-normalized-stable-order-and-current-library ()
  "Normalize once, keep equal-name order, and read the current Store each time."
  (let ((supertag--store nil))
    (supertag--ensure-store)
    (supertag-store-put-entity :nodes "node"
                              '(:id "node" :properties (:z "last" "alpha" "first" :Alpha "second")))
    (let ((entries (plist-get (supertag-note-query-read-node "node") :properties)))
      (should (equal '(:ALPHA :ALPHA :Z) (mapcar (lambda (e) (plist-get e :key)) entries)))
      (should (equal '("first" "second" "last") (mapcar (lambda (e) (plist-get e :value)) entries))))
    (let ((supertag--store nil))
      (supertag--ensure-store)
      (should-not (supertag-note-query-read-node "node")))))

(ert-deftest supertag-document-query-bool-vector-return-isolation ()
  "Boolean vectors retain their type/content without sharing Store storage."
  (let ((supertag--store nil)
        (flags (bool-vector nil t nil t)))
    (supertag--ensure-store)
    (supertag-store-put-entity
     :nodes "flags" (list :id "flags" :properties (list :FLAGS flags)
                           :payload (vector (list flags))))
    (let* ((result (supertag-note-query-read-node "flags"))
           (property (plist-get (car (plist-get result :properties)) :value))
           (nested (car (aref (plist-get (plist-get result :node) :payload) 0))))
      (dolist (returned (list property nested))
        (should (bool-vector-p returned))
        (should (equal flags returned)))
      (aset property 0 t)
      (aset nested 1 nil)
      (should (equal (bool-vector nil t nil t) flags))
      (should-not (eq property flags))
      (should-not (eq nested flags)))))

(ert-deftest supertag-document-query-long-flat-list-nested-isolation ()
  "Flat list length does not consume recursion depth; nested values detach."
  (let ((supertag--store nil)
        (depth max-lisp-eval-depth)
        (refs (mapcar (lambda (n) (format "node-%d" n))
                      (number-sequence 0 999)))
        (pair (cons "head" "tail")))
    (supertag--ensure-store)
    (supertag-store-put-entity
     :nodes "many" (list :id "many" :ref-to refs
                         :payload (list refs pair)))
    (let* ((result (supertag-note-query-read-node "many"))
           (node (plist-get result :node))
           (returned (plist-get node :ref-to))
           (nested (plist-get node :payload)))
      (should (= 1000 (length returned)))
      (should (equal refs returned))
      (should (equal pair (cadr nested)))
      (aset (nth 999 returned) 0 ?X)
      (setcar (car nested) "changed")
      (aset (cdr (cadr nested)) 0 ?X)
      (should (equal "node-999" (nth 999 refs)))
      (should (equal "node-0" (car refs)))
      (should (equal '("head" . "tail") pair))
      (should (= depth max-lisp-eval-depth)))))

;;; Query-A first-use contracts, each in an independent source process.
(defconst supertag-document-query--a-root
  (file-name-directory (directory-file-name (file-name-directory (or load-file-name buffer-file-name)))))
(defun supertag-document-query--a-cold (stage scenario)
  (let* ((tmp (make-temp-file "supertag-query-a-" t))
         (root supertag-document-query--a-root)
         (program (or (getenv "EMACS_BIN") (expand-file-name invocation-name invocation-directory)))
         (deps (split-string (or (getenv "SUPERTAG_DEPS_LOADPATH") "") path-separator t))
         (process-environment (copy-sequence process-environment))
         (script (expand-file-name "cold.el" tmp))
         (body '
(progn
  (require 'cl-lib) (require 'ert) (require 'org)
  (setq user-emacs-directory (file-name-as-directory qa-tmp)
        supertag-data-directory (expand-file-name "data/" qa-tmp)
        supertag--base-data-directory supertag-data-directory
        supertag-db-file (expand-file-name "store.el" supertag-data-directory)
        supertag-db-backup-directory (expand-file-name "backups/" qa-tmp)
        supertag-sync-state-file (expand-file-name "sync.el" qa-tmp)
        supertag-sync--state-source supertag-sync-state-file
        supertag-sync-directories (list qa-tmp) supertag-sync-directories-mode 'unified
        supertag-sync-exclude-directories nil supertag-sync-file-pattern "\\.org$"
        org-id-locations-file (expand-file-name "ids" qa-tmp)
        org-id-locations nil org-id-files nil org-id-track-globally nil
        after-init-time nil org-mode-hook nil
        supertag-view-style-auto-enable t supertag-org-capture-auto-enable t
        global-supertag-ui-completion-mode nil
        make-backup-files nil auto-save-default nil)
  (defun qa-absent (features)
    (dolist (feature features)
      (should-not (featurep feature))
      (should-not (cl-find-if (lambda (row) (and (stringp (car row))
                             (equal (file-name-base (car row)) (symbol-name feature)))) load-history))))
  (defun qa-provider (symbol file)
    (should-not (autoloadp (symbol-function symbol)))
    (should (equal (symbol-file symbol 'defun) (expand-file-name file qa-root)))
    (princ (format "QUERY-A-PROVIDER %S %s\n" symbol file)))
  (defun qa-seed ()
    (supertag--ensure-store)
    (dolist (row '(("p" :id "p" :title "Alpha" :content "needle" :tags ("parent") :properties (:SCORE 2 :EMPTY "" :GROUP "x"))
                   ("c" :id "c" :title "Beta" :content "needle" :tags ("child") :properties (:SCORE 4 :GROUP "x"))
                   ("m" :id "m" :title "Missing" :content "other" :tags nil :properties nil)))
      (supertag-store-put-entity :nodes (car row)
        (plist-put (copy-tree (cdr row)) :created-at (encode-time 0 0 0 2 1 2020))))
    (supertag-store-put-entity :tags "parent" '(:id "parent" :name "root"))
    (supertag-store-put-entity :tags "child" '(:id "child" :name "child" :extends ("parent")))
    (supertag-store-put-entity :relations "named" '(:id "named" :from "p" :to "c" :type :reference :kind :document-link :origin :org :relation-name "knows"))
    (supertag-store-put-entity :relations "plain" '(:id "plain" :from "p" :to "m" :type :reference :kind :document-link :origin :org)))
  (let* ((file (expand-file-name "input.org" qa-tmp))
         (text "* Saved\n:PROPERTIES:\n:ID: saved\n:ALPHA: first\n:END:\nBody.\n")
         (ordinary (get-buffer-create " *query-a-ordinary*"))
         target hooks)
    (with-temp-file file (insert text))
    (setq target (find-file-noselect file))
    (with-current-buffer target (org-mode))
    (setq hooks (list (copy-tree org-mode-hook)
                     (and (boundp 'org-capture-after-finalize-hook) (copy-tree org-capture-after-finalize-hook))
                     (and (boundp 'enable-theme-functions) (copy-tree enable-theme-functions))))
    (when (memq qa-case '(tag-first node-first))
      (load (expand-file-name (if (eq qa-case 'tag-first) "supertag-tag.el" "supertag-node.el") qa-root) nil nil t))
    (load (expand-file-name
           (if (eq qa-stage 'after) "supertag-query.el"
             (if (eq qa-case 'leaf) "supertag-services-note-query.el" "supertag-services-query.el")) qa-root) nil nil t)
    (princ (format "QUERY-A-ENTRY stage=%S case=%S\n" qa-stage qa-case))
    (when (or (eq qa-case 'owner) (eq qa-stage 'after))
      (dolist (symbol qa-symbols) (qa-provider symbol "supertag-query.el"))
      (dolist (old '("supertag-services-query.el" "supertag-services-note-query.el"))
        (should-not (file-exists-p (expand-file-name old qa-root)))))
    (cond
     ((or (eq qa-case 'leaf) (and (eq qa-stage 'after) (not (memq qa-case '(tag-first node-first)))))
      (qa-absent '(supertag-core-scan supertag-node supertag-tag supertag-ops-node
                   supertag-services-sync supertag-service-org supertag-services-ui
                   supertag-ui-commands supertag-services-formula supertag-automation))
      (when (eq qa-stage 'after) (qa-absent '(supertag-services-query supertag-services-note-query)))
      (should (equal hooks (list org-mode-hook
                               (and (boundp 'org-capture-after-finalize-hook) org-capture-after-finalize-hook)
                               (and (boundp 'enable-theme-functions) enable-theme-functions))))
      (dolist (b (list target ordinary))
        (with-current-buffer b
          (should-not (bound-and-true-p supertag-view-style-mode))
          (should-not (bound-and-true-p supertag-ui-completion-mode))))
      (should-not supertag--store))
     ((eq qa-stage 'before)
      (should (featurep 'supertag-tag)) (should (featurep 'supertag-node))
      (should (featurep 'supertag-services-formula))
      (princ "QUERY-A-OLD-HEAVY Tag/Node/Formula loaded\n")))
    (should-not global-supertag-ui-completion-mode)
    (should-not (file-exists-p supertag-db-file))
    (should-error (supertag-note-query-read-node "absent"))
    (qa-seed)
    (let ((facts (prin1-to-string supertag--store)))
      (pcase qa-case
        ((or 'leaf 'heavy 'owner)
         (should-not (supertag-note-query-read-node "missing"))
         (let* ((result (supertag-note-query-read-node "p"))
                (entries (plist-get result :properties)))
           (should (equal '("EMPTY" "GROUP" "SCORE") (mapcar (lambda (x) (plist-get x :name)) entries)))
           (should (equal "" (plist-get (car entries) :value)))
           (aset (plist-get (plist-get result :node) :title) 0 ?X))
         (should-error (supertag-note-query-normalize-property-key :SCORE)))
        ('node
         (should (eq (supertag-store-get-entity :nodes "p") (supertag-query-node "p")))
         (should (= 2 (supertag-query-property-value "p" "score")))
         (qa-provider 'supertag-node-get "supertag-node.el"))
        ('tag
         (should (equal '((:id "parent" :name "root" :display "root")
                          (:id "child" :name "child" :display "root › child"))
                        (supertag-query-tag-descriptors)))
         (should (= 2 (length (supertag-query-tags))))
         (qa-provider 'supertag--ensure-plist "supertag-tag.el")
         (qa-provider 'supertag-tag-display-name "supertag-tag.el"))
        ('scan
         (should (equal '("p") (supertag-query-node-ids-by-tag "parent")))
         (should (equal '("c" "p") (sort (copy-sequence (supertag-query-node-ids-by-tag "parent" t)) #'string<)))
         (should (equal '("c" "p") (sort (supertag-query-node-ids '(term "needle")) #'string<)))
         (should (equal '("c" "m" "p") (sort (supertag-query-node-ids '(between "2020-01-01" "2020-01-03")) #'string<)))
         (dolist (s '(supertag-index-get-nodes-by-tag supertag-index-get-nodes-by-word supertag-index-get-nodes-by-date-range)) (qa-provider s (if (eq qa-stage 'before) "supertag-core-scan.el" "supertag-query.el"))))
        ('relation
         (should (equal '("p") (supertag-query-node-ids '(has-link "knows"))))
         (should (equal '("c") (supertag-query-node-ids '(has-reverse-link knows))))
         (should (equal '("named") (mapcar (lambda (x) (plist-get x :id)) (supertag-query-named-links-from "p" "knows"))))
         (should (equal '("named") (mapcar (lambda (x) (plist-get x :id)) (supertag-query-named-links-to "c" "knows"))))
         (should (equal '("plain") (mapcar (lambda (x) (plist-get x :id)) (supertag-query-ordinary-references-from "p"))))
         (should-error (supertag-query-node-ids '(has-link "")))
         (dolist (s '(supertag-relation-named-document-link-p supertag-relation-find-by-from supertag-relation-find-by-to)) (qa-provider s (if (or (eq qa-stage 'before) (equal (getenv "SUPERTAG_LC_STAGE") "before")) "supertag-ops-relation.el" "supertag-link.el"))))
        ('formula
         (should (= 0 (supertag-query-evaluate '(sum "SCORE"))))
         (should (= 6 (supertag-query-evaluate '(and (sum "SCORE")))))
         (should (= 3 (supertag-query-evaluate '(and (avg "SCORE")))))
         (qa-provider 'supertag-rollup-apply
                      (if (eq qa-stage 'before)
                          "supertag-services-formula.el"
                        "supertag-query.el"))
         (should-not (featurep 'supertag-automation))
         (should (equal '("p" "c" "m") (supertag-query-node-ids '(sort-by "SCORE" asc))))
         (should (equal '(("__ungrouped__" . 0) ("x" . 6)) (supertag-query-evaluate '(and (group-by "GROUP") (sum "SCORE")))))
         (should (= 2.5 (supertag-query--numeric " 2.5 ")))
         (should-not (supertag-query--numeric "two"))
         (should-error (supertag-query-node-ids '(sum "SCORE")))
         (should (= 0 (supertag-query-evaluate '(and (property "GROUP" "none") (sum "SCORE"))))))
        ((or 'tag-first 'node-first)
         (should (equal '("p") (supertag-query-node-ids-by-tag "parent")))
         (should (= 2 (supertag-query-property-value "p" "SCORE")))
         (load (expand-file-name (if (eq qa-stage 'after) "supertag-query.el" "supertag-services-query.el") qa-root) nil nil t)
         (should (equal '("p") (supertag-query-node-ids-by-tag "parent")))
         (should supertag-view-style-auto-enable) (should supertag-org-capture-auto-enable))
        ('sync
         (load (expand-file-name "supertag-services-sync.el" qa-root) nil nil t)
         (when (eq qa-stage 'after) (qa-absent '(supertag-core-scan)))
         (princ (format "QUERY-A-SYNC-BEFORE scan=%S\n" (featurep 'supertag-core-scan)))
         (let ((counters (list :nodes-created 0 :nodes-updated 0 :nodes-deleted 0)))
           (supertag-sync--process-single-file file counters))
         (should (equal "Saved" (plist-get (supertag-store-get-entity :nodes "saved") :title)))
         (should (equal '("saved") (mapcar #'car (supertag-find-nodes-by-file file))))
         (qa-provider 'supertag-find-nodes-by-file
                      (if (eq qa-stage 'before) "supertag-core-scan.el" "supertag-query.el"))))
      (unless (eq qa-case 'sync) (should (equal facts (prin1-to-string supertag--store)))))
    (with-current-buffer target (should (equal text (buffer-string))) (should-not (buffer-modified-p)))
    (should (equal text (with-temp-buffer (insert-file-contents file) (buffer-string))))
    (princ "QUERY-A-PASS\n")))
))
    (unwind-protect
        (progn
          (with-temp-file script
            (insert ";;; -*- lexical-binding: t; -*-\n")
            (prin1 `(setq qa-root ,root qa-tmp ,tmp qa-stage ',stage qa-case ',scenario
                          qa-symbols '(supertag-note-query-normalize-property-key supertag-note-query-read-node supertag-query-link--relation-name supertag-query-link--parse-binary supertag-query-link--parse-unary supertag-query-link--unique supertag-query-link--execute-forward supertag-query-link--execute-reverse supertag-query-link--execute-has-out supertag-query-link--execute-has-in supertag-query-normalize-property-key supertag-query-node supertag-query-tag-descriptors supertag-query-tags supertag-query-node-ids-by-tag supertag-query-automations supertag-query-tag-occurrences supertag-query-relations supertag-query-property-value supertag-query-relations-from supertag-query-relations-to supertag-query-named-links-from supertag-query-named-links-to supertag-query-ordinary-references-from supertag-query-ordinary-references-to supertag-query-relations-among supertag-query-node-tags supertag-query-node-properties supertag-query-node-detail supertag-query supertag-query-nodes supertag-query-node-ids supertag-query-evaluate supertag-query-sexp supertag-query-properties supertag-query-validate supertag-query-date-valid-p supertag-query-expand supertag-query--date-arg supertag-query--modifier-ast-p supertag-query--parse-sexp supertag-query--execute-ast supertag-query--get-all-node-ids supertag-query--ast-modifiers supertag-query--numeric supertag-query--value< supertag-query--sort-value supertag-query--sort-node-ids supertag-query--aggregate-values supertag-query--group-values supertag-query--apply-modifiers supertag-query-modifiers supertag-query--resolve-date-string supertag-query--get-properties-from-ast)) (current-buffer))
            (insert "\n")
            (let ((print-length nil) (print-level nil))
              (prin1 `(condition-case err
                          (unwind-protect ,body
                            (setq emacs-startup-hook nil kill-emacs-hook nil org-mode-hook nil
                                  org-capture-after-finalize-hook nil enable-theme-functions nil)
                            (when (fboundp 'org-id-find)
                              (advice-remove 'org-id-find 'supertag-service-org--org-id-find-advice))
                            (mapc #'cancel-timer (append timer-list timer-idle-list))
                            (dolist (b (buffer-list))
                              (when (or (member (buffer-name b) '(" *query-a-ordinary*"))
                                        (and (buffer-file-name b) (file-in-directory-p (buffer-file-name b) qa-tmp)))
                                (with-current-buffer b (set-buffer-modified-p nil) (kill-buffer b)))))
                        (error (princ (format "QUERY-A-ERROR %S\n" err)) (kill-emacs 1))) (current-buffer))))
          ;; Pin the child cwd before HOME is repointed.
          (setq default-directory (file-truename default-directory))
          (setenv "HOME" tmp) (setenv "CFFIXED_USER_HOME" tmp)
          (setenv "EMACSLOADPATH" (concat (mapconcat #'identity deps path-separator) path-separator))
          (with-temp-buffer
            (let ((status (apply #'call-process program nil t nil
                                 (append '("-Q" "--batch")
                                         (apply #'append (mapcar (lambda (dir) (list "-L" dir)) deps))
                                         (list "-L" root "-l" script)))))
              (unless (and (equal status 0) (string-match-p "QUERY-A-ENTRY" (buffer-string))
                           (string-match-p "QUERY-A-PASS" (buffer-string)))
                (ert-fail (format "QUERY-A %S/%S exit=%S\n%s" stage scenario status (buffer-string))))
              (dolist (line (split-string (buffer-string) "\n" t))
                (when (string-prefix-p "QUERY-A-" line) (princ (concat line "\n")))))))
      (delete-directory tmp t))))

(ert-deftest supertag-document-query-a-leaf ()
  (supertag-document-query--a-cold 'after 'leaf))

(ert-deftest supertag-document-query-a-heavy ()
  (supertag-document-query--a-cold 'after 'heavy))

(ert-deftest supertag-document-query-a-node ()
  (supertag-document-query--a-cold 'after 'node))

(ert-deftest supertag-document-query-a-tag ()
  (supertag-document-query--a-cold 'after 'tag))

(ert-deftest supertag-document-query-a-scan ()
  (supertag-document-query--a-cold 'after 'scan))

(ert-deftest supertag-document-query-a-relation ()
  (supertag-document-query--a-cold 'after 'relation))

(ert-deftest supertag-document-query-a-formula ()
  (supertag-document-query--a-cold 'after 'formula))

(ert-deftest supertag-document-query-a-sync ()
  (supertag-document-query--a-cold 'after 'sync))

(ert-deftest supertag-document-query-a-tag-first ()
  (supertag-document-query--a-cold 'after 'tag-first))

(ert-deftest supertag-document-query-a-node-first ()
  (supertag-document-query--a-cold 'after 'node-first))

(ert-deftest supertag-document-query-a-entry-owner ()
  (supertag-document-query--a-cold 'after 'owner))

;;; QUERY-B: independent fresh-process computation, not QA historical before.
(defun supertag-document-query--b-cold (scenario)
  (let* ((root supertag-document-query--a-root)
         (stage (if (equal (getenv "SUPERTAG_QB_STAGE") "before") 'before 'after))
         (tmp (make-temp-file "supertag-query-b-" t))
         (script (expand-file-name "cold.el" tmp))
         (deps (split-string (or (getenv "SUPERTAG_DEPS_LOADPATH") "") path-separator t))
         (process-environment (copy-sequence process-environment))
         (body
          '(progn
             (require 'ert) (require 'cl-lib) (require 'org)
             (setq user-emacs-directory (file-name-as-directory qb-tmp)
                   supertag-data-directory (expand-file-name "data/" qb-tmp)
                   org-id-locations-file (expand-file-name "ids" qb-tmp)
                   org-id-track-globally nil after-init-time nil
                   org-mode-hook nil make-backup-files nil auto-save-default nil
                   supertag-view-style-auto-enable t supertag-org-capture-auto-enable t
                   global-supertag-ui-completion-mode nil)
             (let* ((file (expand-file-name "input.org" qb-tmp))
                    (text "* Saved\n:PROPERTIES:\n:ID: qb\n:END:\nBody.\n")
                    (ordinary (get-buffer-create " *qb-ordinary*")) target hooks modes)
               (with-temp-file file (insert text))
               (setq target (find-file-noselect file))
               (with-current-buffer ordinary (insert "Ordinary draft"))
               (setq hooks (mapcar (lambda (s) (and (boundp s) (copy-tree (symbol-value s))))
                                   '(org-mode-hook org-capture-after-finalize-hook enable-theme-functions)))
               (setq modes (mapcar (lambda (b) (with-current-buffer b
                                                (list major-mode (buffer-modified-p))))
                                   (list target ordinary)))
               (load (expand-file-name "supertag-query.el" qb-root) nil nil t)
               (princ "QUERY-B-ENTRY\n")
               (should-not supertag--store)
               (when (eq qb-case 'owner)
                 (dolist (s qb-symbols)
                   (should (equal (symbol-file s 'defun)
                                  (expand-file-name "supertag-query.el" qb-root))))
                 (should-not (file-exists-p (expand-file-name "supertag-services-formula.el" qb-root))))
               ;; Real non-count dispatch resolves the old ordinary provider on before.
               (should (= 6 (supertag-query--aggregate-values
                             '((:id "a" :title 2) (:id "b" :title 4)) 'sum "title")))
               (supertag--ensure-store)
               (supertag-store-put-entity :nodes "qb" '(:id "qb" :properties (:X "2")))
               (let* ((entity '(:id "qb" :properties (:X "9" :BAD " 2" :TEXT "word")))
                      (original (copy-tree entity))
                      (snapshot (prin1-to-string supertag--store)))
                 (pcase qb-case
                   ('sources
                    (should (= 3 (supertag-formula-eval-string "x + 1" "qb")))
                    (should (= 10 (supertag-formula-evaluate "x + 1" entity)))
                    (let (names)
                      (should (= 6 (supertag-formula-evaluate "x + 1" entity
                                      (lambda (name) (push name names) "5"))))
                      (should (equal names '("x"))))
                    (dolist (input '("missing + 1" "bad + 1" "text * 2"))
                      (should-not (supertag-formula-evaluate input entity)))
                    (should (= -9 (supertag-formula-evaluate "-x" entity)))
                    (should (equal 4.5 (supertag-formula-evaluate "x / 2" entity)))
                    (should (= 0 (supertag-formula-evaluate "x / 0" entity)))
                    (should (= 4.5 (supertag-formula-evaluate "n + 1" nil (lambda (_) "3.5"))))
                    (princ "QUERY-B-DONE sources\n"))
                   ('grammar
                    (should (equal '(2 + 3 * 4) (supertag-formula-tokenize "2 + 3 * 4")))
                    (should (= 14 (supertag-formula-eval
                                   (supertag-formula-parse (supertag-formula-tokenize "2 + 3 * 4")) "qb")))
                    (should (= 10 (supertag-formula-evaluate "(+ {{ :x }} 1)" entity)))
                    (should (= 10 (supertag-formula-evaluate "{{x}} + 1" entity)))
                    (should (equal "x + x" (supertag-formula--translate-placeholders "{{:x}} + {{ x }}")))
                    (should-error (supertag-formula-eval-string "{{x}} + 1" "qb"))
                    (dolist (input '("(+ x 1 2)" "(foo x)" "x @ 2" "x +" ""))
                      (should-error (supertag-formula-evaluate input entity)))
                    (should-error (supertag-formula-evaluate nil entity))
                    (princ "QUERY-B-DONE grammar\n"))
                   ('rollup
                    (dolist (row '((count :count 2) (sum :sum 5) (avg :avg 2)
                                   (average :average 2) (min :min 2) (max :max 3)
                                   (first :first 2) (last :last 3)))
                      (dolist (op (list (car row) (cadr row)))
                        (should (= (nth 2 row) (supertag-rollup-apply op '(2 3))))))
                    (dolist (op '(count :count sum :sum avg :avg average :average))
                      (should (= 0 (supertag-rollup-apply op nil))))
                    (dolist (op '(min :min max :max first :first last :last))
                      (should-not (supertag-rollup-apply op nil)))
                    (should (= 2 (supertag-rollup-apply 'unique-count '(2 2 3))))
                    (should (equal "a, b" (supertag-rollup-apply 'concat '("a" "b"))))
                    (should (equal "" (supertag-rollup-apply 'concat nil)))
                    (dolist (op '(:unique-count :concat :unknown))
                      (should (equal (format "Unknown rollup function: %S" op)
                                     (supertag-rollup-apply op '(2 3)))))
                    (let ((values (list 2 3)) seen)
                      (should (= 6 (supertag-rollup-apply
                                    (lambda (xs) (setq seen xs) (apply #'* xs)) values)))
                      (should (eq seen values)))
                    (should-error (supertag-rollup-apply (lambda (_) (error "reducer")) '(1)))
                    (princ "QUERY-B-DONE rollup\n"))
                   ('owner (princ "QUERY-B-DONE owner\n"))
                   (_ (error "Unknown QB case %S" qb-case)))
                 (should (equal original entity))
                 (should (equal snapshot (prin1-to-string supertag--store)))
                 (load (expand-file-name "supertag-query.el" qb-root) nil nil t)
                 (should (equal snapshot (prin1-to-string supertag--store))))
               (dolist (s qb-symbols)
                 (should-not (autoloadp (symbol-function s)))
                 (should (equal (symbol-file s 'defun)
                                (expand-file-name (if (eq qb-stage 'before)
                                                     "supertag-services-formula.el" "supertag-query.el") qb-root))))
               (dolist (f '(supertag-node supertag-tag supertag-services-ui supertag-automation
                             supertag-services-sync supertag-service-org))
                 (should-not (featurep f))
                 (should-not (cl-find-if (lambda (row) (and (stringp (car row))
                                                           (equal (file-name-base (car row)) (symbol-name f)))) load-history)))
               (when (eq qb-stage 'after) (should-not (featurep 'supertag-services-formula)))
               (should (equal hooks (mapcar (lambda (s) (and (boundp s) (symbol-value s)))
                                           '(org-mode-hook org-capture-after-finalize-hook enable-theme-functions))))
               (should (equal modes (mapcar (lambda (b) (with-current-buffer b
                                                        (list major-mode (buffer-modified-p)))) (list target ordinary))))
               (should supertag-view-style-auto-enable) (should supertag-org-capture-auto-enable)
               (should-not global-supertag-ui-completion-mode)
               (with-current-buffer target (should (equal text (buffer-string))))
               (with-current-buffer ordinary (should (equal "Ordinary draft" (buffer-string))))
               (should (equal text (with-temp-buffer (insert-file-contents file) (buffer-string))))
               (princ (format "QUERY-B-PASS %S %S\n" qb-stage qb-case))))))
    (unwind-protect
        (progn
          (with-temp-file script
            (insert ";;; -*- lexical-binding: t; -*-\n")
            (prin1 `(setq qb-root ,root qb-tmp ,tmp qb-stage ',stage qb-case ',scenario
                          qb-symbols '(supertag-formula-tokenize supertag-formula-parse supertag-formula-eval
                                       supertag-formula-parse-string supertag-formula-eval-string
                                       supertag-formula--translate-placeholders supertag-formula--prefix-to-infix
                                       supertag-formula--canonicalize supertag-rollup-apply supertag-formula-evaluate)) (current-buffer))
            (insert "\n")
            (let ((print-length nil) (print-level nil))
              (prin1 `(condition-case err
                          (unwind-protect ,body
                            (setq kill-emacs-hook nil emacs-startup-hook nil)
                            (mapc #'cancel-timer (append timer-list timer-idle-list))
                            (dolist (b (buffer-list))
                              (when (or (equal (buffer-name b) " *qb-ordinary*")
                                        (and (buffer-file-name b) (file-in-directory-p (buffer-file-name b) qb-tmp)))
                                (with-current-buffer b (set-buffer-modified-p nil) (kill-buffer b)))))
                        (error (princ (format "QUERY-B-ERROR %S\n" err)) (kill-emacs 1))) (current-buffer))))
          ;; Pin the child cwd before HOME is repointed.
          (setq default-directory (file-truename default-directory))
          (setenv "HOME" tmp) (setenv "CFFIXED_USER_HOME" tmp)
          (setenv "EMACSLOADPATH" (concat (mapconcat #'identity deps path-separator) path-separator))
          (with-temp-buffer
            (let ((status (apply #'call-process (or (getenv "EMACS_BIN") (expand-file-name invocation-name invocation-directory))
                                 nil t nil (append '("-Q" "--batch")
                                                   (apply #'append (mapcar (lambda (d) (list "-L" d)) deps))
                                                   (list "-L" root "-l" script)))))
              (when-let* ((out (getenv "SUPERTAG_QB_EVIDENCE")))
                (write-region (point-min) (point-max) (expand-file-name (format "%s-%s.log" stage scenario) out) nil 'silent)
                (copy-file script (expand-file-name (format "%s-%s.el" stage scenario) out) t))
              (princ (buffer-string))
              (should (equal status 0))
              (should (string-match-p "QUERY-B-ENTRY" (buffer-string)))
              (should (string-match-p (format "QUERY-B-DONE %s" scenario) (buffer-string)))
              (should (string-match-p (format "QUERY-B-PASS %s %s" stage scenario) (buffer-string))))))
      (delete-directory tmp t))))

(ert-deftest supertag-document-query-b-sources () (supertag-document-query--b-cold 'sources))
(ert-deftest supertag-document-query-b-grammar () (supertag-document-query--b-cold 'grammar))
(ert-deftest supertag-document-query-b-rollup () (supertag-document-query--b-cold 'rollup))
(ert-deftest supertag-document-query-b-owner () (supertag-document-query--b-cold 'owner))

;;; QUERY-C independent stages and source-only adapters.
(defun supertag-document-query--c-cold (scenario)
  (let* ((root supertag-document-query--a-root)
         (stage (if (equal (getenv "SUPERTAG_QC_STAGE") "before") 'before 'after))
         (tmp (make-temp-file "supertag-query-c-" t))
         (script (expand-file-name "cold.el" tmp))
         (deps (split-string (or (getenv "SUPERTAG_DEPS_LOADPATH") "") path-separator t))
         (process-environment (copy-sequence process-environment))
         (body '
(progn
 (require 'ert) (require 'cl-lib) (require 'org)
 (setq user-emacs-directory (file-name-as-directory qc-tmp)
       supertag-data-directory (expand-file-name "data/" qc-tmp)
       supertag--base-data-directory supertag-data-directory
       supertag-db-file (expand-file-name "store.el" qc-tmp)
       supertag-db-backup-directory (expand-file-name "backups/" qc-tmp)
       supertag-sync-state-file (expand-file-name "sync.el" qc-tmp)
       supertag-sync--state-source supertag-sync-state-file
       supertag-sync-directories (list qc-tmp) supertag-sync-directories-mode 'unified
       supertag-sync-exclude-directories nil
       org-id-locations-file (expand-file-name "ids" qc-tmp)
       org-id-locations nil org-id-files nil org-id-track-globally nil
       after-init-time nil org-mode-hook nil
       supertag-view-style-auto-enable t supertag-org-capture-auto-enable t
       global-supertag-ui-completion-mode nil make-backup-files nil auto-save-default nil)
 (defun qc-absent (names)
   (dolist (f names)
     (should-not (featurep f))
     (should-not (cl-find-if (lambda (row) (and (stringp (car row))
                                               (equal (file-name-base (car row)) (symbol-name f)))) load-history))))
 (defun qc-owner (s)
   (should-not (autoloadp (symbol-function s)))
   (should (equal (symbol-file s 'defun)
                  (expand-file-name (if (eq qc-stage 'before) "supertag-core-scan.el" "supertag-query.el") qc-root))))
 (defvar qc-events nil)
 (defvar qc-advice nil)
 (defun qc-watch (file)
   (when (and (stringp file) (string-prefix-p qc-root file))
     (push (list (file-name-base file) (featurep 'supertag-query)
                 (featurep 'supertag-node) (featurep 'supertag-tag)) qc-events)
     (dolist (s '(supertag-tag-get supertag-tag-resolve-occurrence supertag-find-tag-descendants
                   supertag-index-find-node-ids-by-tags supertag-find-nodes-by-file supertag-find-nodes-by-tag))
       (when (and (fboundp s) (not (autoloadp (symbol-function s))) (not (assq s qc-advice)))
         (let* ((symbol s) (observer (lambda (&rest _) (push (list 'call symbol) qc-events))))
           (advice-add s :before observer) (push (cons s observer) qc-advice))))))
 (add-hook 'after-load-functions #'qc-watch)
 (let* ((file (expand-file-name "input.org" qc-tmp))
        (text "* Saved\n:PROPERTIES:\n:ID: qc-saved\n:END:\nBody.\n")
        (ordinary (get-buffer-create " *qc-ordinary*")) target facts hooks)
   (with-temp-file file (insert text))
   (setq target (find-file-noselect file))
   (with-current-buffer ordinary (insert "Ordinary draft"))
   (setq hooks (copy-tree org-mode-hook))
   (load (expand-file-name (pcase qc-case ('main "supertag.el") ('node "supertag-node.el")
                                 ('sync "supertag-services-sync.el") ('input "supertag-tag.el")
                                 (_ "supertag-query.el")) qc-root) nil nil t)
   (princ (format "QUERY-C-ENTRY %S query=%S node=%S tag=%S\n" qc-case
                  (featurep 'supertag-query) (featurep 'supertag-node) (featurep 'supertag-tag)))
   (when (memq qc-case '(local tags owner))
     (should-not supertag--store)
     (qc-absent '(supertag-node supertag-tag supertag-services-ui supertag-services-sync supertag-service-org))
     (should-not (file-exists-p supertag-db-file)))
   (when (eq qc-case 'owner)
     (dolist (s qc-symbols)
       (should (equal (symbol-file s 'defun) (expand-file-name "supertag-query.el" qc-root))))
     (should-not (file-exists-p (expand-file-name "supertag-core-scan.el" qc-root))))
   (pcase qc-case
     ('local
      ;; True old provider call loads scan on before, not a manual hot preload.
      (should-not (supertag-index-get-nodes-by-word "no-store"))
      (supertag--ensure-store)
      (dolist (row '(("a" :id "a" :title "Alpha.[X]" :file "/a/x" :level 0 :created-at (1 0) :modified-at (2 0))
                     ("b" :id "b" :content "alpha" :file "/a/./x" :level 0 :created-at (2 0) :modified-at (3 0))
                     ("c" :id "c" :title "" :file "/a/x" :level 0 :created-at (3 0))
                     ("d" :id "d" :file 42 :level 0)
                     ("e" :id "e" :file nil :level 0)))
        (supertag-store-put-entity :nodes (car row) (cdr row)))
      (setq facts (prin1-to-string supertag--store))
      (should (equal '("a" "b") (supertag-index-get-nodes-by-word "ALPHA")))
      (should (equal '("a") (supertag-index-get-nodes-by-word ".[x]")))
      (should (equal '("a" "b" "c") (supertag-index-get-nodes-by-word "")))
      (should-error (supertag-index-get-nodes-by-word 42))
      (should (equal '("b") (supertag-index-get-nodes-by-date-range '(1 0) '(3 0))))
      (should (equal '("a" "b" "c") (supertag-index-get-nodes-by-date-range nil nil)))
      (should (equal '("a") (supertag-index-get-nodes-by-date-range nil '(2 0))))
      (should (equal '("c") (supertag-index-get-nodes-by-date-range '(2 0) nil)))
      (should (equal '("a") (supertag-index-get-nodes-by-date-range '(1 0) '(3 0) :modified-at)))
      (should-not (supertag-index-get-nodes-by-date-range nil nil :absent))
      (should (equal '("a" "c") (mapcar #'car (supertag-find-nodes-by-file "/a/x"))))
      (should (equal '("b") (mapcar #'car (supertag-find-nodes-by-file "/a/./x"))))
      (should-not (supertag-find-nodes-by-file nil))
      (should-not (supertag-find-nodes-by-file 42))
      (should (equal "a" (car (supertag-find-file-node "/a/x"))))
      (should (equal "e" (car (supertag-find-file-node nil))))
      (should (equal "d" (car (supertag-find-file-node 42))))
      (should (eq (cdr (car (supertag-find-nodes-by-file "/a/x"))) (supertag-store-get-entity :nodes "a")))
      (should (eq (cdr (supertag-find-file-node "/a/x")) (supertag-store-get-entity :nodes "a")))
      (dolist (s '(supertag-index-get-nodes-by-word supertag-index-get-nodes-by-date-range supertag-find-nodes-by-file supertag-find-file-node)) (qc-owner s))
      (if (eq qc-stage 'after)
          (progn (qc-absent '(supertag-core-scan supertag-node supertag-tag supertag-services-ui supertag-services-sync supertag-service-org))
                 (should (equal hooks org-mode-hook)))
        (should (featurep 'supertag-core-scan)) (should (featurep 'supertag-node)) (should (featurep 'supertag-tag)))
      (should (equal facts (prin1-to-string supertag--store)))
      (princ "QUERY-C-DONE local\n"))
     ('tags
      (supertag--ensure-store)
      (dolist (row '(("p" :id "p" :name "root" :aliases ("alias"))
                     ("c" :id "c" :name "root/child" :extends ("p"))
                     ("v" :id "v" :name "virtual/child")))
        (supertag-store-put-entity :tags (car row) (cdr row)))
      (dolist (row '(("n1" :id "n1" :tags ("p" "p")) ("n2" :id "n2" :tags ("c"))
                     ("n3" :id "n3" :tag-occurrences ("unresolved" "unresolved"))))
        (supertag-store-put-entity :nodes (car row) (cdr row)))
      (setq facts (prin1-to-string supertag--store))
      (should (equal '("n1") (supertag-index-get-nodes-by-tag "p")))
      (should (equal '("n1" "n2") (supertag-index-get-nodes-by-tag "alias" t)))
      (should (equal '("n3") (supertag-index-get-nodes-by-tag "unresolved")))
      (should-not (supertag-index-get-nodes-by-tag "virtual" t))
      (should (equal '("n1" "n2") (mapcar #'car (supertag-find-nodes-by-tag "p" t))))
      (should (eq (cdar (supertag-find-nodes-by-tag "p")) (supertag-store-get-entity :nodes "n1")))
      (should (equal facts (prin1-to-string supertag--store)))
      (dolist (s '(supertag-tag-get supertag-tag-resolve-occurrence supertag-find-tag-descendants supertag-index-find-node-ids-by-tags))
        (should (member (list 'call s) qc-events)))
      (let ((token supertag--index-nodes-source-token))
        (supertag-store-put-entity :nodes "n2" '(:id "n2" :tags ("p")))
        (should-not (supertag-index-source-current-p token '(:nodes)))
        (setq facts (prin1-to-string supertag--store))
        (should (equal '("n1" "n2") (supertag-index-get-nodes-by-tag "p")))
        (should-not (supertag-index-get-nodes-by-tag "c"))
        (should (supertag-index-source-current-p supertag--index-nodes-source-token '(:nodes)))
        (should (equal facts (prin1-to-string supertag--store))))
      (qc-owner 'supertag-index-get-nodes-by-tag) (qc-owner 'supertag-find-nodes-by-tag)
      (princ "QUERY-C-DONE tags\n"))
     ('node
      (qc-absent '(supertag-query supertag-core-scan supertag-tag supertag-services-sync))
      (supertag--ensure-store)
      (supertag-node-create (list :id "existing-file" :level 0 :file file))
      (setq facts (prin1-to-string supertag--store))
      (with-current-buffer target (should (equal "existing-file" (supertag-ui--get-file-node-at-point))))
      (qc-owner 'supertag-find-file-node)
      (when (eq qc-stage 'after) (qc-absent '(supertag-core-scan supertag-tag)))
      (qc-absent '(supertag-services-sync supertag-ui-commands))
      (should (equal facts (prin1-to-string supertag--store)))
      (princ "QUERY-C-DONE node\n"))
     ('sync
      (princ (format "QUERY-C-SYNC-PROVIDER before-call=%S owner=%S\n"
                     (symbol-function 'supertag-find-nodes-by-file) (symbol-file 'supertag-find-nodes-by-file 'defun)))
      (supertag--ensure-store)
      (let ((counters (list :nodes-created 0 :nodes-updated 0 :nodes-deleted 0)))
        (supertag-sync--process-single-file file counters))
      (should (equal "Saved" (plist-get (supertag-store-get-entity :nodes "qc-saved") :title)))
      (should (member '(call supertag-find-nodes-by-file) qc-events))
      (should (equal '("qc-saved") (mapcar #'car (supertag-find-nodes-by-file file))))
      (qc-owner 'supertag-find-nodes-by-file)
      (princ "QUERY-C-DONE sync\n"))
     ('input
      (qc-absent '(supertag-query))
      (supertag--ensure-store)
      (supertag-store-put-entity :tags "p" '(:id "p" :name "root"))
      (supertag-store-put-entity :nodes "n1" '(:id "n1" :tags ("p")))
      (setq facts (prin1-to-string supertag--store))
      (cl-letf (((symbol-function 'completing-read) (lambda (_prompt choices &rest _) (should (member "root" choices)) "root")))
        (should (equal "p" (supertag-ui-read-tag "Tag: "))))
      (should (featurep 'supertag-query))
      (should-not (member '(call supertag-find-nodes-by-tag) qc-events))
      (should (equal '("n1") (mapcar #'car (supertag-find-nodes-by-tag "p"))))
      (should (member '(call supertag-find-nodes-by-tag) qc-events))
      (qc-owner 'supertag-find-nodes-by-tag)
      (should (equal facts (prin1-to-string supertag--store)))
      (princ "QUERY-C-DONE input\n"))
     ('main
      (should (featurep 'supertag)) (should-not after-init-time)
      (should (memq #'supertag-init emacs-startup-hook))
      (should-not (file-exists-p supertag-db-file))
      (let* ((events (reverse qc-events)) (point (assoc (if (eq qc-stage 'before) "supertag-core-scan" "supertag-query") events)))
        (should point)
        (if (eq qc-stage 'before)
            (progn (should (nth 2 point)) (should (nth 3 point)))
          (should-not (nth 2 point)) (should-not (nth 3 point))
          (should (< (cl-position point events :test #'equal)
                     (cl-position (assoc (if (equal (getenv "SUPERTAG_LB_STAGE") "before") "supertag-ops-node" "supertag-node") events) events :test #'equal)))))
      (princ "QUERY-C-DONE main\n"))
     ('owner (princ "QUERY-C-DONE owner\n"))
     (_ (error "Unknown QC case")))
   (princ (format "QUERY-C-EVENTS %S\n" (reverse qc-events)))
   (with-current-buffer target (should (equal text (buffer-string))) (should-not (buffer-modified-p)))
   (with-current-buffer ordinary (should (equal "Ordinary draft" (buffer-string))))
   (should (equal text (with-temp-buffer (insert-file-contents file) (buffer-string))))
   (should supertag-view-style-auto-enable)
   (should supertag-org-capture-auto-enable)
   (should-not global-supertag-ui-completion-mode)
   (princ (format "QUERY-C-PASS %S %S\n" qc-stage qc-case)))
 (remove-hook 'after-load-functions #'qc-watch)
 (dolist (entry qc-advice) (advice-remove (car entry) (cdr entry))))))
    (unwind-protect
        (progn
          (with-temp-file script
            (insert ";;; -*- lexical-binding: t; -*-\n")
            (prin1 `(setq qc-root ,root qc-tmp ,tmp qc-stage ',stage qc-case ',scenario
                          qc-symbols '(supertag-index-get-nodes-by-tag supertag-index-get-nodes-by-word supertag-index-get-nodes-by-date-range supertag-find-nodes-by-tag supertag-find-nodes-by-file supertag-find-file-node)) (current-buffer))
            (insert "\n")
            (let ((print-length nil) (print-level nil))
              (prin1 `(condition-case err
                          (unwind-protect ,body
                            (setq kill-emacs-hook nil emacs-startup-hook nil org-mode-hook nil enable-theme-functions nil)
                            (when (fboundp 'qc-watch) (remove-hook 'after-load-functions #'qc-watch))
                            (when (boundp 'qc-advice) (dolist (a qc-advice) (advice-remove (car a) (cdr a))))
                            (mapc #'cancel-timer (append timer-list timer-idle-list))
                            (dolist (b (buffer-list))
                              (when (or (equal (buffer-name b) " *qc-ordinary*")
                                        (and (buffer-file-name b) (file-in-directory-p (buffer-file-name b) qc-tmp)))
                                (with-current-buffer b (set-buffer-modified-p nil) (kill-buffer b)))))
                        (error (princ (format "QUERY-C-ERROR %S\n" err)) (kill-emacs 1))) (current-buffer))))
          ;; Pin the child cwd before HOME is repointed.
          (setq default-directory (file-truename default-directory))
          (setenv "HOME" tmp) (setenv "CFFIXED_USER_HOME" tmp)
          (setenv "EMACSLOADPATH" (concat (mapconcat #'identity deps path-separator) path-separator))
          (with-temp-buffer
            (let ((status (apply #'call-process (or (getenv "EMACS_BIN") (expand-file-name invocation-name invocation-directory))
                                 nil t nil (append '("-Q" "--batch")
                                                   (apply #'append (mapcar (lambda (d) (list "-L" d)) deps))
                                                   (list "-L" root "-l" script)))))
              (when-let* ((out (getenv "SUPERTAG_QC_EVIDENCE")))
                (write-region (point-min) (point-max) (expand-file-name (format "%s-%s.log" stage scenario) out) nil 'silent)
                (copy-file script (expand-file-name (format "%s-%s.el" stage scenario) out) t))
              (princ (buffer-string))
              (should (equal status 0))
              (should (string-match-p "QUERY-C-ENTRY" (buffer-string)))
              (should (string-match-p (format "QUERY-C-DONE %s" scenario) (buffer-string)))
              (should (string-match-p (format "QUERY-C-PASS %s %s" stage scenario) (buffer-string))))))
      (delete-directory tmp t))))


(ert-deftest supertag-document-query-c-local () (supertag-document-query--c-cold 'local))

(ert-deftest supertag-document-query-c-tags () (supertag-document-query--c-cold 'tags))

(ert-deftest supertag-document-query-c-node () (supertag-document-query--c-cold 'node))

(ert-deftest supertag-document-query-c-sync () (supertag-document-query--c-cold 'sync))

(ert-deftest supertag-document-query-c-input () (supertag-document-query--c-cold 'input))

(ert-deftest supertag-document-query-c-main () (supertag-document-query--c-cold 'main))

(ert-deftest supertag-document-query-c-owner () (supertag-document-query--c-cold 'owner))

;;; QUERY-D warm real render/Org execution; independent from QA/B/C stages.
(ert-deftest supertag-document-query-d-generated-output ()
  (supertag-document-test-with-vault
    (load (expand-file-name
           (if (equal (getenv "SUPERTAG_QD_STAGE") "before")
               "supertag-query-block.el" "supertag-query.el")
           supertag-document-query--a-root) nil nil t)
    (with-current-buffer (find-file-noselect file)
      (goto-char (point-max))
      (insert "\nOutside [[id:manual][Manual]].\n| [[id:manual-table][Manual table]] |\n\n"
              "#+BEGIN_SRC supertag-query-block :results raw\n(property \"ROLE\" \"generated\")\n#+END_SRC\n\n"
              "#+BEGIN: supertag-query :query \"(property \\\"ROLE\\\" \\\"generated\\\")\"\n#+END:\n\n"
              "* Zulu :gen:\n:PROPERTIES:\n:ID: generated-z\n:ROLE: generated\n:SCORE: 2\n:GROUP: g\n:END:\nTarget Z.\n"
              "* Alpha :gen:\n:PROPERTIES:\n:ID: generated-a\n:ROLE: generated\n:SCORE: 4\n:GROUP: g\n:END:\nTarget A.\n")
      (save-buffer))
    (supertag-sync--process-single-file file (list :nodes-created 0 :nodes-updated 0 :nodes-deleted 0))
    (let ((disk (supertag-document-test-disk file))
          (facts (prin1-to-string supertag--store))
          (ids (copy-tree org-id-locations))
          (org-confirm-babel-evaluate nil)
          (save-count 0) (mode-count 0))
      (cl-letf* ((original-save (symbol-function 'save-buffer))
                 ((symbol-function 'save-buffer)
                  (lambda (&rest args) (cl-incf save-count) (apply original-save args))))
        (let ((org-mode-hook (cons (lambda () (cl-incf mode-count)) org-mode-hook)))
          (let ((table (supertag-query-block--render
                        "(property \"ROLE\" \"generated\")" '(:columns "SCORE" :sort "title" :order "asc" :limit 1))))
            (should (string-match-p "\\[\\[id:generated-a\\]\\[Alpha\\]\\]" table))
            (should-not (string-match-p "generated-z" table))
            (should (string-match-p "SCORE" table)))
          (should (> mode-count 0))
          (let ((table (supertag-query-block--render
                        "(and (property \"ROLE\" \"generated\") (sort-by \"title\" desc))"
                        '(:sort "title" :order "asc" :limit 1))))
            (should (string-match-p "generated-z" table))
            (should-not (string-match-p "generated-a" table)))
          (should (string-match-p "nil" (supertag-query-block--render
                                       "(and (property \"ROLE\" \"generated\") (sum \"SCORE\"))"
                                       '(:limit -1))))
          (should (string-match-p "4" (supertag-query-block--render
                                       "(and (property \"ROLE\" \"generated\") (first \"SCORE\"))" nil)))
          (should (string-match-p "Group" (supertag-query-block--render
                                           "(and (property \"ROLE\" \"generated\") (group-by \"GROUP\") (sum \"SCORE\"))" nil)))
          (should (equal "No results found." (supertag-query-block--render "(property \"ROLE\" \"none\")" nil)))
          (should (string-prefix-p "Error:" (supertag-query-block--render "(" nil)))
          (should (string-prefix-p "Error:" (supertag-query-block--render "(term \"Zulu\")" '(:limit -1))))
          (should-error (supertag-query-block--render-results '(unknown-query))))
        (with-current-buffer (find-file-noselect file)
          (goto-char (point-min)) (search-forward "#+BEGIN_SRC") (beginning-of-line)
          (let ((result (org-babel-execute-src-block)))
            (should (stringp result))
            (should (string-match-p "generated-a" result)))
          (should (save-excursion (goto-char (point-min)) (search-forward "#+RESULTS:" nil t)))
          (goto-char (point-min)) (search-forward "#+BEGIN:") (beginning-of-line)
          (org-dblock-update)
          (let ((once (buffer-string)))
            (org-dblock-update)
            (should (equal once (buffer-string))))
          (should (buffer-modified-p)))
        (should (= save-count 0)))
      (should (equal disk (supertag-document-test-disk file)))
      (should (equal facts (prin1-to-string supertag--store)))
      (should (equal ids org-id-locations))
      ;; Only this explicit test action persists generated output, then projects it.
      (with-current-buffer (find-file-noselect file) (save-buffer))
      (supertag-sync--process-single-file file (list :nodes-created 0 :nodes-updated 0 :nodes-deleted 0))
      (should (equal '("manual" "manual-table")
                     (plist-get (supertag-store-get-entity :nodes "document-node") :ref-to)))
      (should (string-match-p "generated-a" (supertag-document-test-disk file)))
      (princ "QUERY-D-DONE generated-output\n"))))

(defun supertag-document-query--d-cold (scenario)
  (let* ((root supertag-document-query--a-root)
         (stage (if (equal (getenv "SUPERTAG_QD_STAGE") "before") 'before 'after))
         (tmp (make-temp-file "supertag-query-d-" t))
         (script (expand-file-name "cold.el" tmp))
         (deps (split-string (or (getenv "SUPERTAG_DEPS_LOADPATH") "") path-separator t))
         (process-environment (copy-sequence process-environment))
         (body '
(progn
 (require 'ert) (require 'cl-lib)
 (setq user-emacs-directory (file-name-as-directory qd-tmp)
       supertag-data-directory (expand-file-name "data/" qd-tmp)
       supertag--base-data-directory supertag-data-directory
       supertag-db-file (expand-file-name "store.el" qd-tmp)
       supertag-db-backup-directory (expand-file-name "backups/" qd-tmp)
       supertag-sync-state-file (expand-file-name "sync.el" qd-tmp)
       supertag-sync--state-source supertag-sync-state-file
       supertag-sync-directories nil org-id-locations-file (expand-file-name "ids" qd-tmp)
       org-id-locations nil org-id-files nil org-id-track-globally nil
       after-init-time nil make-backup-files nil auto-save-default nil
       supertag-view-style-auto-enable t supertag-org-capture-auto-enable t
       global-supertag-ui-completion-mode nil)
 (defvar qd-mode-count 0)
 (defvar qd-events nil)
 (defun qd-mode-observer () (cl-incf qd-mode-count))
 (setq org-mode-hook '(qd-mode-observer))
 (defun qd-load-observer (file)
   (when (and (stringp file) (string-prefix-p qd-root file))
     (push (list (file-name-base file) (featurep 'org) (featurep 'supertag-node)
                 (featurep 'supertag-tag) (and (boundp 'org-babel-load-languages)
                                              (member '(supertag-query-block . t) org-babel-load-languages))) qd-events)))
 (add-hook 'after-load-functions #'qd-load-observer)
 (defun qd-absent (features)
   (dolist (f features)
     (should-not (featurep f))
     (should-not (cl-find-if (lambda (row) (and (stringp (car row)) (equal (file-name-base (car row)) (symbol-name f)))) load-history))))
 (defvar org-babel-load-languages) (defvar org-babel-default-header-args)
 (when (eq qd-case 'exact)
   (let ((org-babel-load-languages nil) (org-babel-default-header-args nil)) (require 'org)))
 (let* ((preset-lang (pcase qd-case ((or 'exact 'exact-failure) '((supertag-query-block . t))) ('conflict '((supertag-query-block . nil))) (_ nil)))
        (preset-headers (pcase qd-case ((or 'exact 'exact-failure) '((supertag-query-block . ((:results . "raw"))))) ('conflict '((supertag-query-block . ((:results . "value"))))) (_ nil)))
        (org-babel-load-languages (copy-tree preset-lang))
        (org-babel-default-header-args (copy-tree preset-headers))
        (target (get-buffer-create " *qd-target*")))
   ;; Variables must be special even before Org defines them.
   (defvar org-babel-load-languages) (defvar org-babel-default-header-args)
   (unless (eq qd-case 'exact) (should-not (featurep 'org)))
   (when (eq qd-case 'org-first) (require 'org))
   (if (eq qd-case 'exact-failure)
       (let (caught)
         (condition-case err
             (load (expand-file-name "supertag-query.el" qd-root) nil nil t)
           (error (setq caught err)))
         (should-not caught)
         (should (featurep 'org))
         (should (featurep 'supertag-query))
         (should (featurep 'ob-supertag-query-block))
         (should (fboundp 'org-babel-execute:supertag-query-block))
         (should (equal preset-headers org-babel-default-header-args))
         (should (fboundp 'supertag-query-node))
         (princ "QUERY-D-EXACT-PRESET-USABLE\n"))
     (progn
   (load (expand-file-name (pcase qd-case ('main "supertag.el")
                                 ((or 'menu-add 'menu-build 'menu-syntax) "supertag-menu.el")
                                 (_ "supertag-query.el")) qd-root) nil nil t)
   (princ (format "QUERY-D-ENTRY %S org=%S query=%S\n" qd-case (featurep 'org) (featurep 'supertag-query)))
   (when (eq qd-case 'owner)
     (dolist (s qd-functions) (should (equal (symbol-file s 'defun) (expand-file-name "supertag-query.el" qd-root))))
     (dolist (s qd-constants) (should (equal (symbol-file s 'defvar) (expand-file-name "supertag-query.el" qd-root))))
     (should-not (file-exists-p (expand-file-name "supertag-query-block.el" qd-root))))
   (cond
    ((memq qd-case '(empty exact exact-failure conflict org-first owner))
     (should (= qd-mode-count 0))
     (should-not supertag--store)
     (qd-absent '(supertag-node supertag-tag supertag-services-ui supertag-services-sync supertag-service-org))
     (when (eq qd-stage 'before)
       (unless (memq qd-case '(org-first exact)) (should-not (featurep 'org)))
       (should (equal preset-lang org-babel-load-languages))
       (load (expand-file-name "supertag-query-block.el" qd-root) nil nil t))
     (should (featurep 'org)) (should (featurep 'org-table))
     (let ((expected-lang (copy-tree preset-lang)) (expected-headers (copy-tree preset-headers)))
       (should (equal expected-lang org-babel-load-languages))
       (should (equal expected-headers org-babel-default-header-args))
       (load (expand-file-name (if (eq qd-stage 'before) "supertag-query-block.el" "supertag-query.el") qd-root) nil nil t)
       (should (equal expected-lang org-babel-load-languages))
       (should (equal expected-headers org-babel-default-header-args)))
     (when (eq qd-stage 'after)
       (qd-absent '(supertag-query-block supertag-node supertag-tag supertag-services-ui supertag-services-sync supertag-service-org)))
     (dolist (s qd-functions)
       (should (equal (symbol-file s 'defun) (expand-file-name (if (eq qd-stage 'before) "supertag-query-block.el" "supertag-query.el") qd-root))))
     (princ (format "QUERY-D-DONE %S\n" qd-case)))
    ((eq qd-case 'main)
     (should-not after-init-time) (should (memq 'supertag-init emacs-startup-hook))
     (should-not (file-exists-p supertag-db-file))
     (let ((query (assoc "supertag-query" (reverse qd-events))))
       (should query)
         (if (eq qd-stage 'before)
           (progn (should-not (nth 4 query))
                  (should-not (nth 4 (assoc "supertag-query-block" (reverse qd-events)))))
         (should (nth 1 query)) (should-not (nth 4 query))
         (should-not (nth 2 query)) (should-not (nth 3 query))))
     (princ "QUERY-D-DONE main\n"))
    (t
     (qd-absent '(supertag-query supertag-query-block))
     (with-current-buffer target
       (pcase qd-case
         ('menu-add
          (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "")))
            (call-interactively #'supertag-menu--add-query-block))
          (should (equal "" (buffer-string)))
          (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "(term \"Needle\")")))
            (call-interactively #'supertag-menu--add-query-block))
          (should (equal "#+BEGIN_SRC supertag-query-block :results raw\n(term \"Needle\")\n#+END_SRC" (buffer-string)))
          (should (buffer-modified-p))
          (princ "QUERY-D-DONE menu-add\n"))
         ('menu-syntax
          (call-interactively #'supertag-menu--query-describe-syntax)
          (with-current-buffer "*Supertag Query Syntax*"
            (should (eq major-mode 'special-mode)) (should buffer-read-only)
            (should (equal (buffer-string) supertag-query-block--syntax-reference-text)))
          (princ "QUERY-D-DONE menu-syntax\n"))
         ('menu-build
          (let ((answers '("term" "and" "term" "no" "Copy to kill-ring"))
                (texts '("Needle" "Other")))
            (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) (pop answers)))
                      ((symbol-function 'read-string) (lambda (&rest _) (pop texts)))
                      ((symbol-function 'y-or-n-p) (lambda (&rest _) t)))
              (call-interactively #'supertag-menu--query-build))
            (should-not answers) (should-not texts)
            (should (equal "(not (and (term \"Needle\") (term \"Other\")))" (car kill-ring))))
          (supertag--ensure-store)
          (supertag-store-put-entity :nodes "p" '(:id "p" :title "Needle" :tags ("root") :properties (:ROLE "real")))
          (supertag-store-put-entity :tags "root" '(:id "root" :name "root"))
          (supertag-store-put-entity :relations "r" '(:id "r" :from "p" :to "p" :type :reference :kind :document-link :origin :org :relation-name "knows"))
          (let ((facts (prin1-to-string supertag--store)))
            (cl-letf (((symbol-function 'completing-read)
                       (lambda (_prompt candidates &rest _) (should (member "root" candidates)) "root")))
              (should (equal "root" (supertag-query-block--read-tag-name))))
            (cl-letf (((symbol-function 'completing-read)
                       (lambda (_prompt candidates &rest _) (should (equal '("knows") candidates)) "knows")))
              (should (equal "knows" (supertag-query-block--read-link-reference))))
            (dolist (action '("Insert block" "Run now"))
              (let ((answers (list "term" "no" action)))
                (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) (pop answers)))
                          ((symbol-function 'read-string) (lambda (&rest _) "Needle"))
                          ((symbol-function 'y-or-n-p) (lambda (&rest _) nil)))
                  (call-interactively #'supertag-menu--query-build))
                (should-not answers)))
            (with-current-buffer target (should (string-match-p (regexp-quote "#+BEGIN_SRC") (buffer-string))))
            (with-current-buffer "*Supertag Query Results*"
              (should (eq major-mode 'org-mode)) (should view-mode) (should buffer-read-only)
              (should (string-match-p "\\[\\[id:p\\]\\[Needle\\]\\]" (buffer-string))))
            (dolist (row `((supertag-node-format-link . ,(if (or (eq qd-stage 'before) (equal (getenv "SUPERTAG_LB_STAGE") "before")) "supertag-ops-node.el" "supertag-link.el"))
                           (supertag-node-get . "supertag-node.el")
                           (supertag-ui-read-tag . "supertag-tag.el")
                           (supertag-view-api-list-tag-ids . "supertag-tag.el")
                           (supertag-relation-named-document-link-p . ,(if (or (eq qd-stage 'before) (equal (getenv "SUPERTAG_LC_STAGE") "before")) "supertag-ops-relation.el" "supertag-link.el"))))
              (should-not (autoloadp (symbol-function (car row))))
              (should (equal (symbol-file (car row) 'defun) (expand-file-name (cdr row) qd-root))))
            (should (equal facts (prin1-to-string supertag--store))))
          (princ "QUERY-D-DONE menu-build\n"))
         (_ (error "QD unknown menu case"))))))
   (princ (format "QUERY-D-EVENTS %S\n" (reverse qd-events)))
   (should-not (file-exists-p supertag-db-file))
   (princ (format "QUERY-D-PASS %S %S\n" qd-stage qd-case)))))
 (remove-hook 'after-load-functions #'qd-load-observer))))
    (unwind-protect
        (progn
          (with-temp-file script
            (insert ";;; -*- lexical-binding: t; -*-\n")
            (prin1 `(setq qd-root ,root qd-tmp ,tmp qd-stage ',stage qd-case ',scenario
                          qd-functions '(supertag-query-block--format-table supertag-query-block--parse-columns supertag-query-block--normalize-sort-key supertag-query-block--normalize-order supertag-query-block--normalize-limit supertag-query-block--sort-value supertag-query-block--numeric supertag-query-block--value< supertag-query-block--apply-sort supertag-query-block--row supertag-query-block--aggregate-headers-and-rows supertag-query-block--headers-and-rows supertag-query-block--render supertag-add-query-block org-babel-execute:supertag-query-block org-dblock-write:supertag-query supertag-query-block--render-results supertag-query-block--completing-read-operator supertag-query-block--annotate-operator supertag-query-block--live-tag-names supertag-query-block--live-property-names supertag-query-block--read-tag-name supertag-query-block--read-property-name supertag-query-block--read-link-reference supertag-query-block--read-date supertag-query-block--make-condition supertag-query-block--combine-conditions supertag-query-block--build-condition supertag-query-block--present-built-query supertag-query-build supertag-query-describe-syntax) qd-constants '(supertag-query-block--operators supertag-query-block--syntax-reference-text)) (current-buffer))
            (insert "\n")
            (let ((print-length nil) (print-level nil))
              (prin1 `(condition-case err
                          (unwind-protect ,body
                            (setq kill-emacs-hook nil emacs-startup-hook nil org-mode-hook nil enable-theme-functions nil)
                            (when (fboundp 'qd-load-observer) (remove-hook 'after-load-functions #'qd-load-observer))
                            (mapc #'cancel-timer (append timer-list timer-idle-list))
                            (dolist (b (buffer-list))
                              (when (or (member (buffer-name b) '(" *qd-target*" "*Supertag Query Results*" "*Supertag Query Syntax*"))
                                        (and (buffer-file-name b) (file-in-directory-p (buffer-file-name b) qd-tmp)))
                                (with-current-buffer b (set-buffer-modified-p nil) (kill-buffer b)))))
                        (error (princ (format "QUERY-D-ERROR %S\n" err)) (kill-emacs 1))) (current-buffer))))
          ;; Pin the child cwd before HOME is repointed.
          (setq default-directory (file-truename default-directory))
          (setenv "HOME" tmp) (setenv "CFFIXED_USER_HOME" tmp)
          (setenv "EMACSLOADPATH" (concat (mapconcat #'identity deps path-separator) path-separator))
          (with-temp-buffer
            (let ((status (apply #'call-process (or (getenv "EMACS_BIN") (expand-file-name invocation-name invocation-directory))
                                 nil t nil (append '("-Q" "--batch")
                                                   (apply #'append (mapcar (lambda (d) (list "-L" d)) deps))
                                                   (list "-L" root "-l" script)))))
              (when-let* ((out (getenv "SUPERTAG_QD_EVIDENCE")))
                (write-region (point-min) (point-max) (expand-file-name (format "%s-%s.log" stage scenario) out) nil 'silent)
                (copy-file script (expand-file-name (format "%s-%s.el" stage scenario) out) t))
              (princ (buffer-string))
              (should (equal status 0))
              (if (eq scenario 'exact-failure)
                  (should (string-match-p "QUERY-D-EXACT-PRESET-USABLE" (buffer-string)))
                (should (string-match-p "QUERY-D-ENTRY" (buffer-string)))
                (should (string-match-p (format "QUERY-D-DONE %s" scenario) (buffer-string)))
                (should (string-match-p (format "QUERY-D-PASS %s %s" stage scenario) (buffer-string)))))))
      (delete-directory tmp t))))


(ert-deftest supertag-document-query-d-empty () (supertag-document-query--d-cold 'empty))

(ert-deftest supertag-document-query-d-exact () (supertag-document-query--d-cold 'exact))

(ert-deftest supertag-document-query-d-conflict () (supertag-document-query--d-cold 'conflict))

(ert-deftest supertag-document-query-d-org-first () (supertag-document-query--d-cold 'org-first))

(ert-deftest supertag-document-query-d-main () (supertag-document-query--d-cold 'main))

(ert-deftest supertag-document-query-d-menu-add () (supertag-document-query--d-cold 'menu-add))

(ert-deftest supertag-document-query-d-menu-build () (supertag-document-query--d-cold 'menu-build))

(ert-deftest supertag-document-query-d-menu-syntax () (supertag-document-query--d-cold 'menu-syntax))

(ert-deftest supertag-document-query-d-owner () (supertag-document-query--d-cold 'owner))

(ert-deftest supertag-document-query-d-exact-failure () (supertag-document-query--d-cold 'exact-failure))

;;; QUERY-E independent read-adapter controls.
(ert-deftest supertag-document-query-e-saved-properties ()
  (supertag-document-test-with-vault
    (when (equal (getenv "SUPERTAG_QE_STAGE") "before") (require 'supertag-view-api))
    (princ "QUERY-E-ENTRY saved-properties\n")
    (with-current-buffer (find-file-noselect file)
      (goto-char (point-max)) (insert "Unsent draft.\n")
      (let ((disk (supertag-document-test-disk file)) (live (buffer-string))
            (dirty (buffer-modified-p)) (facts (prin1-to-string supertag--store))
            (ids (prin1-to-string org-id-locations)))
        (progn
          (should (equal "first" (supertag-view-api-node-property "document-node" "aLpHa")))
          (should (equal "" (supertag-view-api-node-property "document-node" "EMPTY")))
          (should-not (supertag-view-api-node-property "document-node" "MISSING")))
        (dolist (bad '(nil "" 1 :ALPHA))
          (should-error (supertag-view-api-node-property "document-node" bad)))
        (should-not (supertag-view-api-node-property "absent" "ALPHA"))
        (should (equal disk (supertag-document-test-disk file)))
        (should (equal live (buffer-string))) (should (eq dirty (buffer-modified-p)))
        (should (equal facts (prin1-to-string supertag--store)))
        (should (equal ids (prin1-to-string org-id-locations)))))
    (princ "QUERY-E-DONE saved-properties\n")))

(defun supertag-document-query--e-cold (scenario)
  (let* ((root supertag-document-query--a-root)
         (stage (if (equal (getenv "SUPERTAG_QE_STAGE") "before") 'before 'after))
         (tmp (make-temp-file "supertag-query-e-" t))
         (script (expand-file-name "cold.el" tmp))
         (deps (split-string (or (getenv "SUPERTAG_DEPS_LOADPATH") "") path-separator t))
         (process-environment (copy-sequence process-environment))
         (body
          '(progn
             (require 'ert) (require 'cl-lib)
             (setq user-emacs-directory (file-name-as-directory qe-tmp)
                   supertag-data-directory (expand-file-name "data/" qe-tmp)
                   supertag--base-data-directory supertag-data-directory
                   supertag-db-file (expand-file-name "store.el" qe-tmp)
                   supertag-db-backup-directory (expand-file-name "backups/" qe-tmp)
                   supertag-sync-state-file (expand-file-name "sync.el" qe-tmp)
                   supertag-sync--state-source supertag-sync-state-file
                   supertag-sync-directories nil
                   org-id-locations-file (expand-file-name "ids" qe-tmp)
                   org-id-locations nil org-id-files nil org-id-track-globally nil
                   after-init-time nil make-backup-files nil auto-save-default nil
                   org-mode-hook nil org-babel-load-languages nil
                   global-supertag-ui-completion-mode nil)
             (defun qe-absent (features)
               (dolist (f features)
                 (should-not (featurep f))
                 (should-not (cl-find-if
                              (lambda (row) (and (stringp (car row))
                                                (equal (file-name-base (car row)) (symbol-name f))))
                              load-history))))
             (load (expand-file-name "supertag-query.el" qe-root) nil nil t)
             (princ (format "QUERY-E-ENTRY %s query=%S\n" qe-case (featurep 'supertag-query)))
             (should (featurep 'supertag-query)) (should-not supertag--store)
             (qe-absent '(supertag-node supertag-tag supertag-view-api supertag-services-ui
                                       supertag-services-sync supertag-ops-relation supertag-link))
             (if (eq qe-case 'owner)
                 (progn
                   (dolist (f qe-forms)
                     (should (equal (symbol-file f 'defun) (expand-file-name "supertag-query.el" qe-root))))
                   (load (expand-file-name (if (or (eq qe-stage 'before) (equal (getenv "SUPERTAG_VWB_STAGE") "before")) "supertag-view-api.el" "supertag-view-framework.el") qe-root) nil nil t)
                   (load (expand-file-name (if (or (eq qe-stage 'before) (equal (getenv "SUPERTAG_VWB_STAGE") "before")) "supertag-view-api.el" "supertag-view-framework.el") qe-root) nil nil t)
                   (dolist (f qe-forms)
                     (should (equal (symbol-file f 'defun) (expand-file-name "supertag-query.el" qe-root))))
                   (should (equal (symbol-file 'supertag-view-api-subscribe 'defun)
                                  (expand-file-name (if (or (eq qe-stage 'before) (equal (getenv "SUPERTAG_VWB_STAGE") "before")) "supertag-view-api.el" "supertag-view-framework.el") qe-root))))
               (when (eq qe-stage 'before)
                 (load (expand-file-name "supertag-view-api.el" qe-root) nil nil t))
               (supertag--ensure-store)
               (cond
                ((eq qe-case 'relation)
                 (let ((record (list :id "embedded-relation" :from "a" :to "b")))
                   (supertag-store-put-entity :relations "relation-key" record)
                   (princ "QUERY-E-RELATION-CALL\n")
                   (should (eq record (supertag-view-api-get-entity :relation "relation-key")))
                   (should (equal "embedded-relation"
                                  (plist-get (supertag-view-api-get-entity :relations "relation-key") :id)))
                   (should-not (autoloadp (symbol-function 'supertag-relation-get)))
                   (should (equal (symbol-file 'supertag-relation-get 'defun)
                                  (expand-file-name (if (or (eq qe-stage 'before) (equal (getenv "SUPERTAG_LC_STAGE") "before")) "supertag-ops-relation.el" "supertag-link.el") qe-root)))
                   (should (cl-find-if (lambda (row) (and (stringp (car row))
                                                        (equal (file-name-base (car row)) (if (or (eq qe-stage 'before) (equal (getenv "SUPERTAG_LC_STAGE") "before")) "supertag-ops-relation" "supertag-link")))) load-history))))
                ((eq qe-case 'node)
                 (let ((record (list :id "n" :title "Node")))
                   (supertag-store-put-entity :nodes "n" record)
                   (should (eq record (supertag-view-api-get-entity :node "n")))
                   (should (featurep 'supertag-node))
                   (should-not (autoloadp (symbol-function 'supertag-node-get)))))
                ((eq qe-case 'tag)
                 (let ((record (list :id "parent" :name "Parent")))
                   (supertag-store-put-entity :tags "parent" record)
                   (should (eq record (supertag-view-api-get-entity :tag "parent")))
                   (should (equal '("parent") (supertag-view-api-list-entity-ids '(:type :tags))))
                   (should (featurep 'supertag-tag))
                   (should-not (autoloadp (symbol-function 'supertag-view-api-list-tag-ids)))))
                (t
                 ;; Direct Store seeds; saved-property control uses real Org projection.
                 (dolist (entry '(("parent" :id "parent" :name "Parent" :aliases ("alias"))
                                  ("parent/child" :id "parent/child" :name "Parent/Child" :extends ("parent"))))
                   (supertag-store-put-entity :tags (car entry) (cdr entry)))
                 (dolist (entry '(("a" :id "a" :title "Alpha" :tags ("parent"))
                                  ("b" :id "b" :title "Beta" :tags ("parent/child"))))
                   (supertag-store-put-entity :nodes (car entry) (cdr entry)))
                 (supertag-store-put-entity :relations "map-key" '(:id "embedded-id" :from "a" :to "b"))
                 (supertag-store-put-entity :automations "z-key" '(:id "rule-z" :name "Zulu"))
                 (supertag-store-put-entity :automations "a-key" '(:id "rule-a" :name "Alpha"))
                 (let ((facts (prin1-to-string supertag--store)))
                   (if (eq qe-case 'dataset)
                       (progn
                         (should (equal '("a" "b") (supertag-view-api-list-entity-ids '(:type :nodes))))
                         (should (equal '("parent" "parent/child") (supertag-view-api-list-entity-ids '(:type :tags))))
                         (dolist (token '("parent" "alias"))
                           (should (equal '("a") (supertag-view-api-list-entity-ids (list :type :tag :value token))))
                           (should (equal '("a" "b") (sort (supertag-view-api-list-entity-ids
                                                          (list :type :tag :value token :include-descendants t)) #'string<))))
                         (should (equal '("embedded-id") (supertag-view-api-list-entity-ids '(:type :relations))))
                         (dolist (type '(:automation :automations))
                           (should (equal '("rule-a" "rule-z") (supertag-view-api-list-entity-ids (list :type type)))))
                         (dolist (type '(:embeds :database :databases))
                           (should-not (supertag-view-api-list-entity-ids (list :type type))))
                         (dolist (type '(:node :relation nil :unknown))
                           (should-error (supertag-view-api-list-entity-ids (list :type type))))
                         (dolist (bad '(nil "" 9))
                           (should-error (supertag-view-api-list-entity-ids (list :type :tag :value bad)))))
                     (dolist (pair '((:node :nodes "a" :nodes "a")
                                     (:tag :tags "parent" :tags "parent")
                                     (:relation :relations "map-key" :relations "map-key")
                                     (:automation :automations "rule-a" :automations "a-key")))
                       (let ((raw (supertag-store-get-entity (nth 3 pair) (nth 4 pair))))
                         (dolist (type (list (car pair) (cadr pair)))
                           (should (eq raw (supertag-view-api-get-entity type (nth 2 pair))))
                           (should-not (supertag-view-api-get-entity type "missing")))))
                     (dolist (type '(:embed :embeds :database :databases :unknown))
                       (should-not (supertag-view-api-get-entity type "a")))
                     (dolist (bad '(nil "" 3))
                       (should-error (supertag-view-api-get-entity :unknown bad)))
                     (let ((rows (supertag-view-api-get-entities :nodes '("b" nil "missing" "a" "b"))))
                       (should (equal '("b" "a" "b") (mapcar (lambda (n) (plist-get n :id)) rows)))
                       (should (eq (car rows) (nth 2 rows))))
                     (should-error (supertag-view-api-get-entities :nodes '("a" ""))))
                   (should (equal facts (prin1-to-string supertag--store))))))
               (should-not (file-exists-p supertag-db-file))
               (princ (format "QUERY-E-COST %s %S\n" qe-case
                              (mapcar (lambda (f) (cons f (featurep f)))
                                      '(supertag-node supertag-tag supertag-view-api supertag-services-ui supertag-services-sync supertag-ops-relation supertag-link)))))
             (princ (format "QUERY-E-DONE %s\n" qe-case)))))
    (unwind-protect
        (progn
          (with-temp-file script
            (insert ";;; -*- lexical-binding: t; -*-\n")
            (prin1 `(setq qe-root ,root qe-tmp ,tmp qe-stage ',stage qe-case ',scenario
                          qe-forms '(supertag-view-api-list-entity-ids supertag-view-api-get-entity
                                     supertag-view-api-get-entities supertag-view-api-node-property))
                   (current-buffer))
            (insert "\n")
            (let ((print-length nil) (print-level nil))
              (prin1 `(condition-case err
                          (unwind-protect ,body
                            (setq kill-emacs-hook nil emacs-startup-hook nil org-mode-hook nil enable-theme-functions nil)
                            (mapc #'cancel-timer (append timer-list timer-idle-list))
                            (dolist (b (buffer-list))
                              (when (and (buffer-file-name b) (file-in-directory-p (buffer-file-name b) qe-tmp))
                                (with-current-buffer b (set-buffer-modified-p nil) (kill-buffer b)))))
                        (error (princ (format "QUERY-E-ERROR %S\n" err)) (kill-emacs 1)))
                     (current-buffer))))
          ;; Pin the child cwd before HOME is repointed.
          (setq default-directory (file-truename default-directory))
          (setenv "HOME" tmp) (setenv "CFFIXED_USER_HOME" tmp)
          (setenv "EMACSLOADPATH" (concat (mapconcat #'identity deps path-separator) path-separator))
          (with-temp-buffer
            (let ((status (apply #'call-process (or (getenv "EMACS_BIN") (expand-file-name invocation-name invocation-directory))
                                 nil t nil (append '("-Q" "--batch")
                                                   (apply #'append (mapcar (lambda (d) (list "-L" d)) deps))
                                                   (list "-L" root "-l" script)))))
              (when-let* ((out (getenv "SUPERTAG_QE_EVIDENCE")))
                (write-region (point-min) (point-max) (expand-file-name (format "%s-%s.log" stage scenario) out) nil 'silent)
                (copy-file script (expand-file-name (format "%s-%s.el" stage scenario) out) t))
              (princ (buffer-string))
              (should (equal status 0))
              (should (string-match-p (format "QUERY-E-ENTRY %s" scenario) (buffer-string)))
              (should (string-match-p (format "QUERY-E-DONE %s" scenario) (buffer-string))))))
      (delete-directory tmp t))))

(ert-deftest supertag-document-query-e-dataset () (supertag-document-query--e-cold 'dataset))
(ert-deftest supertag-document-query-e-entities () (supertag-document-query--e-cold 'entities))
(ert-deftest supertag-document-query-e-relation-first () (supertag-document-query--e-cold 'relation))
(ert-deftest supertag-document-query-e-node-first () (supertag-document-query--e-cold 'node))
(ert-deftest supertag-document-query-e-tag-first () (supertag-document-query--e-cold 'tag))
(ert-deftest supertag-document-query-e-owner () (supertag-document-query--e-cold 'owner))

(ert-deftest supertag-document-query-property-shorthand ()
  "Shorthand shares property matching, composition and result columns."
  (let ((supertag--store nil))
    (supertag--ensure-store)
    (supertag-store-put-entity
     :nodes "a" '(:id "a" :title "Alpha"
                     :properties (:STATUS "doing" :OWNER "Ada" :EMPTY "")))
    (supertag-store-put-entity
     :nodes "b" '(:id "b" :title "Beta" :properties (:STATUS "done")))
    (dolist (query '((status "doing") (STATUS "doing")
                     (property "status" "doing") (field "status" "doing")
                     (and (status "doing") (owner "Ada"))
                     (not (status "done")) (empty "")))
      (should (equal '("a") (supertag-query-node-ids query))))
    (should (equal '("a" "b")
                   (sort (supertag-query-node-ids
                          '(or (status "doing") (status "done"))) #'string<)))
    (should-not (supertag-query-node-ids '(status "DOING")))
    (should-not (supertag-query-node-ids '(absent "")))
    (should (equal '("STATUS") (supertag-query-properties '(status "doing"))))
    (let ((rendered (org-babel-execute:supertag-query-block "(status \"doing\")" nil)))
      (should (string-match-p "STATUS" rendered))
      (should (string-match-p "doing" rendered))
      (should-not (string-match-p "Beta" rendered)))))

(ert-deftest supertag-document-query-todo-shorthand-and-reserved-properties ()
  "TODO uses heading state; explicit property bypasses built-in names."
  (let ((supertag--store nil))
    (supertag--ensure-store)
    (supertag-store-put-entity
     :nodes "a" '(:id "a" :todo "TODO" :priority "#A" :tags ("task")
                     :properties (:STATUS "doing" :TODO "drawer"
                                  :TAG "custom" :AND "custom" :PRIORITY "custom")))
    (supertag-store-put-entity :nodes "b" '(:id "b" :todo "DONE"))
    (supertag-store-put-entity :nodes "c" '(:id "c"))
    (dolist (query '((todo "TODO") (task "TODO") (priority "a")
                     (and (todo "TODO") (status "doing"))
                     (and (tag "task") (todo "TODO"))
                     (property "todo" "drawer") (property "tag" "custom")
                     (property "and" "custom") (property "priority" "custom")))
      (should (equal '("a") (supertag-query-node-ids query))))
    (should (equal '("a" "b")
                   (sort (supertag-query-node-ids '(todo "TODO" "DONE")) #'string<)))
    (should-not (supertag-query-node-ids '(todo "todo")))
    (should-not (supertag-query-node-ids '(todo "drawer")))
    (should-not (supertag-query-node-ids '(todo)))))

(ert-deftest supertag-document-query-shorthand-validation ()
  "Only named, single-string properties qualify; built-ins keep validation."
  (dolist (query '((status) (status "a" "b") (status 1) (status doing)
                   (:status "doing") (nil "doing") (42 "doing")
                   ("status" "doing") (tag "a" "b") (property "status")
                   (before "a" "b") (and "custom")))
    (should-error (supertag-query-validate query)))
  (should (equal '(status "doing")
                 (supertag-query-validate '(status "doing"))))
  (should (equal '(todo "TODO")
                 (supertag-query-validate '(todo "TODO")))))
