;;; migrate-fields-test.el --- Migration contracts -*- lexical-binding: t; -*-
(require 'document-fixture)
(require 'supertag-automation)
(require 'supertag-migrate)

(defun supertag-migrate-test-value (node name value &optional type)
  (let* ((entries (gethash :legacy-fields supertag--store))
         (remaining (cl-remove-if (lambda (e) (and (equal node (plist-get e :node))
                                                  (equal name (plist-get e :name)))) entries)))
    (puthash :legacy-fields
             (append remaining (list (supertag-migrate--field-entry
                                      node name value 'global nil (list :name name :type type))))
             supertag--store)))
(defun supertag-migrate-test-field (name type value)
  (supertag-migrate-test-value "document-node" name value type))

(ert-deftest supertag-migrate-mapping-and-preview ()
  (supertag-document-test-with-vault
    (dolist (row '(("bool" :boolean t) ("false" :boolean "false")
                   ("date" :date "2026-09-06") ("choices" :options (a b))
                   ("ref" :node-reference ("document-node" "missing"))
                   ("中文" :text "值") ("a b:c" :text "one\ntwo")
                   ("event-time" :timestamp "2026-09-06 12:34")
                   ("time" :timestamp (27000 0 0 0))
                   ("day" :date (27000 0 0 0))
                   ("blank" :text "") ("TODO" :text "DONE")
                   ("empty" :text nil) ("" :text "ignored")))
      (apply #'supertag-migrate-test-field row))
    (supertag-migrate-test-value "document-node" "undefined-list" '(a b))
    (let* ((before (with-temp-buffer (insert-file-contents file) (buffer-string)))
           (report (supertag-migrate-preview))
           (writes (plist-get (car (plist-get report :nodes)) :writes)))
      (should (equal (cdr (assoc "BOOL" writes)) "true"))
      (should (equal (cdr (assoc "FALSE" writes)) "false"))
      (should (equal (cdr (assoc "DATE" writes)) "2026-09-06"))
      (should (equal (cdr (assoc "CHOICES" writes)) "a b"))
      (should (equal (cdr (assoc "REF" writes))
                     "[[id:document-node][Property Node]] [[id:missing]]"))
      (should (equal (cdr (assoc "中文" writes)) "值"))
      (should (equal (cdr (assoc "A_B_C" writes)) "one two"))
      (should (equal "a b" (cdr (assoc "UNDEFINED-LIST" writes))))
      (should (equal "2026-09-06 12:34" (cdr (assoc "EVENT-TIME" writes))))
      (should (equal (format-time-string "%Y-%m-%d %H:%M" '(27000 0 0 0)) (cdr (assoc "TIME" writes))))
      (should (equal (format-time-string "%Y-%m-%d" '(27000 0 0 0)) (cdr (assoc "DAY" writes))))
      (should (cl-find-if (lambda (item) (and (equal "TODO" (plist-get item :key))
                                            (eq :reserved (plist-get item :reason))))
                          (plist-get report :skipped)))
      (should (= 4 (length (plist-get report :skipped))))
      (should (equal before (with-temp-buffer (insert-file-contents file) (buffer-string))))
      (should-not (buffer-modified-p (find-file-noselect file))))))

(ert-deftest supertag-migrate-apply-conflicts-and-idempotence ()
  (supertag-document-test-with-vault
    (supertag-migrate-test-field "ALPHA" :text "different")
    (supertag-migrate-test-field "ID" :text "replacement")
    (supertag-migrate-test-field "NEW" :text "new value")
    (let* (           (report (supertag-migrate-preview)))
      (should (= 1 (plist-get report :conflict-count)))
      (should (eq :reserved (plist-get (car (plist-get report :skipped)) :reason)))
      (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
        (supertag-migrate-apply))
      (with-temp-buffer
        (insert-file-contents file)
        (should (re-search-forward "^:NEW:[ \t]+new value$" nil t))
        (goto-char (point-min))
        (should (re-search-forward "^:ALPHA:[ \t]+first$" nil t))
        (should-not (search-forward "replacement" nil t)))
      (should (equal "new value" (plist-get (plist-get (supertag-node-get "document-node") :properties) :NEW)))
      (should (= 2 (length (gethash :legacy-fields supertag--store))))
      (should (= 0 (plist-get (supertag-migrate-preview) :write-count))))))

(ert-deftest supertag-migrate-automation-read-only ()
  (supertag-document-test-with-vault
    ;; Seed a persisted legacy rule: new rule creation rejects this vocabulary.
    (let* ((rule (supertag-store-put-entity
                  :automations "legacy-field-rule"
                  '(:id "legacy-field-rule" :name "Field rule" :trigger :on-field-change
                    :condition (and (field-equals "x" "y") (field-changed "x"))
                    :actions ((supertag-field-set "x" "y")))))
           (before (copy-tree rule))
           (report (supertag-migrate-preview)))
      (should (equal "Field rule" (plist-get (car (plist-get report :automations)) :name)))
      (let ((refs (plist-get (car (plist-get report :automations)) :references)))
        (dolist (ref '((:trigger . :on-field-change) (:condition . field-equals)
                       (:condition . field-changed) (:actions . supertag-field-set)))
          (should (member ref refs))))
      (should (equal before rule)))))
(ert-deftest supertag-migrate-live-conflict-cancel-and-unlocatable ()
  (supertag-document-test-with-vault
    (supertag-migrate-test-field "ALPHA" :text "field value")
    (supertag-migrate-test-field "NEW" :text "new value")
    (supertag-migrate-test-value "absent" "x" "x")
    (supertag-store-put-entity :nodes "file-node" (list :id "file-node" :level 0 :file file))
    (supertag-migrate-test-value "file-node" "x" "x")
    (supertag-store-put-entity :nodes "lost" (list :id "lost" :level 1 :file (concat tmp "/missing.org")))
    (supertag-migrate-test-value "lost" "x" "x")
    (with-current-buffer (find-file-noselect file)
      (goto-char (point-min))
      (org-entry-put nil "ALPHA" "live draft")
      (let ((live (buffer-string))
            (disk (with-temp-buffer (insert-file-contents file) (buffer-string)))
            (report (supertag-migrate-preview)))
        (should (= 3 (length (plist-get report :skipped))))
        (should (equal "live draft" (plist-get (car (plist-get
                 (cl-find "document-node" (plist-get report :nodes)
                          :key (lambda (node) (plist-get node :id)) :test #'equal)
                 :conflicts)) :org)))
        (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) nil)))
          (should-not (supertag-migrate-apply)))
        (should (equal live (buffer-string)))
        (should (buffer-modified-p))
        (should (equal disk (with-temp-buffer (insert-file-contents file) (buffer-string))))))))

(ert-deftest supertag-migrate-retry-after-second-node-failure ()
  (supertag-document-test-with-vault
    (let ((second (expand-file-name "z.org" tmp)))
      (with-temp-file second (insert "* Second\n:PROPERTIES:\n:ID: second-node\n:END:\nBody\n"))
      (should (eq 'complete (plist-get (supertag-reindex-org) :status)))
      (dolist (id '("document-node" "second-node"))
        (supertag-migrate-test-value id "MIGRATED" "value"))
      (let ((facts (prin1-to-string (gethash :legacy-fields supertag--store)))
            (writer (symbol-function 'supertag-service-org-save-and-project-current-node))
            (failed nil))
        (cl-flet ((disk (path)
                    (with-temp-buffer (insert-file-contents path) (org-mode)
                                      (goto-char (point-min)) (org-entry-get nil "MIGRATED")))
                  (projected (id)
                    (plist-get (plist-get (supertag-node-get id) :properties) :MIGRATED)))
          (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
                    ((symbol-function 'supertag-service-org-save-and-project-current-node)
                     (lambda (id)
                       (if (and (equal id "second-node") (not failed))
                           (progn (setq failed t) (error "One-time second-node failure"))
                         (funcall writer id)))))
            (should-error (supertag-migrate-apply))
            (should (equal "value" (disk file)))
            (should (equal "value" (projected "document-node")))
            (should-not (disk second))
            (should-not (projected "second-node"))
            (with-current-buffer (find-file-noselect second)
              (goto-char (point-min))
              (should (equal "value" (org-entry-get nil "MIGRATED"))))
            (let ((report (supertag-migrate-preview)))
              (should (= 0 (plist-get report :write-count)))
              (should (= 1 (plist-get report :pending-count))))
            (supertag-migrate-apply)
            (should (equal "value" (disk second)))
            (should (equal "value" (projected "second-node")))
            (should (= 0 (plist-get (supertag-migrate-preview) :pending-count)))
            (should-not (gethash :legacy-fields supertag--store))))))))

(ert-deftest supertag-migrate-key-collisions ()
  (let (reports)
    (dolist (order '(("a b" "a:b") ("a:b" "a b")))
      (supertag-document-test-with-vault
        (dolist (name order)
          (supertag-migrate-test-field name :text name))
        (let* ((report (supertag-migrate-preview))
               (node (car (plist-get report :nodes))))
          (should (= 0 (plist-get report :write-count)))
          (should (= 1 (plist-get report :conflict-count)))
          (should (eq :key-conflict (plist-get (car (plist-get node :conflicts)) :type)))
          (push (plist-get node :conflicts) reports))
        (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
          (supertag-migrate-apply))
        (with-current-buffer (find-file-noselect file)
          (goto-char (point-min)) (should-not (org-entry-get nil "A_B")))
        (supertag-migrate-test-field "a b" :text "same")
        (supertag-migrate-test-field "a:b" :text "same")
        (should (= 1 (plist-get (supertag-migrate-preview) :write-count)))))
    (should (equal (car reports) (cadr reports)))))

(ert-deftest supertag-migrate-retry-projection-only ()
  (supertag-document-test-with-vault
    (supertag-migrate-test-field "REPAIR" :text "value")
    (let ((projector (symbol-function 'supertag-service-org--project-current-node))
          (failed nil))
      (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
                ((symbol-function 'supertag-service-org--project-current-node)
                 (lambda (id)
                   (if failed (funcall projector id)
                     (setq failed t) (error "Projection failure")))))
        (should-error (supertag-migrate-apply))
        (should-not (buffer-modified-p (find-file-noselect file)))
        (should-not (plist-get (plist-get (supertag-node-get "document-node") :properties) :REPAIR))
        (should (= 1 (plist-get (supertag-migrate-preview) :pending-count)))
        (cl-letf (((symbol-function 'supertag-service-org--save-current-buffer)
                   (lambda () (ert-fail "Clean pending projection must not save"))))
          (supertag-migrate-apply))
        (should (equal "value" (plist-get (plist-get (supertag-node-get "document-node") :properties) :REPAIR)))
        (should (= 0 (plist-get (supertag-migrate-preview) :pending-count)))))))

(ert-deftest supertag-migrate-unrelated-draft-is-not-pending ()
  (supertag-document-test-with-vault
    (supertag-migrate-test-field "ID" :text "reserved")
    (with-current-buffer (find-file-noselect file)
      (goto-char (point-max)) (insert "Unrelated draft")
      (should (= 0 (plist-get (supertag-migrate-preview) :pending-count)))
      (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
                ((symbol-function 'supertag-service-org--update-buffer-and-resync)
                 (lambda (&rest _) (ert-fail "No eligible key must not repair"))))
        (supertag-migrate-apply))
      (should (buffer-modified-p)))))

(provide 'migrate-fields-test)
