;;; move-node-ui-test.el --- Move UI adapter tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'org)
(if (equal (getenv "SUPERTAG_SYA_STAGE") "before")
      (require 'supertag-ui-commands)
    (require 'supertag-node))
(require 'supertag-link)

(defmacro move-node-ui-test--fixture (&rest body)
  "Run BODY with temporary source/target files and no runtime writers."
  (declare (indent 0))
  `(let* ((dir (make-temp-file "supertag-move-ui-" t))
          (source (expand-file-name "source.org" dir))
          (target (expand-file-name "target.org" dir))
          source-buffer target-buffer)
     (unwind-protect
         (progn
           (with-temp-file source
             (insert "* Root\n:PROPERTIES:\n:ID: root\n:END:\nBody\n** Child\nChild body\n* Second\nSecond body\n"))
           (with-temp-file target
             (insert "* Target\nBody\n** Existing\nText\n* Last\n"))
           (setq source-buffer (find-file-noselect source)
                 target-buffer (find-file-noselect target))
           (save-window-excursion
             (switch-to-buffer source-buffer)
             (goto-char (point-min))
             (cl-letf (((symbol-function 'save-buffer)
                        (lambda (&rest _) (ert-fail "UI must not save")))
                       ((symbol-function 'supertag-node-identity-ensure-at-point)
                        (lambda (&rest _) (ert-fail "UI must not create IDs")))
                       ((symbol-function 'supertag-node-set-location)
                        (lambda (&rest _) (ert-fail "UI must not update Store")))
                       ((symbol-function 'supertag-reference-materialize-at-point)
                        (lambda (&rest _) (ert-fail "UI must not materialize links"))))
               ,@body)))
       (dolist (buffer (list source-buffer target-buffer))
         (when (buffer-live-p buffer)
           (with-current-buffer buffer (set-buffer-modified-p nil))
           (kill-buffer buffer)))
       (delete-directory dir t))))

(ert-deftest move-node-ui-delegates-once-with-warning-and-source-context ()
  (dolist (command '(supertag-move-node supertag-move-node-and-link))
    (move-node-ui-test--fixture
      (let (calls prompt)
        (cl-letf (((symbol-function 'read-file-name) (lambda (&rest _) target))
                  ((symbol-function 'supertag-ui-select-insert-position)
                   (lambda (_) (goto-char (point-max)) '(:position 1 :level 2)))
                  ((symbol-function 'yes-or-no-p)
                   (lambda (text) (setq prompt text) t))
                  ((symbol-function 'supertag-service-org-move-nodes)
                   (lambda (sources file position level link)
                     (push (list sources file (marker-position position)
                                 (marker-buffer position) level link) calls)
                     (switch-to-buffer target-buffer)
                     (goto-char (point-max))
                     '("root"))))
          (funcall command))
        (should (equal calls (list (list '("root") target 1 target-buffer 2
                                         (eq command 'supertag-move-node-and-link)))))
        (should (string-match-p "All unsaved changes in affected files will be saved" prompt))
        (should (eq (current-buffer) source-buffer))
        (should (eq (window-buffer (selected-window)) source-buffer))
        (should (= (point) 1))
        (should-not (buffer-modified-p source-buffer))))))

(ert-deftest move-node-ui-region-is-readonly-fold-independent-and-collapsed ()
  (move-node-ui-test--fixture
    (org-fold-hide-subtree)
    (let ((before (buffer-string)) (tick (buffer-chars-modified-tick)) roots)
      (unwind-protect
          (progn
            (setq roots (supertag-ui--move-roots-in-region (point-min) (point-max)))
            (should (= 2 (length roots)))
            (should (equal '("Root" "Second")
                           (mapcar (lambda (marker)
                                     (save-excursion (goto-char marker) (org-get-heading t t t t))) roots)))
            (should (equal before (buffer-string)))
            (should (= tick (buffer-chars-modified-tick)))
            (should-not (buffer-modified-p)))
        (mapc (lambda (marker) (set-marker marker nil)) roots)))))

(ert-deftest move-node-ui-region-boundaries-and-idless-delegation ()
  (move-node-ui-test--fixture
    (search-forward "** Child")
    (let ((beg (line-beginning-position)) (end (point-max)) calls)
      (cl-letf (((symbol-function 'read-file-name) (lambda (&rest _) target))
                ((symbol-function 'supertag-ui-select-insert-position)
                 (lambda (_) '(:position 1 :level 1)))
                ((symbol-function 'yes-or-no-p) (lambda (_) t))
                ((symbol-function 'supertag-service-org-move-nodes)
                 (lambda (sources &rest _)
                   (setq calls (mapcar (lambda (marker)
                                         (should (markerp marker))
                                         (save-excursion
                                           (goto-char marker)
                                           (should-not (org-id-get))
                                           (org-get-heading t t t t))) sources))
                   '("created-child" "created-second"))))
        (supertag-move-node beg end))
      (should (equal calls '("Child" "Second"))))
    (goto-char (point-min))
    (search-forward "* Second")
    (let* ((end (line-beginning-position))
           (roots (supertag-ui--move-roots-in-region 2 end)))
      (unwind-protect
          (should (equal '("Child")
                         (mapcar (lambda (m) (goto-char m) (org-get-heading t t t t)) roots)))
        (mapc (lambda (m) (set-marker m nil)) roots)))))

(ert-deftest move-node-ui-refusal-keeps-idless-region-untouched ()
  (move-node-ui-test--fixture
    (let ((text (buffer-string)) (calls 0))
      (cl-letf (((symbol-function 'read-file-name) (lambda (&rest _) target))
                ((symbol-function 'supertag-ui-select-insert-position)
                 (lambda (_) '(:position 1 :level 1)))
                ((symbol-function 'yes-or-no-p) (lambda (_) nil))
                ((symbol-function 'supertag-service-org-move-nodes)
                 (lambda (&rest _) (cl-incf calls))))
        (supertag-move-node (point-min) (point-max)))
      (should (= calls 0))
      (should (equal text (buffer-string)))
      (should-not (buffer-modified-p)))))

(ert-deftest move-node-ui-selector-cancel-restores-both-buffer-contexts ()
  (dolist (exit '(quit error nil))
    (move-node-ui-test--fixture
      (with-current-buffer target-buffer
        (goto-char 3)
        (narrow-to-region 1 7))
      (let ((calls 0) widened)
        (cl-letf (((symbol-function 'read-file-name) (lambda (&rest _) target))
                  ((symbol-function 'supertag-ui-select-insert-position)
                   (lambda (_)
                     (setq widened (> (point-max) 7))
                     (goto-char (point-max))
                     (pcase exit ('quit (signal 'quit nil)) ('error (error "Cancelled")))))
                  ((symbol-function 'supertag-service-org-move-nodes)
                   (lambda (&rest _) (cl-incf calls))))
          (condition-case nil (supertag-move-node) ((error quit) nil)))
        (should widened)
        (should (= calls 0)))
      (should (eq (current-buffer) source-buffer))
      (should (= (point) 1))
      (with-current-buffer target-buffer
        (should (= (point) 3))
        (should (= (point-max) 7))))))

(ert-deftest move-node-ui-service-error-restores-source-window-and-point ()
  (move-node-ui-test--fixture
    (cl-letf (((symbol-function 'read-file-name) (lambda (&rest _) target))
              ((symbol-function 'supertag-ui-select-insert-position)
               (lambda (_) '(:position 1 :level 1)))
              ((symbol-function 'yes-or-no-p) (lambda (_) t))
              ((symbol-function 'supertag-service-org-move-nodes)
               (lambda (&rest _)
                 (switch-to-buffer target-buffer)
                 (error "Service failure"))))
      (should-error (supertag-move-node)))
    (should (eq (current-buffer) source-buffer))
    (should (eq (window-buffer) source-buffer))
    (should (= (point) 1))))

(ert-deftest move-node-ui-single-heading-still-requires-id ()
  (move-node-ui-test--fixture
    (search-forward "* Second")
    (beginning-of-line)
    (cl-letf (((symbol-function 'read-file-name)
               (lambda (&rest _) (ert-fail "Must fail before selection"))))
      (should-error (supertag-move-node) :type 'user-error)
      (should-error (supertag-move-node-and-link) :type 'user-error))))

(ert-deftest move-node-ui-native-position-options-survive-narrowing ()
  (dolist (choice '("File Top" "File End" "Under Heading..." "After Heading..."))
    (move-node-ui-test--fixture
      (with-current-buffer target-buffer
        (goto-char 3)
        (narrow-to-region 1 7))
      (let (result)
        (unwind-protect
            (progn
              (cl-letf (((symbol-function 'completing-read)
                         (lambda (prompt &rest _)
                           (if (string-prefix-p "Insert" prompt) choice "Target"))))
                (setq result (supertag-ui--move-select-target target)))
              (should (markerp (plist-get result :position)))
              (should (= (plist-get result :level) (if (equal choice "Under Heading...") 2 1)))
              (with-current-buffer target-buffer
                (should (= (point) 3))
                (should (= (point-max) 7))))
          (when result (set-marker (plist-get result :position) nil)))))))

(ert-deftest move-node-ui-allows-same-file-selection ()
  (move-node-ui-test--fixture
    (let (called)
      (cl-letf (((symbol-function 'read-file-name) (lambda (&rest _) source))
                ((symbol-function 'supertag-ui-select-insert-position)
                 (lambda (_) (goto-char (point-max)) (list :position (point) :level 1)))
                ((symbol-function 'yes-or-no-p) (lambda (_) t))
                ((symbol-function 'supertag-service-org-move-nodes)
                 (lambda (_sources file marker &rest _)
                   (setq called (and (equal file source) (eq (marker-buffer marker) source-buffer)))
                   '("root"))))
        (supertag-move-node))
      (should called)
      (should (= (point) 1)))))

(defmacro move-node-ui-test--e2e-fixture (&rest body)
  "Run BODY with real Move UI/service writers and isolated temporary files."
  (declare (indent 0))
  `(let* ((dir (make-temp-file "supertag-move-ui-e2e-" t))
          (source (expand-file-name "source.org" dir))
          (target (expand-file-name "target.org" dir))
          (source-text "* Root\n:PROPERTIES:\n:ID: root\n:END:\nBody\n** Child\nChild body\n* Second\nSecond body\n")
          (target-text "* Target\nBody\n* Last\n")
          (supertag--store nil)
          (supertag--subscribers (make-hash-table :test 'equal))
          (supertag-sync--internal-modifications (make-hash-table :test 'equal))
          source-buffer target-buffer)
     (unwind-protect
         (progn
           (with-temp-file source (insert source-text))
           (with-temp-file target (insert target-text))
           (setq source-buffer (find-file-noselect source)
                 target-buffer (find-file-noselect target))
           (supertag--ensure-store)
           (cl-letf (((symbol-function 'supertag-node-location-find)
                      (lambda (id)
                        (cl-loop for buffer in (list source-buffer target-buffer)
                                 thereis
                                 (with-current-buffer buffer
                                   (save-excursion
                                     (save-restriction
                                       (widen)
                                       (goto-char (point-min))
                                       (when (re-search-forward
                                              (concat "^:ID: " (regexp-quote id) "$") nil t)
                                         (org-back-to-heading t)
                                         (point-marker)))))))))
             (save-window-excursion
               (switch-to-buffer source-buffer)
               (goto-char (point-min))
               ,@body)))
       (dolist (buffer (list source-buffer target-buffer))
         (when (buffer-live-p buffer)
           (with-current-buffer buffer (set-buffer-modified-p nil))
           (kill-buffer buffer)))
       (delete-directory dir t))))

(defun move-node-ui-test--disk (file)
  "Return FILE text for Move end-to-end assertions."
  (with-temp-buffer
    (insert-file-contents file)
    (buffer-string)))

(ert-deftest move-node-ui-e2e-public-same-file-after-heading ()
  (move-node-ui-test--e2e-fixture
    (cl-letf (((symbol-function 'read-file-name) (lambda (&rest _) source))
              ((symbol-function 'supertag-ui-select-insert-position)
               (lambda (_)
                 (goto-char (point-max))
                 (list :position (point-marker) :level 1)))
              ((symbol-function 'yes-or-no-p) (lambda (_) t))
              ((symbol-function 'message) #'ignore))
      (should (equal '("root") (supertag-move-node))))
    (let ((text (move-node-ui-test--disk source)))
      (should (< (string-match "^\\* Second$" text)
                 (string-match "^\\* Root$" text)))
      (should (string-match-p "^\\*\\* Child$" text)))
    (should (eq (current-buffer) source-buffer))
    (should (= (point) (point-min)))))

(ert-deftest move-node-ui-e2e-file-top-and-end-order ()
  (dolist (choice '("File Top" "File End"))
    (move-node-ui-test--e2e-fixture
      (cl-letf (((symbol-function 'read-file-name) (lambda (&rest _) target))
                ((symbol-function 'completing-read)
                 (lambda (prompt &rest _)
                   (if (string-prefix-p "Insert" prompt) choice "Target")))
                ((symbol-function 'yes-or-no-p) (lambda (_) t))
                ((symbol-function 'message) #'ignore))
        (should (equal '("root") (supertag-move-node))))
      (let* ((text (move-node-ui-test--disk target))
             (root (string-match "^\\* Root$" text))
             (target-heading (string-match "^\\* Target$" text))
             (last (string-match "^\\* Last$" text)))
        (if (equal choice "File Top")
            (should (< root target-heading))
          (should (< last root)))
        (should (string-match-p "^\\*\\* Child$" text))))))

(ert-deftest move-node-ui-e2e-after-heading-keeps-whole-subtree-order ()
  (move-node-ui-test--e2e-fixture
    (cl-letf (((symbol-function 'read-file-name) (lambda (&rest _) target))
              ((symbol-function 'completing-read)
               (lambda (prompt &rest _)
                 (if (string-prefix-p "Insert" prompt)
                     "After Heading..."
                   "Target")))
              ((symbol-function 'yes-or-no-p) (lambda (_) t))
              ((symbol-function 'message) #'ignore))
      (should (equal '("root") (supertag-move-node))))
    (let* ((text (move-node-ui-test--disk target))
           (target-heading (string-match "^\\* Target$" text))
           (root (string-match "^\\* Root$" text))
           (child (string-match "^\\*\\* Child$" text))
           (last (string-match "^\\* Last$" text)))
      (should (< target-heading root))
      (should (< root child))
      (should (< child last)))))

(ert-deftest move-node-ui-e2e-native-under-after-accept-ending-delimiters ()
  (dolist (fixture
           '((drawer . "* Target\n:PROPERTIES:\n:ID: target\n:END:\n* Last\n")
             (block . "* Target\n#+begin_src emacs-lisp\n(message \"safe\")\n#+end_src\n* Last\n")))
    (dolist (choice '("Under Heading..." "After Heading..."))
      (move-node-ui-test--e2e-fixture
        (with-current-buffer target-buffer
          (widen)
          (erase-buffer)
          (insert (cdr fixture))
          (save-buffer))
        (cl-letf (((symbol-function 'read-file-name) (lambda (&rest _) target))
                  ((symbol-function 'completing-read)
                   (lambda (prompt &rest _)
                     (if (string-prefix-p "Insert" prompt) choice "Target")))
                  ((symbol-function 'yes-or-no-p) (lambda (_) t))
                  ((symbol-function 'message) #'ignore))
          (should (equal '("root") (supertag-move-node))))
        (let* ((text (move-node-ui-test--disk target))
               (delimiter
                (string-match
                 (if (eq (car fixture) 'drawer) "^:END:$" "^#\\+end_src$")
                 text))
               (root (string-match
                      (if (equal choice "Under Heading...")
                          "^\\*\\* Root$"
                        "^\\* Root$")
                      text))
               (child (string-match
                       (if (equal choice "Under Heading...")
                           "^\\*\\*\\* Child$"
                         "^\\*\\* Child$")
                       text))
               (last (string-match "^\\* Last$" text)))
          (should (< delimiter root))
          (should (< root child))
          (should (< child last)))))))

(ert-deftest move-node-ui-e2e-same-file-move-and-link-keeps-distinct-stub ()
  (move-node-ui-test--e2e-fixture
    (cl-letf (((symbol-function 'read-file-name) (lambda (&rest _) source))
              ((symbol-function 'supertag-ui-select-insert-position)
               (lambda (_)
                 (goto-char (point-max))
                 (list :position (point-marker) :level 1)))
              ((symbol-function 'yes-or-no-p) (lambda (_) t))
              ((symbol-function 'message) #'ignore))
      (should (equal '("root") (supertag-move-node-and-link))))
    (with-current-buffer source-buffer
      (goto-char (point-min))
      (let ((stub-id (org-entry-get nil "ID")))
        (should stub-id)
        (should-not (equal stub-id "root")))
      (org-end-of-meta-data t)
      (should (looking-at-p "\\[\\[id:root\\]\\[Root\\]\\]$"))
      (goto-char (point-max))
      (re-search-backward "^\\* Root$")
      (should (equal "root" (org-entry-get nil "ID")))
      (should (re-search-forward "^\\*\\* Child$" nil t)))))

(ert-deftest move-node-ui-e2e-region-idless-roots-under-heading ()
  (move-node-ui-test--e2e-fixture
    (let (moved)
      (cl-letf (((symbol-function 'read-file-name) (lambda (&rest _) target))
                ((symbol-function 'supertag-ui-select-insert-position)
                 (lambda (_)
                   (goto-char (point-min))
                   (forward-line 1)
                   (list :position (point-marker) :level 2)))
                ((symbol-function 'yes-or-no-p) (lambda (_) t))
                ((symbol-function 'message) #'ignore))
        (setq moved (supertag-move-node (point-min) (point-max))))
      (should (= 2 (length moved)))
      (should (equal "" (move-node-ui-test--disk source)))
      (with-current-buffer target-buffer
        (goto-char (point-min))
        (should (re-search-forward "^\\*\\* Root$" nil t))
        (should (re-search-forward "^\\*\\*\\* Child$" nil t))
        (org-back-to-heading t)
        (should-not (org-entry-get nil "ID"))
        (should (re-search-forward "^\\*\\* Second$" nil t))
        (should (org-entry-get nil "ID"))))))

(ert-deftest move-node-ui-e2e-save-failure-has-no-partial-move ()
  (move-node-ui-test--e2e-fixture
    (with-current-buffer source-buffer
      (goto-char 3)
      (set-mark 6)
      (setq mark-active t)
      (narrow-to-region 1 62))
    (let ((save (symbol-function 'save-buffer)) (calls 0)
          (before '(3 6 1 62)))
      (cl-letf (((symbol-function 'read-file-name) (lambda (&rest _) target))
                ((symbol-function 'supertag-ui-select-insert-position)
                 (lambda (_) (list :position (point-min-marker) :level 1)))
                ((symbol-function 'yes-or-no-p) (lambda (_) t))
                ((symbol-function 'save-buffer)
                 (lambda (&rest args)
                   (apply save args)
                   (when (= 2 (cl-incf calls)) (error "source save failed"))))
                ((symbol-function 'message) #'ignore))
        (should-error (supertag-move-node)))
      (should (equal before
                     (list (point) (mark) (point-min) (point-max)))))
    (should (equal source-text (move-node-ui-test--disk source)))
    (should (equal target-text (move-node-ui-test--disk target)))))

(ert-deftest move-node-ui-e2e-capture-within-target-uses-same-file-writer ()
  (move-node-ui-test--e2e-fixture
    (let ((org-capture-plist '(:supertag t :supertag-tags-prompt t
                               :supertag-move within-target))
          (org-capture-last-stored-marker (point-marker)))
      (cl-letf (((symbol-function 'supertag-capture-finalize-node-at-point)
                 (lambda (_) "root"))
                ((symbol-function 'supertag-capture--get-from-tags-prompt)
                 (lambda (_) nil))
                ((symbol-function 'supertag-ui-select-insert-position)
                 (lambda (_)
                   (goto-char (point-max))
                   (list :position (point-marker) :level 1)))
                ((symbol-function 'yes-or-no-p) (lambda (_) t))
                ((symbol-function 'message) #'ignore))
        (supertag-org-capture-after-finalize)))
    (let ((text (move-node-ui-test--disk source)))
      (should (< (string-match "^\\* Second$" text)
                 (string-match "^\\* Root$" text))))))

(provide 'move-node-ui-test)
;;; move-node-ui-test.el ends here

;;; NODE-D retained UI contracts, evaluated before ownership migration.
(ert-deftest move-node-ui-preserves-exact-service-error-payload ()
  (dolist (kind '(supertag-move-recovery-error supertag-projection-error))
    (move-node-ui-test--fixture
      (let* ((snapshots (list (list :buffer source-buffer :text (buffer-string))))
             (payload (list :cause '(error "injected") :snapshots snapshots
                            :retry-function 'supertag-service-org--retry-move-projection
                            :retry-args (list source target))) caught)
        (cl-letf (((symbol-function 'read-file-name) (lambda (&rest _) target))
                  ((symbol-function 'completing-read) (lambda (&rest _) "File End"))
                  ((symbol-function 'yes-or-no-p) (lambda (_) t))
                  ((symbol-function 'supertag-service-org-move-nodes)
                   (lambda (&rest _) (signal kind payload))))
          (condition-case err (call-interactively #'supertag-move-node)
            (error (setq caught err))))
        (should (eq kind (car caught)))
        (should (eq payload (cdr caught)))
        (should (eq snapshots (plist-get (cdr caught) :snapshots)))
        (should (eq source-buffer (current-buffer)))
        (should (= 1 (point)))))))

(ert-deftest move-node-ui-current-position-uses-safe-own-subtree-boundary ()
  (move-node-ui-test--fixture
    (with-current-buffer target-buffer
      (let ((text (buffer-string)))
        (goto-char (point-min)) (search-forward "Body")
        (let ((position (point))
              (expected (save-excursion (org-back-to-heading t) (org-end-of-subtree t t) (point))))
          (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "Current Position")))
            (should (equal (list :position expected :level 1)
                           (supertag-ui-select-insert-position target position)))))
        (should (equal text (buffer-string)))))))

;;; NODE-D independent source-only entry and Capture reachability.
(defconst move-node-ui-test--node-d-root
  (expand-file-name ".." (file-name-directory load-file-name)))
(defun move-node-ui-test--node-d-cold (mode spec available)
  (let* ((tmp (make-temp-file "supertag-node-d-" t))
         (root move-node-ui-test--node-d-root)
         (program (or (getenv "EMACS_BIN") (expand-file-name invocation-name invocation-directory)))
         (deps (split-string (or (getenv "SUPERTAG_DEPS_LOADPATH") "") path-separator t))
         (process-environment (copy-sequence process-environment))
         (script (expand-file-name "cold.el" tmp))
         (body '(progn
  (require 'cl-lib) (require 'ert) (require 'org) (require 'org-capture)
  (setq user-emacs-directory (file-name-as-directory nd-tmp)
        supertag-data-directory (expand-file-name "data/" nd-tmp)
        supertag--base-data-directory supertag-data-directory
        supertag-db-file (expand-file-name "store.el" supertag-data-directory)
        supertag-db-backup-directory (expand-file-name "backups/" nd-tmp)
        supertag-sync-state-file (expand-file-name "sync.el" nd-tmp)
        supertag-sync--state-source supertag-sync-state-file
        supertag-sync-directories (list nd-tmp) supertag-sync-directories-mode 'unified
        org-id-locations-file (expand-file-name "ids" nd-tmp)
        org-id-locations nil org-id-files nil org-id-track-globally nil
        org-mode-hook nil after-init-time nil supertag-view-style-auto-enable nil
        supertag-org-capture-auto-enable nil org-capture-after-finalize-hook nil
        make-backup-files nil auto-save-default nil load-prefer-newer t)
  (defun nd-disk (file) (with-temp-buffer (insert-file-contents file) (buffer-string)))
  (defun nd-owners ()
    (dolist (symbol '(supertag-ui--move-roots-in-region supertag-ui--move-select-target
                      supertag-ui--move-source-context supertag-ui--move-restore-source-context
                      supertag-ui--move supertag-move-node supertag-move-node-and-link
                      supertag-ui--safe-current-insert-position supertag-ui-select-insert-position))
      (unless (equal (symbol-file symbol 'defun) (expand-file-name "supertag-node.el" nd-root))
        (error "NODE-D owner mismatch %S=%S" symbol (symbol-file symbol 'defun))))
    (should (commandp 'supertag-move-node)) (should (commandp 'supertag-move-node-and-link)))
  (if (eq nd-mode 'owner-ui)
      (progn (require 'supertag-query) (require 'supertag-tag) (require 'supertag-services-sync) (supertag-node--prepare-cache-listener t))
    (load (expand-file-name "supertag-node.el" nd-root) nil nil t))
  (when (eq nd-mode 'capture-warm)
     (if (equal (getenv "SUPERTAG_SYA_STAGE") "before")
      (load (expand-file-name "supertag-ui-commands.el" nd-root) nil nil t)
    (require 'supertag-service-org)))
  (princ (format "NODE-D-ENTRY mode=%S spec=%S move=%S commands=%S\n"
                 nd-mode nd-spec (fboundp 'supertag-move-node) (featurep 'supertag-ui-commands)))
  (if (memq nd-mode '(owner-node owner-ui))
      (nd-owners)
    (if (memq nd-mode '(capture-cold capture-warm))
        (progn
          (if (eq nd-mode 'capture-warm)
              (if (equal (getenv "SUPERTAG_SYA_STAGE") "before")
      (should (featurep 'supertag-ui-commands))
    (progn (should (featurep 'supertag-service-org))
                     (should-not (featurep 'supertag-ui-commands))))
            (should-not (featurep 'supertag-ui-commands))
            (should-not (cl-find-if (lambda (row) (and (stringp (car row))
                                                       (equal "supertag-ui-commands" (file-name-base (car row))))) load-history)))
          (should (eq (not (null (fboundp 'supertag-move-node))) nd-available))
          (should (eq (not (null (fboundp 'supertag-move-node-and-link))) nd-available)))
      (nd-owners)
      (should (featurep 'supertag-service-org))
      (dolist (feature '(supertag-services-ui supertag-ui-commands supertag-services-sync supertag-tag supertag-query supertag-services-query supertag-services-note-query supertag-link supertag))
        (should-not (featurep feature))
        (should-not (cl-find-if (lambda (row) (and (stringp (car row))
                                                   (equal (symbol-name feature) (file-name-base (car row))))) load-history)))
      (should-not (autoloadp (symbol-function 'supertag-service-org-move-nodes)))
      (should (equal (symbol-file 'supertag-service-org-move-nodes 'defun)
                     (expand-file-name "supertag-service-org.el" nd-root))))
    (let* ((source (expand-file-name "source.org" nd-tmp))
           (target (expand-file-name "target.org" nd-tmp))
           (capture-p (memq nd-mode '(capture-cold capture-warm)))
           (will-move (and nd-available (not (memq nd-spec '(no-opt nil-move)))))
           (within (eq nd-spec 'within-target))
           (source-text (if capture-p "* Stay\nBody\n" "* Root\n:PROPERTIES:\n:ID: root\n:END:\nBody\n** Child\nChild body\n"))
           (target-text "* Destination\nBody\n")
           (files-prompt 0) (positions-prompt 0) (confirms 0) saves projects)
      (with-temp-file source (insert source-text))
      (with-temp-file target (insert target-text))
      (supertag--ensure-store)
      (unless capture-p
        ;; Isolated projection input for the real identity lookup.  No Sync preload.
        (supertag-store-put-entity :nodes "root" (list :id "root" :file source :title "Root" :level 1 :position 1 :type :node)))
      (cl-labels ((save-observer (orig &rest args)
                    (when (member (buffer-file-name) (list source target)) (push (buffer-file-name) saves))
                    (apply orig args))
                  (project-observer (orig id &rest args)
                    (push (cons id args) projects) (apply orig id args))
                  (provider-observer (_file)
                    (when (and (featurep 'supertag-service-org)
                               (not (advice-member-p #'project-observer 'supertag-service-org-retry-node-projection)))
                      (advice-add 'supertag-service-org-retry-node-projection :around #'project-observer))))
        (unwind-protect
            (progn
              (advice-add 'save-buffer :around #'save-observer)
              (if (featurep 'supertag-service-org)
                  (provider-observer nil)
                (add-hook 'after-load-functions #'provider-observer))
              (cl-letf (((symbol-function 'read-file-name)
                         (lambda (&rest _) (cl-incf files-prompt) target))
                        ((symbol-function 'completing-read)
                         (lambda (prompt &rest _)
                           (should (equal "Insert position: " prompt))
                           (cl-incf positions-prompt) (if within "File Top" "File End")))
                        ((symbol-function 'yes-or-no-p)
                         (lambda (prompt)
                           (should (string-prefix-p "Move " prompt))
                           (should (string-match-p "All unsaved changes" prompt))
                           (cl-incf confirms) t)))
                (if capture-p
                    (let ((org-capture-templates
                           `(("n" "Node" entry (file ,source) "* Captured\nCaptured body\n"
                              :supertag ,(not (eq nd-spec 'no-opt))
                              :supertag-move ,(unless (eq nd-spec 'nil-move) nd-spec)))))
                      (supertag-enable-org-capture-integration)
                      (org-capture nil "n") (should org-capture-mode)
                      (org-capture-finalize))
                  (switch-to-buffer (find-file-noselect source)) (goto-char (point-min))
                  (let ((origin (current-buffer)))
                    (should (equal '("root")
                                   (call-interactively (if (eq nd-spec 'link)
                                                           #'supertag-move-node-and-link #'supertag-move-node))))
                    (should (eq origin (current-buffer))) (should (= 1 (point)))))))
          (remove-hook 'after-load-functions #'provider-observer)
          (advice-remove 'save-buffer #'save-observer)
          (advice-remove 'supertag-service-org-retry-node-projection #'project-observer)))
      (should (= (if will-move 1 0) confirms))
      (should (= (if will-move 1 0) positions-prompt))
      (should (= (if (and will-move (not within)) 1 0) files-prompt))
      (let* ((name (if capture-p "Captured" "Root"))
             (destination (if (and will-move (not within)) target source))
             (text (nd-disk destination)) id)
        (with-temp-buffer
          (insert text) (org-mode) (goto-char (point-min))
          (re-search-forward (concat "^\\* " name "$"))
          (org-back-to-heading t) (setq id (org-entry-get nil "ID")))
        (cond
         ((eq nd-spec 'no-opt) (should-not id))
         ((and capture-p (not will-move))
          ;; Existing bare Capture finalizer projects the new live ID but does
          ;; not save it unless a member writer or requested Move saves later.
          (should-not id)
          (with-current-buffer (find-file-noselect source)
            (goto-char (point-min)) (re-search-forward "^\\* Captured$") (org-back-to-heading t)
            (setq id (org-entry-get nil "ID"))
            (should id) (should (buffer-modified-p))
            (should (equal source (plist-get (supertag-node-get id) :file)))))
         (t (should id) (should (equal destination (plist-get (supertag-node-get id) :file)))))
        (when will-move
          (should (featurep 'supertag-service-org))
          (should-not (autoloadp (symbol-function 'supertag-service-org-move-nodes)))
          (if within
              (should (< (string-match "^\\* Captured$" text) (string-match "^\\* Stay$" text)))
            (should (string-prefix-p target-text text)))
          (when (eq nd-spec 'link)
            (with-current-buffer (find-file-noselect source)
              (goto-char (point-min))
              (when capture-p (re-search-forward "^\\* Captured$") (org-back-to-heading t))
              (should (org-entry-get nil "ID"))
              (should-not (equal id (org-entry-get nil "ID"))))
            (should (string-match-p (regexp-quote (concat "[[id:" id "]")) (nd-disk source)))))
        (unless will-move (should (equal target-text (nd-disk target)))))
      (unless capture-p
        (should (equal (list target source) (reverse saves)))
        (should (= (if (eq nd-spec 'link) 2 1) (length projects)))
        (should-not (featurep 'supertag-ui-commands))
        (should-not (featurep 'supertag-services-ui)))
      (princ (format "NODE-D-BRANCH %S/%S available=%S move=%S prompts=%S saves=%S projects=%S\n"
                     nd-mode nd-spec nd-available will-move (list files-prompt positions-prompt confirms)
                     (length saves) (length projects)))))
  (princ "NODE-D-PASS\n"))))
    (unwind-protect
        (progn
          (with-temp-file script
            (insert ";;; -*- lexical-binding: t; -*-\n")
            (prin1 `(setq nd-root ,root nd-tmp ,tmp nd-mode ',mode nd-spec ',spec nd-available ,available) (current-buffer))
            (insert "\n")
            (let ((print-length nil) (print-level nil))
              (prin1 `(condition-case err
                          (unwind-protect ,body
                            (setq emacs-startup-hook nil kill-emacs-hook nil org-mode-hook nil
                                  org-capture-after-finalize-hook nil enable-theme-functions nil)
                            (mapc #'cancel-timer (append timer-list timer-idle-list)))
                        (error (princ (format "NODE-D-ERROR %S\n" err)) (kill-emacs 1))) (current-buffer))))
          (setenv "HOME" tmp) (setenv "CFFIXED_USER_HOME" tmp)
          (setenv "EMACSLOADPATH" (concat (mapconcat #'identity deps path-separator) path-separator))
          (with-temp-buffer
            (let ((status (apply #'call-process program nil t nil
                                 (append '("-Q" "--batch")
                                         (apply #'append (mapcar (lambda (dir) (list "-L" dir)) deps))
                                         (list "-L" root "-l" script)))))
              (unless (and (equal status 0) (string-match-p "NODE-D-ENTRY" (buffer-string))
                           (string-match-p "NODE-D-PASS" (buffer-string)))
                (ert-fail (format "NODE-D %S/%S exit=%S\n%s" mode spec status (buffer-string))))
              (dolist (line (split-string (buffer-string) "\n" t))
                (when (string-prefix-p "NODE-D-" line) (princ (concat line "\n")))))))
      (delete-directory tmp t))))

(ert-deftest move-node-ui-capture-cold-reachability ()
  (dolist (spec '(within-target link t no-opt nil-move))
    (move-node-ui-test--node-d-cold 'capture-cold spec t)))
(ert-deftest move-node-ui-capture-commands-preloaded-reachability ()
  (dolist (spec '(within-target link t no-opt nil-move))
    (move-node-ui-test--node-d-cold 'capture-warm spec t)))

(ert-deftest move-node-ui-owner-cold-node ()
  (move-node-ui-test--node-d-cold 'owner-node nil nil))
(ert-deftest move-node-ui-owner-cold-ui ()
  (move-node-ui-test--node-d-cold 'owner-ui nil nil))

;;; Added after migration: actual first Node writer/provider execution.
(ert-deftest move-node-ui-node-first-call-real-write ()
  (move-node-ui-test--node-d-cold 'node-write t t))
(ert-deftest move-node-ui-node-first-call-real-write-and-link ()
  (move-node-ui-test--node-d-cold 'node-write 'link t))
