;;; named-link-query-test.el --- Queries over saved named Org links -*- lexical-binding: t; -*-
(require 'add-link-workflow-test)
(require 'supertag-api)
(require 'supertag-query)

(defmacro supertag-named-link-test--vault (&rest body)
  (declare (indent 0))
  `(supertag-add-link-test--isolated
     (let ((supertag-text-link-relation-types '("supports" "opposes")))
       (supertag-text-link-refresh)
       (supertag-tag-create '(:id "x" :name "x"))
       (supertag-tag-create '(:id "source-kind" :name "source-kind"))
       (supertag-add-link-test--write-node (expand-file-name "target.org" tmp) "target" "Target #x")
       (supertag-add-link-test--write-node (expand-file-name "source.org" tmp) "source" "Source #source-kind"
                                         "[[supports:target][First]] [[supports:target][Again]] [[id:target][Ordinary]]")
       (supertag-add-link-test--write-node (expand-file-name "other.org" tmp) "other" "Other"
                                         "[[opposes:target][Different]] [[supports:source][Incoming]]")
       ,@body)))

(ert-deftest supertag-named-link-query-parses-relation-names ()
  (dolist (operator '(link reverse-link))
    (should (equal (list :type operator :reference "supports" :child '(:type tag :value "x"))
                   (supertag-query--parse-sexp (list operator 'supports '(tag "x"))))))
  (dolist (operator '(has-link has-reverse-link))
    (should (equal (list :type operator :reference "supports")
                   (supertag-query--parse-sexp (list operator "supports")))))
  (dolist (query '((link "" (tag "x")) (reverse-link "" (tag "x"))
                   (has-link "") (has-reverse-link "")))
    (should-error (supertag-query--parse-sexp query))))

(ert-deftest supertag-named-link-query-executes-saved-projection ()
  (supertag-named-link-test--vault
    (should (equal '("source") (supertag-query-node-ids '(link "supports" (tag "x")))))
    (should (equal '("other") (supertag-query-node-ids '(link "opposes" (tag "x")))))
    (should (equal '("target") (supertag-query-node-ids '(reverse-link "supports" (tag "source-kind")))))
    (should (equal '("other" "source") (sort (supertag-query-node-ids '(has-link "supports")) #'string<)))
    (should (equal '("source" "target") (sort (supertag-query-node-ids '(has-reverse-link "supports")) #'string<)))
    (should-not (supertag-query-node-ids '(has-link "unknown")))
    (should-not (supertag-query-node-ids '(has-link "id")))
    (should-not (supertag-query-node-ids '(link "id" (tag "x"))))
    (should (equal (supertag-query-node-ids '(link "supports" (tag "x")))
                   (supertag-query-node-ids '(exists-link "supports" (tag "x")))))
    (dolist (query '((link "supports" (tag "x"))
                     (exists-link "supports" (tag "x"))
                     (reverse-link "supports" (tag "source-kind"))
                     (has-link "supports") (has-reverse-link "supports")))
      (should (equal (sort (supertag-query-node-ids query) #'string<)
                     (sort (supertag-query-node-ids
                            (cons (car query) (cons 'supports (cddr query))))
                           #'string<))))
    (should (equal (mapcar (lambda (r) (plist-get r :from))
                          (supertag-query-named-links-to "target" "supports"))
                   (supertag-query-node-ids '(link "supports" (tag "x")))))
    (should (equal (mapcar (lambda (r) (plist-get r :to))
                          (supertag-query-named-links-from "source" "supports"))
                   (supertag-query-node-ids '(reverse-link "supports" (tag "source-kind")))))))

(ert-deftest supertag-named-link-query-api-reads-named-links ()
  (supertag-named-link-test--vault
    (let ((links (plist-get (supertag-api-node "source") :links)))
      (should (= 2 (length links)))
      (should (equal '(:in :out) (sort (mapcar (lambda (link) (plist-get link :direction)) links)
                                    (lambda (a b) (string< (symbol-name a) (symbol-name b))))))
      (dolist (link links)
        (should (equal "supports" (plist-get link :label)))
        (let* ((outgoing (eq :out (plist-get link :direction)))
               (relations (if outgoing
                              (supertag-query-named-links-from "source")
                            (supertag-query-named-links-to "source")))
               (relation-id (plist-get link :relation-id))
               (title (plist-get link :title)))
          (should (and (stringp relation-id) (> (length relation-id) 0)))
          (should (member relation-id (mapcar (lambda (r) (plist-get r :id)) relations)))
          (should (equal (if outgoing "target" "other") (plist-get link :node)))
          (should (and (stringp title) (> (length title) 0))))))
    (dolist (instance (supertag-link-service-instances "source"))
      (should (supertag-relation-named-document-link-p (plist-get instance :relation)))
      (should-not (plist-member instance :definition))
      (should-not (plist-member instance :definition-id)))))

(ert-deftest supertag-named-link-query-retired-surface-absent ()
  (should-not (featurep 'supertag-ops-link-definition))
  (should-not (cl-find "link" (supertag-api-catalog) :test #'equal :key (lambda (entry) (plist-get entry :name))))
  (dolist (symbol '(supertag-api-link supertag-link-create supertag-link-find
                    supertag-relation-create-notion-style supertag-link-definition-get))
    (should-not (fboundp symbol))))

(ert-deftest supertag-named-link-query-library-reads-relation-names ()
  (supertag-named-link-test--vault
    (cl-letf (((symbol-function 'completing-read)
               (lambda (prompt collection _predicate require-match &rest _)
                 (should (equal "Relation name: " prompt))
                 (should (equal '("opposes" "supports") (sort (copy-sequence collection) #'string<)))
                 (should-not require-match)
                 "new-relation")))
      (should (equal "new-relation" (supertag-query-block--read-link-reference))))))

(ert-deftest supertag-named-link-query-library-allows-empty-candidates ()
  (supertag-add-link-test--isolated
    (cl-letf (((symbol-function 'completing-read)
               (lambda (prompt collection _predicate require-match &rest _)
                 (should (equal "Relation name: " prompt))
                 (should-not collection) (should-not require-match) "fresh")))
      (should (equal "fresh" (supertag-query-block--read-link-reference))))))

(provide 'named-link-query-test)
