;;; semantic-test.el --- Isolated semantic candidate contracts -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'document-fixture)
(require 'supertag-semantic)
(require 'supertag-view-node)

(defmacro supertag-semantic-test-with-index (&rest body)
  (declare (indent 0))
  `(supertag-document-test-with-vault
    (let ((supertag-semantic-enabled t)
          (supertag-semantic--vectors (make-hash-table :test 'equal))
          (supertag-semantic--dirty (make-hash-table :test 'equal))
          (supertag-semantic--context nil) (supertag-semantic--dim nil)
          (supertag-semantic--last-enabled nil) (supertag-semantic--last-save 0)
          (supertag-semantic--active nil) (supertag-semantic--process nil)
          (supertag-semantic--timer nil) (supertag-semantic--error nil)
          (supertag-semantic--paused nil) (supertag-semantic--rebuild nil)
          (supertag-semantic--needs-save nil)
          (supertag-semantic--subscription-table nil))
      (unwind-protect
          (cl-letf (((symbol-function 'supertag-semantic--schedule) #'ignore)
                    ((symbol-function 'supertag-semantic--probe) (lambda () t)))
            ,@body)
        (supertag-semantic-stop)))))

(defmacro supertag-semantic-test-with-request (&rest body)
  (declare (indent 0))
  `(let (requests)
     (cl-letf (((symbol-function 'supertag-semantic--request)
                (lambda (texts callback) (push (cons texts callback) requests) nil)))
	      ,@body)))

(defun supertag-semantic-test-complete (request &optional vector)
  (funcall (cdr request) (vconcat (mapcar (lambda (_) (or vector [1.0 0.0])) (car request))) nil))

(defun supertag-semantic-test-seed (id title content &optional refs)
  (supertag-store-put-entity :nodes id
                             (list :id id :title title :content content :level 1
                                   :ref-to refs :file (plist-get (supertag-semantic--node "document-node") :file)) t))

(ert-deftest supertag-semantic-disabled-does-nothing ()
  (supertag-semantic-test-with-index
   (let ((supertag-semantic-enabled nil)
         (store (prin1-to-string supertag--store))
         (subscribers (prin1-to-string supertag--subscribers)))
     (cl-letf (((symbol-function 'supertag-semantic--request) (lambda (&rest _) (ert-fail "Request while disabled"))))
       (with-temp-buffer (supertag-semantic-insert-section "document-node") (should (equal "" (buffer-string))))
       (supertag-semantic--pump)
       (supertag-semantic-status))
     (should-not supertag-semantic--context)
     (should (equal store (prin1-to-string supertag--store)))
     (should (equal subscribers (prin1-to-string supertag--subscribers)))
     (should-not (file-exists-p (supertag-data-file "supertag-semantic.el"))))))

(ert-deftest supertag-semantic-cache-preserves-all-bytes-and-rejects-nonbytes ()
  (supertag-semantic-test-with-index
   (supertag-semantic--ensure)
   (let ((bytes (apply #'unibyte-string (number-sequence 0 255))))
     (setq supertag-semantic--dim 256)
     (puthash "document-node" (cons "hash" bytes) supertag-semantic--vectors)
     (supertag-semantic--save)
     (clrhash supertag-semantic--vectors)
     (supertag-semantic--load)
     (let ((loaded (cdr (gethash "document-node" supertag-semantic--vectors))))
       (should (equal bytes loaded))
       (should-not (multibyte-string-p loaded)))
     (dolist (invalid '("中" "ab"))
       (with-temp-file (car supertag-semantic--context)
         (prin1 (list :version 1 :model supertag-semantic-model :dim 1
                      :entries (list (cons "document-node" (cons "hash" invalid))))
                (current-buffer)))
       (clrhash supertag-semantic--vectors)
       (setq supertag-semantic--dim nil)
       (supertag-semantic--load)
       (should (zerop (hash-table-count supertag-semantic--vectors)))
       (should-not supertag-semantic--dim)))))

(ert-deftest supertag-semantic-index-roundtrip-and-only-dirty-node-refresh ()
  (supertag-semantic-test-with-index
   (supertag-semantic-test-with-request
    (supertag-semantic-test-seed "other" "Other" "Distinct original body.")
    (let ((store (prin1-to-string supertag--store)) (disk (supertag-document-test-disk file)))
      (supertag-semantic--ensure) (supertag-semantic--ensure)
      (should (= 1 (cl-count #'supertag-semantic--changed (gethash :store-changed supertag--subscribers))))
      (supertag-semantic--pump)
      (should (= 2 (length (caar requests))))
      (should (cl-some (lambda (text) (string-match-p "Property Node.*\n.*\nBody" text)) (caar requests)))
      (supertag-semantic-test-complete (car requests))
      (should (= 2 (hash-table-count supertag-semantic--vectors)))
      (should (= 0 (hash-table-count supertag-semantic--dirty)))
      (let ((entry (gethash "document-node" supertag-semantic--vectors)))
        (should-not (multibyte-string-p (cdr entry)))
        (clrhash supertag-semantic--vectors)
        (supertag-semantic--load)
        (should (equal entry (gethash "document-node" supertag-semantic--vectors)))
        (should-not (multibyte-string-p (cdr (gethash "document-node" supertag-semantic--vectors)))))
      (should (equal store (prin1-to-string supertag--store)))
      (should (equal disk (supertag-document-test-disk file))))
    (supertag-semantic-test-seed "other" "Other" "Changed original body.")
    (should (equal '("other") (hash-table-keys supertag-semantic--dirty)))
    (supertag-semantic--pump)
    (should (= 1 (length (caar requests))))
    (should (string-match-p "Changed original body" (caaar requests)))
    (supertag-semantic-test-complete (car requests))
    (supertag-store-remove-entity :nodes "other")
    (should-not (gethash "other" supertag-semantic--vectors))
    (supertag-semantic--pump)
    (clrhash supertag-semantic--vectors) (supertag-semantic--load)
    (should-not (gethash "other" supertag-semantic--vectors)))))

(ert-deftest supertag-semantic-batches-and-rebuilds-on-model-or-dimension-change ()
  (supertag-semantic-test-with-index
   (supertag-semantic-test-with-request
    (supertag-semantic-test-seed "other" "Other" "Body")
    (let ((supertag-semantic-request-chars 1))
      (supertag-semantic--ensure) (supertag-semantic--pump)
      (should (= 1 (length (caar requests))))
      (supertag-semantic--pump) (should (= 1 (length requests)))
      (supertag-semantic-test-complete (car requests))
      (supertag-semantic--pump) (supertag-semantic-test-complete (car requests)))
    (should (= 2 (hash-table-count supertag-semantic--vectors)))
    (let ((supertag-semantic-model "another-model"))
      (supertag-semantic--ensure)
      (should (= 0 (hash-table-count supertag-semantic--vectors)))
      (should (= 2 (hash-table-count supertag-semantic--dirty)))
      (supertag-semantic--pump) (supertag-semantic-test-complete (car requests))
      (supertag-semantic-test-seed "other" "Other" "Changed")
      (supertag-semantic--pump)
      (supertag-semantic-test-complete (car requests) [1.0 0.0 0.0])
      (should (= 3 supertag-semantic--dim))
      (should-not (gethash "document-node" supertag-semantic--vectors))
      (should (gethash "document-node" supertag-semantic--dirty))
      (supertag-semantic--pump) (supertag-semantic-test-complete (car requests) [1.0 0.0 0.0])
      (should (= 2 (hash-table-count supertag-semantic--vectors)))))))

(ert-deftest supertag-semantic-ranking-excludes-links-and-applies-threshold ()
  (supertag-semantic-test-with-index
   (supertag-semantic-test-seed "best" "Best" "Related")
   (supertag-semantic-test-seed "weak" "Weak" "Different")
   (supertag-semantic-test-seed "incoming" "Incoming" "Linked" '("document-node"))
   (supertag-semantic-test-seed "outgoing" "Outgoing" "Linked")
   (supertag-store-put-entity :nodes "document-node"
                              (plist-put (copy-sequence (supertag-semantic--node "document-node")) :ref-to '("outgoing")) t)
   (supertag-semantic--ensure)
   (maphash (lambda (id node)
              (puthash id (cons (supertag-semantic--hash node)
                                (supertag-semantic--quantize (if (equal id "weak") [0.0 1.0] [1.0 0.0])))
                       supertag-semantic--vectors)) (supertag-store-get-collection :nodes))
   (should (equal '("best") (mapcar (lambda (m) (plist-get m :id)) (supertag-semantic--matches "document-node"))))
   (let ((supertag-semantic-min-similarity 0) (supertag-semantic-max-results 1))
     (should (equal '("best") (mapcar (lambda (m) (plist-get m :id)) (supertag-semantic--matches "document-node")))))))

(ert-deftest supertag-semantic-stale-response-and-stale-text-are-not-committed ()
  (supertag-semantic-test-with-index
   (supertag-semantic-test-with-request
    (supertag-semantic--ensure) (supertag-semantic--pump)
    (let ((a (car requests)))
      (supertag-semantic-rebuild) (supertag-semantic--pump)
      (supertag-semantic-test-complete (car requests) [0.0 1.0])
      (let ((before (copy-tree (gethash "document-node" supertag-semantic--vectors))))
        (supertag-semantic-test-complete a [1.0 0.0])
        (should (equal before (gethash "document-node" supertag-semantic--vectors)))))
    (supertag-semantic-test-seed "document-node" "Updated" "first")
    (supertag-semantic--pump)
    (supertag-semantic-test-seed "document-node" "Updated" "second")
    (supertag-semantic-test-complete (car requests))
    (should (gethash "document-node" supertag-semantic--dirty))
    (should-not (equal (car (gethash "document-node" supertag-semantic--vectors))
                       (supertag-semantic--hash (supertag-semantic--node "document-node")))))))

(ert-deftest supertag-semantic-rebuild-offers-session-enable ()
  (supertag-semantic-test-with-index
    (let ((supertag-semantic-enabled nil))
      (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
        (supertag-semantic-rebuild))
      (should supertag-semantic-enabled)
      (should supertag-semantic--rebuild))
    (let ((supertag-semantic-enabled nil))
      (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) nil)))
        (should-error (supertag-semantic-rebuild) :type 'user-error))
      (should-not supertag-semantic-enabled))))

(ert-deftest supertag-semantic-rebuild-probe-failure-preserves-index ()
  (supertag-semantic-test-with-index
    (let ((entry (cons "persisted" (supertag-semantic--quantize [1.0 0.0]))))
      (puthash "document-node" entry supertag-semantic--vectors)
      (cl-letf (((symbol-function 'supertag-semantic--probe)
                 (lambda () (error "Connection refused"))))
        (should-error (supertag-semantic-rebuild) :type 'user-error))
      (should (eq entry (gethash "document-node" supertag-semantic--vectors)))
      (should supertag-semantic-enabled))))

(ert-deftest supertag-semantic-rebuild-reports-batch-progress-and-completion ()
  (supertag-semantic-test-with-index
    (supertag-semantic-test-with-request
      (supertag-semantic-test-seed "extra" "Extra" "Extra body")
      (let ((supertag-semantic-request-chars 1) messages)
        (cl-letf (((symbol-function 'message)
                   (lambda (format-string &rest args)
                     (push (apply #'format format-string args) messages))))
          (supertag-semantic-rebuild)
          (should (= 2 (plist-get supertag-semantic--rebuild :total)))
          (supertag-semantic--pump)
          (supertag-semantic-test-complete (car requests))
          (should (= 1 (plist-get supertag-semantic--rebuild :done)))
          (supertag-semantic--pump)
          (supertag-semantic-test-complete (car requests))
          (should-not supertag-semantic--rebuild)
          (should (cl-some (lambda (line)
                             (string-match-p "Similar notes ready: 2 notes embedded" line))
                           messages)))))))

(ert-deftest supertag-semantic-stop-reports-and-resume-preserves-vectors ()
  (supertag-semantic-test-with-index
    (supertag-semantic-test-with-request
      (supertag-semantic-test-seed "extra" "Extra" "Extra body")
      (let ((supertag-semantic-request-chars 1) messages (scheduled 0))
        (cl-letf (((symbol-function 'message)
                   (lambda (format-string &rest args)
                     (push (apply #'format format-string args) messages)))
                  ((symbol-function 'supertag-semantic--schedule)
                   (lambda () (cl-incf scheduled))))
          (supertag-semantic-rebuild)
          (supertag-semantic--pump)
          (supertag-semantic-test-complete (car requests))
          (let ((entry (gethash "document-node" supertag-semantic--vectors)))
            (should entry)
            (should (= 1 (plist-get supertag-semantic--rebuild :done)))
            (supertag-semantic-stop)
            (should-not supertag-semantic--rebuild)
            (should (cl-some (lambda (line)
                               (string-match-p "Embedding stopped at 1/2 — M-x supertag-semantic-resume to continue"
                                               line))
                             messages))
            (setq scheduled 0)
            (supertag-semantic-resume)
            (should (= 1 scheduled))
            (should (eq entry (gethash "document-node" supertag-semantic--vectors)))
            (should (= 1 (plist-get supertag-semantic--rebuild :total)))))))))

(ert-deftest supertag-semantic-real-view-computing-cards-and-failure-no-retry-storm ()
  (supertag-semantic-test-with-index
   (supertag-semantic-test-with-request
    (supertag-semantic-test-seed "similar" "Similar title" "Original line one.\nOriginal line two.\nThird.\nFourth.")
    (let ((disk (supertag-document-test-disk file))
          (store (prin1-to-string supertag--store))
          (view (with-current-buffer (find-file-noselect file) (supertag-view-node-open "document-node"))))
      (with-current-buffer view (should (string-match-p "Computing…" (buffer-string))))
      (supertag-semantic--pump) (supertag-semantic-test-complete (car requests))
      (with-current-buffer view
        (should (string-match-p " SIMILAR / " (buffer-string)))
        (should (string-match-p "Similar title" (buffer-string)))
        (should (string-match-p "      Original line one" (buffer-string)))
        (should (string-match-p "Fourth" (buffer-string)))
        (should-not (string-match-p "\\[View\\]" (buffer-string)))
        (should-not (string-match-p "\\[Add link\\]" (buffer-string))))
      (should (equal disk (supertag-document-test-disk file)))
      (should (equal store (prin1-to-string supertag--store)))
      (supertag-semantic-rebuild) (supertag-semantic--pump)
      (let ((sidecar (supertag-document-test-disk (supertag-data-file "supertag-semantic.el"))))
        (funcall (cdar requests) nil "Endpoint unavailable")
        (dotimes (_ 3) (supertag-semantic--pump))
        (should (= 2 (length requests)))
        (with-current-buffer view (should (string-match-p "Unavailable: Endpoint unavailable" (buffer-string))))
        (should (equal sidecar (supertag-document-test-disk (supertag-data-file "supertag-semantic.el"))))
        (should (equal disk (supertag-document-test-disk file)))
        (should (equal store (prin1-to-string supertag--store))))))))

(ert-deftest supertag-semantic-section-follows-mention-section ()
  (supertag-semantic-test-with-index
   (supertag-semantic-test-with-request
    (cl-letf (((symbol-function 'supertag-concept-node-p) (lambda (_) t))
              ((symbol-function 'supertag-view-mention-insert-section)
               (lambda (_) (insert "MENTION-SECTION\n"))))
      (let ((view (with-current-buffer (find-file-noselect file) (supertag-view-node-open "document-node"))))
        (with-current-buffer view
          (should (< (string-match "MENTION-SECTION" (buffer-string))
                     (string-match "SIMILAR" (buffer-string))))))))))

(ert-deftest supertag-semantic-cold-endpoint-failure-writes-no-data ()
  (supertag-semantic-test-with-index
   (supertag-semantic-test-with-request
    (let ((disk (supertag-document-test-disk file)) (store (prin1-to-string supertag--store)))
      (supertag-semantic--ensure) (supertag-semantic--pump)
      (funcall (cdar requests) nil "Connection refused")
      (should supertag-semantic--paused)
      (should-not (file-exists-p (supertag-data-file "supertag-semantic.el")))
      (should (equal disk (supertag-document-test-disk file)))
      (should (equal store (prin1-to-string supertag--store)))))))

(ert-deftest supertag-semantic-real-local-endpoint-if-model-present ()
  (skip-unless (executable-find supertag-semantic-curl-program))
  ;; Discover the installed default model using only the local public endpoint.
  (let ((available nil))
    (with-temp-buffer
      (let ((process (make-process :name "semantic-test-tags" :buffer (current-buffer)
                                   :noquery t :sentinel #'ignore
                                   :command (list supertag-semantic-curl-program "--silent" "--fail"
                                                  "--noproxy" "*" "--max-time" "2"
                                                  "http://localhost:11434/api/tags"))))
        (let ((deadline (+ (float-time) 3)))
          (while (and (process-live-p process) (< (float-time) deadline))
            (accept-process-output process 0.05)))
        (when (process-live-p process) (delete-process process))
        (when (= 0 (process-exit-status process))
          (setq available
                (ignore-errors
                  (cl-some (lambda (model) (member (alist-get 'name model) '("bge-m3" "bge-m3:latest")))
                           (alist-get 'models (json-parse-string (buffer-string) :object-type 'alist :array-type 'list))))))))
    (skip-unless available))
  (supertag-semantic-test-with-index
   (let ((supertag-semantic-endpoint "http://localhost:11434")
         (supertag-semantic-model "bge-m3"))
     (supertag-semantic-test-seed "document-node" "咖啡因与睡眠"
                                  "下午喝含咖啡因的饮料会延迟入睡。想改善睡眠，可以减少午后咖啡摄入。")
     (supertag-semantic-test-seed "sleep-zh" "晚间休息与饮品"
                                  "为了更快入睡，下午之后少喝咖啡，避免咖啡因影响夜间休息。")
     (supertag-semantic-test-seed "sleep-en" "Caffeine and rest"
                                  "Avoid coffee in the afternoon to prevent caffeine from delaying sleep at night.")
     (supertag-semantic-test-seed "garden" "番茄浇水"
                                  "番茄在阳光充足的地方生长，需要保持土壤湿润。")
     (supertag-semantic--ensure)
     (supertag-semantic--pump)
     (let ((deadline (+ (float-time) 35)))
       (while (and supertag-semantic--active (< (float-time) deadline))
         (accept-process-output nil 0.05)))
     (should-not supertag-semantic--active)
     (should-not supertag-semantic--error)
     (should (> supertag-semantic--dim 0))
     (should (gethash "document-node" supertag-semantic--vectors))
     (let* ((source (cdr (gethash "document-node" supertag-semantic--vectors)))
            (zh (supertag-semantic--score source (cdr (gethash "sleep-zh" supertag-semantic--vectors))))
            (en (supertag-semantic--score source (cdr (gethash "sleep-en" supertag-semantic--vectors))))
            (other (supertag-semantic--score source (cdr (gethash "garden" supertag-semantic--vectors)))))
       (message "Synthetic bge-m3 quality: Chinese rewrite=%.4f cross-language=%.4f unrelated=%.4f" zh en other)
       (should (> zh other)) (should (> en other)))
     (should (file-exists-p (supertag-data-file "supertag-semantic.el"))))))

(ert-deftest supertag-semantic-input-bounds-and-disabled-subscription ()
  (supertag-semantic-test-with-index
   (let ((supertag-semantic-max-chars 4))
     (should (equal "标题\n父 / 子\n正文前四"
                    (supertag-semantic--text '(:title "标题" :olp ("父" "子") :content "正文前四后面不发")))))
   (supertag-semantic--ensure)
   (clrhash supertag-semantic--dirty)
   (supertag-semantic--changed '(:tags "tag") nil '(:name "Tag"))
   (should (= 0 (hash-table-count supertag-semantic--dirty)))
   (let ((supertag-semantic-enabled nil))
     (supertag-semantic-test-seed "disabled" "No embedding" "New content"))
   (should (= 0 (hash-table-count supertag-semantic--dirty)))))

(ert-deftest supertag-semantic-batch-refreshes-current-view-without-returning-to-old-node ()
  (supertag-semantic-test-with-index
   (supertag-semantic-test-with-request
    (supertag-semantic-test-seed "other" "Other" "Body")
    (let ((view (with-current-buffer (find-file-noselect file) (supertag-view-node-open "document-node"))))
      (supertag-semantic--pump)
      (supertag-view-node-open "other")
      (supertag-semantic-test-complete (car requests))
      (with-current-buffer view
        (should (equal "other" supertag-view-node--current-node-id))
        (should-not (string-match-p "Computing…" (buffer-string))))))))

(ert-deftest supertag-semantic-disabled-response-releases-slot-without-committing ()
  (supertag-semantic-test-with-index
   (supertag-semantic-test-with-request
    (supertag-semantic--ensure) (supertag-semantic--pump)
    (let ((supertag-semantic-enabled nil))
      (supertag-semantic-test-complete (car requests)))
    (should-not supertag-semantic--active)
    (should (= 0 (hash-table-count supertag-semantic--vectors)))
    (should-not (file-exists-p (supertag-data-file "supertag-semantic.el")))
    (supertag-semantic--pump)
    (should (= 2 (length requests)))
    (supertag-semantic-test-complete (car requests))
    (should (gethash "document-node" supertag-semantic--vectors)))))

(ert-deftest supertag-semantic-title-button-visits-original-id ()
  (supertag-semantic-test-with-index
    (supertag-semantic-test-with-request
      (supertag-semantic-test-seed "other" "标题 ]\n下一行" "Original")
      (let ((view (with-current-buffer (find-file-noselect file) (supertag-view-node-open "document-node"))) visited)
        (supertag-semantic--pump) (supertag-semantic-test-complete (car requests))
        (with-current-buffer view
          (goto-char (point-min)) (search-forward "标题 ]")
          (let ((button (button-at (1- (point)))))
            (should button)
            (cl-letf (((symbol-function 'supertag-goto-node) (lambda (id &rest _) (setq visited id))))
              (button-activate button))))
        (should (equal "other" visited))))))

(ert-deftest supertag-semantic-pause-survives-auto-refresh-until-retry-button ()
  (supertag-semantic-test-with-index
    (supertag-semantic-test-with-request
      (let ((view (with-current-buffer (find-file-noselect file) (supertag-view-node-open "document-node"))))
        (supertag-semantic--pump) (funcall (cdar requests) nil "Offline")
        (supertag-semantic-test-seed "unrelated" "New" "Unrelated")
        (with-current-buffer view (supertag-view-node--refresh-view))
        (supertag-semantic--pump)
        (should (= 1 (length requests)))
        (should supertag-semantic--paused)
        (with-current-buffer view
          (goto-char (point-min)) (search-forward "[Retry]")
          (button-activate (button-at (1- (point)))))
        (supertag-semantic--pump) (should (= 2 (length requests)))
        (supertag-semantic-stop)
        (with-current-buffer view (supertag-view-node--refresh-view))
        (supertag-semantic--pump) (should (= 2 (length requests)))))))

(ert-deftest supertag-semantic-reenable-reconciles-disabled-changes-once ()
  (supertag-semantic-test-with-index
    (supertag-semantic-test-with-request
      (supertag-semantic-test-seed "modified" "Old" "Old")
      (supertag-semantic-test-seed "deleted" "Delete" "Old")
      (let ((view (with-current-buffer (find-file-noselect file) (supertag-view-node-open "document-node"))))
        (supertag-semantic--pump) (supertag-semantic-test-complete (car requests))
        (let ((disk (supertag-document-test-disk (supertag-data-file "supertag-semantic.el")))
              (supertag-semantic-enabled nil))
          (supertag-semantic-test-seed "modified" "Modified" "Changed")
          (supertag-semantic-test-seed "added" "Added" "New")
          (supertag-store-remove-entity :nodes "deleted")
          (with-current-buffer view (supertag-view-node--refresh-view))
          (should (equal disk (supertag-document-test-disk (supertag-data-file "supertag-semantic.el")))))
        (with-current-buffer view (supertag-view-node--refresh-view))
        (should-not (gethash "deleted" supertag-semantic--vectors))
        (supertag-semantic--pump)
        (should (= 2 (length (caar requests))))
        (should (cl-every (lambda (text) (string-match-p "Modified\\|Added" text)) (caar requests)))
        (cl-letf (((symbol-function 'supertag-semantic--scan) (lambda () (ert-fail "Repeated full scan"))))
          (with-current-buffer view (supertag-view-node--refresh-view)))))))

(ert-deftest supertag-semantic-intermediate-batches-preserve-reading-and-coalesce-save ()
  (supertag-semantic-test-with-index
    (supertag-semantic-test-with-request
      (supertag-semantic-test-seed "y-other" "Second" "Second")
      (supertag-semantic-test-seed "z-other" "Third" "Third")
      (supertag-semantic-test-seed "existing" "Existing" "Already indexed reading body.")
      (supertag-semantic--ensure)
      (puthash "existing"
               (cons (supertag-semantic--hash (supertag-semantic--node "existing"))
                     (supertag-semantic--quantize [1.0 0.0]))
               supertag-semantic--vectors)
      (remhash "existing" supertag-semantic--dirty)
      (let ((supertag-semantic-request-chars 1)
            (saves 0) (refreshes 0)
            (writer (symbol-function 'supertag-semantic--save))
            (renderer (symbol-function 'supertag-view-node--refresh-view))
            (view (with-current-buffer (find-file-noselect file) (supertag-view-node-open "document-node"))))
        (cl-letf (((symbol-function 'supertag-semantic--save)
                   (lambda () (cl-incf saves) (funcall writer)))
                  ((symbol-function 'supertag-view-node--refresh-view)
                   (lambda () (cl-incf refreshes) (funcall renderer))))
          (supertag-semantic--pump) (supertag-semantic-test-complete (car requests))
          (should (= 0 saves))
          (with-current-buffer view
            (goto-char (point-min)) (search-forward "Already indexed reading body."))
          (let ((position (with-current-buffer view (point)))
                (start (window-start (get-buffer-window view t)))
                (before refreshes))
            (supertag-semantic--pump) (supertag-semantic-test-complete (car requests))
            (should (= before refreshes)) (should (= 0 saves))
            (should (= position (with-current-buffer view (point))))
            (supertag-semantic--pump) (supertag-semantic-test-complete (car requests))
            (should (= 1 saves)) (should (= (1+ before) refreshes))
            (should (= position (with-current-buffer view (point))))
            (should (= start (window-start (get-buffer-window view t))))))))))

(defvar supertag-semantic-request-timeout)

(defun supertag-semantic-test--dispose-request (options)
  "Clean temporary artifacts if a request assertion fails before its sentinel."
  (when options
    (let ((input (substring (cadr (member "--data-binary" (plist-get options :command))) 1)))
      (when (file-exists-p input) (delete-file input))))
  (dolist (key '(:buffer :stderr))
    (when (buffer-live-p (plist-get options key))
      (kill-buffer (plist-get options key)))))

(ert-deftest supertag-semantic-request-timeout-is-passed-to-curl ()
  (supertag-semantic-test-with-index
    (let ((supertag-semantic-request-timeout 7.5) options failure)
      (unwind-protect
          (cl-letf (((symbol-function 'make-process)
                     (lambda (&rest args) (setq options args) nil)))
            (supertag-semantic--request '("Body") (lambda (_vectors error) (setq failure error)))
            (let ((input (substring (cadr (member "--data-binary" (plist-get options :command))) 1)))
              (should (file-exists-p input))
              (cl-letf (((symbol-function 'process-status) (lambda (_) 'exit))
                        ((symbol-function 'process-exit-status) (lambda (_) 28)))
                (funcall (plist-get options :sentinel) nil "exited 28"))
              (should-not (file-exists-p input)))
            (should (equal "7.5" (cadr (member "--max-time" (plist-get options :command)))))
            (should (equal "Request timed out after 7.5 s" failure))
            (should (= 30 (eval (car (get 'supertag-semantic-request-timeout 'standard-value)) t))))
        (supertag-semantic-test--dispose-request options)))))

(ert-deftest supertag-semantic-timeout-sentinel-uses-submitted-setting-and-retry ()
  (let ((scheduler (symbol-function 'supertag-semantic--schedule)))
    (supertag-semantic-test-with-index
      (let ((supertag-semantic-request-timeout 7) options)
        (unwind-protect
            (cl-letf (((symbol-function 'make-process)
                       (lambda (&rest args) (setq options args) nil))
                      ((symbol-function 'supertag-semantic--schedule) scheduler)
                      ((symbol-function 'run-with-idle-timer) (lambda (&rest _) (timer-create))))
              (let* ((disk (supertag-document-test-disk file))
                     (store (prin1-to-string supertag--store))
                     (view (with-current-buffer (find-file-noselect file)
                             (supertag-view-node-open "document-node"))))
                (supertag-semantic--pump)
                (should supertag-semantic--active)
                (with-current-buffer (plist-get options :stderr) (insert "curl: operation timed out"))
                ;; Change the option after submitting; the sentinel must retain 7.
                (setq supertag-semantic-request-timeout 99)
                (cl-letf (((symbol-function 'process-status) (lambda (_) 'exit))
                          ((symbol-function 'process-exit-status) (lambda (_) 28)))
                  (funcall (plist-get options :sentinel) nil "exited 28"))
                (should-not (buffer-live-p (plist-get options :buffer)))
                (should-not (buffer-live-p (plist-get options :stderr)))
                (should-not supertag-semantic--active)
                (should supertag-semantic--paused)
                (should (equal "Request timed out after 7 s" supertag-semantic--error))
                (should-not (file-exists-p (supertag-data-file "supertag-semantic.el")))
                (with-current-buffer view
                  (should (string-match-p "Unavailable: Request timed out after 7 s" (buffer-string)))
                  (goto-char (point-min)) (search-forward "[Retry]")
                  (button-activate (button-at (1- (point)))))
                (should-not supertag-semantic--error)
                (should-not supertag-semantic--paused)
                (should (timerp supertag-semantic--timer))
                (should (gethash "document-node" supertag-semantic--dirty))
                (should (equal disk (supertag-document-test-disk file)))
                (should (equal store (prin1-to-string supertag--store)))))
          (supertag-semantic-test--dispose-request options))))))

(defun supertag-semantic-test--blocked-render (error-state)
  "Render an existing view while paused or in ERROR-STATE, without adding work."
  (supertag-semantic-test-with-index
    (let ((view (with-current-buffer (find-file-noselect file)
                  (supertag-view-node-open "document-node")))
          (queue (symbol-function 'supertag-semantic--queue))
          (schedule (symbol-function 'supertag-semantic--schedule)))
      (setq supertag-semantic--paused (not error-state)
            supertag-semantic--error (and error-state "Offline"))
      (clrhash supertag-semantic--dirty)
      (puthash "already-dirty" t supertag-semantic--dirty)
      (dotimes (cold 2)
        (when (= cold 1) (setq supertag-semantic--last-enabled nil))
        (let ((queued 0) (scheduled 0)
              (disk (supertag-document-test-disk file))
              (store (prin1-to-string supertag--store)))
          (cl-letf (((symbol-function 'supertag-semantic--queue)
                     (lambda (id) (cl-incf queued) (funcall queue id)))
                    ((symbol-function 'supertag-semantic--schedule)
                     (lambda () (cl-incf scheduled) (funcall schedule))))
            (with-current-buffer view
              (supertag-view-node--refresh-view)
              (should (string-match-p (if error-state "Unavailable: Offline" "Paused\\.")
                                      (buffer-string)))
              (should (string-match-p "\\[Retry\\]" (buffer-string)))))
          (should (= 0 queued))
          (should (= 0 scheduled))
          (should (equal '("already-dirty") (hash-table-keys supertag-semantic--dirty)))
          (should (eq t (gethash "already-dirty" supertag-semantic--dirty)))
          (should (equal disk (supertag-document-test-disk file)))
          (should (equal store (prin1-to-string supertag--store))))))))

(ert-deftest supertag-semantic-paused-render-does-not-queue-or-schedule ()
  (supertag-semantic-test--blocked-render nil))

(ert-deftest supertag-semantic-error-render-does-not-queue-or-schedule ()
  (supertag-semantic-test--blocked-render t))

(ert-deftest supertag-semantic-computing-stop-button-and-retry-preserve-generation ()
  (let ((scheduler (symbol-function 'supertag-semantic--schedule)))
    (supertag-semantic-test-with-index
      (supertag-semantic-test-with-request
        (cl-letf (((symbol-function 'supertag-semantic--schedule) scheduler)
                  ((symbol-function 'run-with-idle-timer) (lambda (&rest _) (timer-create))))
          (let ((disk (supertag-document-test-disk file))
                (store (prin1-to-string supertag--store))
                (view (with-current-buffer (find-file-noselect file)
                        (supertag-view-node-open "document-node"))))
            (supertag-semantic--pump)
            (let ((old (car requests))
                  (dirty (hash-table-keys supertag-semantic--dirty)))
              (should supertag-semantic--active)
              (with-current-buffer view
                (should (string-match-p "Computing…" (buffer-string)))
                (goto-char (point-min)) (search-forward "[Stop]")
                (let ((button (button-at (1- (point)))))
                  (should button)
                  (button-activate button)))
              (should supertag-semantic--paused)
              (should-not supertag-semantic--active)
              (should-not supertag-semantic--process)
              (should-not supertag-semantic--timer)
              (should (equal dirty (hash-table-keys supertag-semantic--dirty)))
              (with-current-buffer view
                (should (equal "document-node" supertag-view-node--current-node-id))
                (should (string-match-p "Paused\\." (buffer-string))))
              (supertag-semantic-test-complete old)
              (should supertag-semantic--paused)
              (should (= 0 (hash-table-count supertag-semantic--vectors)))
              (should (= 1 (length requests)))
              (should-not (file-exists-p (supertag-data-file "supertag-semantic.el")))
              (with-current-buffer view
                (goto-char (point-min)) (search-forward "[Retry]")
                (button-activate (button-at (1- (point)))))
              (should-not supertag-semantic--paused)
              (should (timerp supertag-semantic--timer))
              (supertag-semantic--pump)
              (should (= 2 (length requests)))
              (let ((active supertag-semantic--active))
                (supertag-semantic-test-complete old)
                (should (eq active supertag-semantic--active))
                (should (= 0 (hash-table-count supertag-semantic--vectors))))
              (supertag-semantic-test-complete (car requests))
              (should (= 1 (hash-table-count supertag-semantic--vectors)))
              (should-not supertag-semantic--active)
              (should (equal disk (supertag-document-test-disk file)))
              (should (equal store (prin1-to-string supertag--store))))))))))

(defun supertag-semantic-test--observe-blocked-context ()
  "Render production section and require context observation without work creation."
  (let ((scan (symbol-function 'supertag-semantic--scan))
        (queue (symbol-function 'supertag-semantic--queue))
        (schedule (symbol-function 'supertag-semantic--schedule))
        (scanned 0) (queued 0) (scheduled 0))
    (cl-letf (((symbol-function 'supertag-semantic--scan)
               (lambda () (cl-incf scanned) (funcall scan)))
              ((symbol-function 'supertag-semantic--queue)
               (lambda (id) (cl-incf queued) (funcall queue id)))
              ((symbol-function 'supertag-semantic--schedule)
               (lambda () (cl-incf scheduled) (funcall schedule))))
      (with-temp-buffer
        (supertag-semantic-insert-section "document-node")
        (should (string-match-p "\\[Retry\\]" (buffer-string)))))
    (should (= 0 scanned))
    (should (= 0 queued))
    (should (= 0 scheduled))
    (should (equal supertag-semantic--context (supertag-semantic--current-context)))
    (should-not supertag-semantic--last-enabled)))

(defun supertag-semantic-test--blocked-context-roundtrip (dimension error-state)
  "Observe A/B/A for model or directory DIMENSION while stopped or in ERROR-STATE.
This exercises the context seam with real Store events, not vault activation."
  (supertag-semantic-test-with-index
    (supertag-semantic-test-with-request
      (let ((supertag-semantic-model "model-A")
            (directory-b (expand-file-name "context-B/" tmp)))
        (supertag-semantic-test-seed "other" "Other" "old body")
        (supertag-semantic--ensure)
        (supertag-semantic--pump)
        (supertag-semantic-test-complete (car requests))
        (should (= 2 (hash-table-count supertag-semantic--vectors)))
        (should (= 0 (hash-table-count supertag-semantic--dirty)))
        (if error-state
            (progn
              (supertag-semantic-test-seed "document-node" "Property Node" "changed source")
              (supertag-semantic--pump)
              (funcall (cdar requests) nil "Offline")
              (should (equal "Offline" supertag-semantic--error)))
          (supertag-semantic-stop))
        (should supertag-semantic--paused)
        (let ((old (car requests))
              (request-count (length requests))
              (disk (supertag-document-test-disk file))
              (sidecar (supertag-document-test-disk (car supertag-semantic--context))))
          (let ((supertag-semantic-model (if (eq dimension 'model) "model-B" supertag-semantic-model))
                (supertag-data-directory (if (eq dimension 'directory) directory-b supertag-data-directory)))
            (supertag-semantic-test--observe-blocked-context)
            (should-not supertag-semantic--active)
            (should (= 0 (hash-table-count supertag-semantic--vectors)))
            ;; Old dirty belongs to A; dropping it is context invalidation.
            (should (= 0 (hash-table-count supertag-semantic--dirty)))
            (supertag-semantic-test-seed "other" "Other" "changed body in B"))
          (supertag-semantic-test--observe-blocked-context)
          (should supertag-semantic--paused)
          (when error-state (should (equal "Offline" supertag-semantic--error)))
          (should (= request-count (length requests)))
          (should (equal sidecar (supertag-document-test-disk (car supertag-semantic--context))))
          (should-not (file-exists-p (expand-file-name "supertag-semantic.el" directory-b)))
          (let ((store (prin1-to-string supertag--store)))
            (supertag-semantic--retry "document-node")
            (should-not supertag-semantic--paused)
            (should-not supertag-semantic--error)
            (should supertag-semantic--last-enabled)
            (should (gethash "other" supertag-semantic--dirty))
            (supertag-semantic--pump)
            (should (= (1+ request-count) (length requests)))
            (should (cl-some (lambda (text) (string-match-p "changed body in B" text))
                             (caar requests)))
            (let ((active supertag-semantic--active))
              (supertag-semantic-test-complete old)
              (should (eq active supertag-semantic--active)))
            (supertag-semantic-test-complete (car requests))
            (should (equal (car (gethash "other" supertag-semantic--vectors))
                           (supertag-semantic--hash (supertag-semantic--node "other"))))
            (should (= 2 (hash-table-count supertag-semantic--vectors)))
            (should-not (gethash "other" supertag-semantic--dirty))
            (should (equal disk (supertag-document-test-disk file)))
            (should (equal store (prin1-to-string supertag--store)))))))))

(ert-deftest supertag-semantic-paused-model-roundtrip-reconciles-store-events ()
  (supertag-semantic-test--blocked-context-roundtrip 'model nil))

(ert-deftest supertag-semantic-error-model-roundtrip-reconciles-store-events ()
  (supertag-semantic-test--blocked-context-roundtrip 'model t))

(ert-deftest supertag-semantic-paused-directory-roundtrip-reconciles-store-events ()
  (supertag-semantic-test--blocked-context-roundtrip 'directory nil))

(ert-deftest supertag-semantic-error-directory-roundtrip-reconciles-store-events ()
  (supertag-semantic-test--blocked-context-roundtrip 'directory t))

(ert-deftest supertag-semantic-deferred-context-rebuild-and-disable-lifecycle ()
  (supertag-semantic-test-with-index
    (supertag-semantic-test-with-request
      (supertag-semantic--ensure)
      (supertag-semantic--pump)
      (supertag-semantic-test-complete (car requests))
      (supertag-semantic-stop)
      (let ((supertag-semantic-model "deferred-model"))
        (supertag-semantic-test--observe-blocked-context)
        (let ((supertag-semantic-enabled nil))
          (supertag-semantic--ensure)
          (should-not supertag-semantic--last-enabled))
        ;; Re-enable while still paused cannot claim that reconciliation ran.
        (supertag-semantic-test--observe-blocked-context)
        (supertag-semantic-rebuild)
        (should-not supertag-semantic--paused)
        (should-not supertag-semantic--error)
        (should supertag-semantic--last-enabled)
        (should (gethash "document-node" supertag-semantic--dirty))
        (cl-letf (((symbol-function 'supertag-semantic--scan)
                   (lambda () (ert-fail "Rebuild reconciliation repeated"))))
          (with-temp-buffer (supertag-semantic-insert-section "document-node")))
        (supertag-semantic--pump)
        (supertag-semantic-test-complete (car requests))
        (should (gethash "document-node" supertag-semantic--vectors))))))

(ert-deftest supertag-semantic-passages-lexical-contract ()
  (should (equal (supertag-semantic--passages "\n:PROPERTIES:\n:X: hidden\n:END:\n\nFirst\nsecond\n:LOGBOOK:\nhidden\n:END:\nLast\n") '("First\nsecond" "Last")))
  (should-not (supertag-semantic--passages ":LOGBOOK:\nsecret\n:END:\n"))
  (dolist (case '(("中文学习" ("别的内容" "中文学习方法") "中文学习方法")
                  ("APPLE trees" ("water" "apple trees grow") "apple trees grow")
                  ("中文 apple" ("nothing" "中文 apple") "中文 apple")
                  ("unknown" ("first" "second") "first")
                  ("apple" ("apple one" "apple two") "apple one")))
    (should (equal (car (supertag-semantic--closest-passage (car case) (cadr case))) (caddr case))))
  (should (= 0 (cdr (supertag-semantic--closest-passage "甲\n\n乙" '("甲乙")))))
  (should-not (car (supertag-semantic--closest-passage "x" nil))))

(ert-deftest supertag-semantic-public-passage-preview-and-own-body-navigation ()
  (supertag-semantic-test-with-index
   (supertag-semantic-test-with-request
    (with-temp-file file
      (insert "* Query\n:PROPERTIES:\n:ID: document-node\n:END:\nOrange orchard harvest. Second preview line Third preview line Fourth hidden line\n\n* Candidate\n:PROPERTIES:\n:ID: candidate\n:END:\nUnrelated first paragraph.\n\n:LOGBOOK:\nOrange orchard harvest.\n:END:\n\nOrange orchard harvest.\nSecond preview line\nThird preview line\nFourth hidden line\n\nOrange orchard harvest.\nSecond preview line\nThird preview line\nFourth hidden line\n\n** Child\n:PROPERTIES:\n:ID: child\n:END:\nOrange orchard harvest.\n* Neighbor\n:PROPERTIES:\n:ID: neighbor\n:END:\nOrange orchard harvest.\n* Fallback\n:PROPERTIES:\n:ID: fallback\n:END:\nDistant vocabulary.\n\nOther paragraph.\n* Empty\n:PROPERTIES:\n:ID: empty\n:END:\n:LOGBOOK:\nOnly metadata\n:END:\n"))
    (supertag-reindex-org)
    (supertag-semantic--ensure)
    (supertag-semantic--pump)
    (supertag-semantic-test-complete (car requests))
    (let ((disk (supertag-document-test-disk file))
          (store (prin1-to-string supertag--store)) button fallback-button empty-button)
      (unwind-protect
          (progn
            (supertag-view-node-open "document-node")
            (with-current-buffer (supertag-view-node--buffer)
              (goto-char (point-min))
              (should (search-forward "Candidate" nil t))
              (setq button (button-at (1- (point))))
              (should (equal "candidate" (get-text-property (1- (point)) 'supertag-node-id)))
              (should (search-forward "      Orange orchard harvest." nil t))
              (should (search-forward "Second preview line Third preview line" nil t))
              (should (search-forward "Fourth hidden line" nil t))
              (goto-char (point-min))
              (should (search-forward "Fallback" nil t))
              (setq fallback-button (button-at (1- (point))))
              (should (search-forward "      Distant vocabulary." nil t))
              (goto-char (point-min))
              (should (search-forward "Empty" nil t))
              (setq empty-button (button-at (1- (point)))))
            (button-activate fallback-button)
            (should (org-at-heading-p))
            (should (equal "fallback" (org-entry-get nil "ID")))
            (button-activate empty-button)
            (should (org-at-heading-p))
            (should (equal "empty" (org-entry-get nil "ID")))
            (button-activate button)
            (should (derived-mode-p 'org-mode))
            (should (looking-at "Orange orchard harvest\\."))
            (should-not (org-in-regexp org-drawer-regexp))
            (let ((expected (save-excursion
                              (goto-char (point-min))
                              (search-forward ":ID: candidate")
                              (search-forward ":LOGBOOK:")
                              (search-forward ":END:")
                              (search-forward "Orange orchard harvest.")
                              (line-beginning-position))))
              (should (= expected (point))))
            (should (equal disk (supertag-document-test-disk file)))
            (should (equal store (prin1-to-string supertag--store)))
            (should-not (buffer-modified-p))
            ;; Remove all own-body matches but leave the drawer, child and sibling.
            (let ((start (point))
                  (end (save-excursion (re-search-forward org-heading-regexp) (line-beginning-position))))
              (delete-region start end))
            (let ((live (buffer-string)))
              (button-activate button)
              (should (org-at-heading-p))
              (should (equal "candidate" (org-entry-get nil "ID")))
              (should (equal live (buffer-string)))
              (should (equal disk (supertag-document-test-disk file)))
              (should (equal store (prin1-to-string supertag--store)))))
        (when (buffer-live-p (supertag-view-node--buffer))
          (kill-buffer (supertag-view-node--buffer))))))))

(ert-deftest supertag-semantic-unclosed-and-lone-drawer-markers-are-body ()
  (dolist (text '(":NOTE:\nLegitimate orchard prose.\n\nMore prose.\n"
                  ":END:\nLegitimate orchard prose.\n\nMore prose.\n"))
    (should (equal (supertag-semantic--passages text)
                   (list (string-trim-right (car (split-string text "\n\n"))) "More prose."))))
  (should (equal (supertag-semantic--passages
                  "Before.\n\n:LOGBOOK:\nHidden orchard prose.\n:END:\n\nAfter.")
                 '("Before." "After."))))

(ert-deftest supertag-semantic-block-drawer-literals-preserve-original-text ()
  (dolist (kind '("src text" "example"))
    (let ((block (format "#+begin_%s\n:LOGBOOK:\nExample orchard code\n:END:\n#+end_%s"
                         kind (car (split-string kind)))))
      (should (equal (supertag-semantic--passages (concat block "\n\nAfter.\n"))
                     (list block "After."))))))

(ert-deftest supertag-semantic-public-literal-paragraphs-preview-and-locate ()
  (dolist (body '(":NOTE:\nOrchard needle body.\n\nLater legitimate prose."
                  ":END:\nOrchard needle body."
                  "#+begin_src text\n\n:LOGBOOK:\nOrchard needle body.\n:END:\n\n#+end_src"
                  "#+begin_example\n\n:LOGBOOK:\nOrchard needle body.\n:END:\n\n#+end_example"))
    (supertag-semantic-test-with-index
     (supertag-semantic-test-with-request
      (with-temp-file file
        (insert "* Query\n:PROPERTIES:\n:ID: document-node\n:END:\nOrchard needle body.\n\n* Candidate\n:PROPERTIES:\n:ID: candidate\n:END:\n"
                body
                "\n** Child\n:PROPERTIES:\n:ID: child\n:END:\nOrchard needle body.\n* Neighbor\n:PROPERTIES:\n:ID: neighbor\n:END:\nOrchard needle body.\n"))
      (supertag-reindex-org)
      (supertag-semantic--ensure)
      (supertag-semantic--pump)
      (supertag-semantic-test-complete (car requests))
      (let ((disk (supertag-document-test-disk file))
            (store (prin1-to-string supertag--store)) button)
        (unwind-protect
            (progn
              (supertag-view-node-open "document-node")
              (with-current-buffer (supertag-view-node--buffer)
                (goto-char (point-min))
                  (should (search-forward "Candidate" nil t))
                (setq button (button-at (1- (point))))
                (should (search-forward "      Orchard needle body." nil t)))
              (with-current-buffer (find-file-noselect file)
                (goto-char (point-min))
                (search-forward ":ID: candidate")
                (org-back-to-heading t)
                (org-fold-hide-subtree))
              (button-activate button)
              (should (derived-mode-p 'org-mode))
              (should (looking-at ":\\(?:NOTE\\|END\\|LOGBOOK\\):"))
              (should-not (org-invisible-p (point)))
              (should (equal "candidate" (org-entry-get nil "ID")))
              (should (equal disk (buffer-string)))
              (should-not (buffer-modified-p))
              (should (equal disk (supertag-document-test-disk file)))
              (should (equal store (prin1-to-string supertag--store)))
              ;; Unclosed NOTE must not swallow the later paragraph either.
              (when (string-prefix-p ":NOTE:" body)
                (supertag-semantic--visit-passage "candidate" "Later legitimate prose.")
                (should (looking-at "Later legitimate prose\\.")))
              ;; The same text exists beyond the own-body bound, but must not match.
              (supertag-semantic--visit-passage "candidate" "* Neighbor")
              (should (org-at-heading-p))
              (should (equal "candidate" (org-entry-get nil "ID"))))
          (when (buffer-live-p (supertag-view-node--buffer))
            (kill-buffer (supertag-view-node--buffer)))))))))
