;;; tag-rename-delete-test.el --- Org-first tag changes -*- lexical-binding: t; -*-
(require 'document-fixture)
(if (equal (getenv "SUPERTAG_SYA_STAGE") "before")
      (require 'supertag-ui-commands)
    (require 'supertag-tag))

(defmacro supertag-tag-change-test--vault (&rest body)
  (declare (indent 0))
  `(supertag-document-test-with-vault
     (supertag-tag-create '(:id "old" :name "old" :aliases ("alias" "emacs/package")))
     (dolist (pair (list
                   (cons file ":PROPERTIES:\n:ID: file-node\n:END:\n#+TITLE: File\n#+FILETAGS: :old:\nFile body\n")
                   (cons plain "* Alias #alias\n:PROPERTIES:\n:ID: alias-node\n:END:\nAlias body\n* Path #emacs/package\n:PROPERTIES:\n:ID: path-node\n:END:\nPath body\n")))
       (with-current-buffer (find-file-noselect (car pair))
         (erase-buffer) (insert (cdr pair)) (save-buffer)))
     (should (eq 'complete (plist-get (supertag-reindex-org) :status)))
     (should (= 3 (length (supertag-find-nodes-by-tag "old"))))
     (unwind-protect (progn ,@body)
       (when (get-buffer "*Supertag Tag Change*") (kill-buffer "*Supertag Tag Change*")))))

(defun supertag-tag-change-test--snapshot (files)
  (list (mapcar (lambda (file)
                  (with-current-buffer (find-file-noselect file)
                    (list (supertag-document-test-disk file) (buffer-string) (buffer-modified-p))))
                files)
        (prin1-to-string supertag--store)))

(ert-deftest supertag-tag-change-preview-is-zero-write ()
  (supertag-tag-change-test--vault
    (with-current-buffer (find-file-noselect plain)
      (goto-char (point-min)) (search-forward " #alias") (replace-match "")
      (search-forward "Alias body") (replace-match "Alias body #alias")
      (goto-char (point-max)) (insert "Draft"))
    (let* ((before (supertag-tag-change-test--snapshot (list file plain)))
           (report (supertag-tag-change-preview "old" "new")))
      (should (= 2 (length report)))
      (should (= 3 (apply #'+ (mapcar (lambda (group) (length (cadr group))) report))))
      (with-current-buffer "*Supertag Tag Change*"
        (should (derived-mode-p 'special-mode))
        (should (string-match-p "3 个 token / 3 节点 / 2 文件" (buffer-string)))
        (should (string-match-p "待保存/待投影 0" (buffer-string)))
        (should (string-match-p "emacs/package" (buffer-string)))
        (should (string-match-p "Alias body #alias" (buffer-string))))
      (should (equal before (supertag-tag-change-test--snapshot (list file plain)))))))

(ert-deftest supertag-tag-change-rename-confirmed ()
  (supertag-tag-change-test--vault
    (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "new"))
              ((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
      (supertag-tag-rename "old"))
    (let ((new (supertag-tag-resolve-occurrence "new")))
      (should (supertag-tag-get new))
      (should-not (supertag-tag-get "old"))
      (dolist (id '("file-node" "alias-node" "path-node"))
        (should (equal (list new) (plist-get (supertag-node-get id) :tags))))
    (dolist (path (list file plain))
      (with-current-buffer (find-file-noselect path)
        (should-not (buffer-modified-p))
        (should (equal (buffer-string) (supertag-document-test-disk path)))
        (should-not (string-match-p "#alias\\|#emacs/package\\|:old:" (buffer-string)))
        (should (string-match-p "new" (buffer-string))))))))

(ert-deftest supertag-tag-change-delete-confirmed ()
  (supertag-tag-change-test--vault
    (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
      (supertag-delete-tag-everywhere "old"))
    (should-not (supertag-tag-get "old"))
    (dolist (id '("file-node" "alias-node" "path-node"))
      (should-not (plist-get (supertag-node-get id) :tags)))
    (dolist (path (list file plain))
      (with-current-buffer (find-file-noselect path)
        (should-not (buffer-modified-p))
        (should (equal (buffer-string) (supertag-document-test-disk path)))
        (should-not (string-match-p "#alias\\|#emacs/package\\|:old:" (buffer-string)))
        (should (string-match-p "body" (buffer-string)))))))

(ert-deftest supertag-tag-change-cancel-is-zero-write ()
  (supertag-tag-change-test--vault
    (let ((before (supertag-tag-change-test--snapshot (list file plain))))
      (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "new"))
                ((symbol-function 'yes-or-no-p) (lambda (&rest _) nil)))
        (should-not (supertag-tag-rename "old"))
        (should (equal before (supertag-tag-change-test--snapshot (list file plain))))
        (should-not (supertag-delete-tag-everywhere "old"))
        (should (equal before (supertag-tag-change-test--snapshot (list file plain))))))))

(ert-deftest supertag-tag-change-merge-previews-canonical-target ()
  (supertag-tag-change-test--vault
    (supertag-tag-create '(:id "other" :name "Canonical" :aliases ("destination")))
    (let ((before (supertag-tag-change-test--snapshot (list file plain))) prompt)
      (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "destination"))
                ((symbol-function 'yes-or-no-p) (lambda (text) (setq prompt text) nil)))
        (should-not (supertag-tag-rename "old")))
      (dolist (part '("Merge" "other" "Canonical")) (should (string-match-p part prompt)))
      (with-current-buffer "*Supertag Tag Change*"
        (should (string-prefix-p "并入已有标签 other（token Canonical）" (buffer-string)))
        (should (= 3 (how-many "→ Canonical" (point-min) (point-max)))))
      (should (equal before (supertag-tag-change-test--snapshot (list file plain))))
      (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "destination"))
                ((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
        (should (equal "other" (supertag-tag-rename "old"))))
      (dolist (id '("file-node" "alias-node" "path-node"))
        (should (equal '("other") (plist-get (supertag-node-get id) :tags))))
      (dolist (path (list file plain))
        (with-current-buffer (find-file-noselect path)
          (should-not (buffer-modified-p))
          (should (equal (buffer-string) (supertag-document-test-disk path)))
          (should-not (string-match-p "destination\\|#alias\\|#emacs/package\\|:old:" (buffer-string)))
          (should (string-match-p "Canonical" (buffer-string)))))
      (should-not (supertag-tag-get "old")))))

(ert-deftest supertag-tag-change-own-alias-rejects-without-writing ()
  (supertag-tag-change-test--vault
    (let ((before (supertag-tag-change-test--snapshot (list file plain))))
      (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "alias"))
                ((symbol-function 'yes-or-no-p) (lambda (&rest _) (ert-fail "Own alias must reject before confirmation"))))
        (should-error (supertag-tag-rename "old") :type 'user-error))
      (should (equal before (supertag-tag-change-test--snapshot (list file plain)))))))

(ert-deftest supertag-tag-change-resolution-change-rejects-before-writing ()
  (supertag-tag-change-test--vault
    (let (after-external-change)
      (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "new"))
                ((symbol-function 'yes-or-no-p)
                 (lambda (&rest _)
                   (supertag-tag-create '(:name "new"))
                   (setq after-external-change (supertag-tag-change-test--snapshot (list file plain)))
                   t)))
        (let ((error (should-error (supertag-tag-rename "old") :type 'user-error)))
          (should (string-match-p "resolution changed" (error-message-string error)))))
      ;; The simulated external creation is preserved; this command adds no writes.
      (should (equal after-external-change (supertag-tag-change-test--snapshot (list file plain)))))))

(ert-deftest supertag-tag-change-preview-skips-metadata-lines ()
  (supertag-tag-change-test--vault
    (with-current-buffer (find-file-noselect plain)
      (goto-char (point-min)) (search-forward "Alias body")
      (replace-match "#+CAPTION: META #alias\nPROSE #alias"))
    (let ((before (supertag-tag-change-test--snapshot (list file plain))))
      (supertag-tag-change-preview "old" "new")
      (with-current-buffer "*Supertag Tag Change*"
        (should (string-match-p "PROSE #alias" (buffer-string)))
        (should-not (string-match-p "CAPTION" (buffer-string))))
      (should (equal before (supertag-tag-change-test--snapshot (list file plain)))))))


(ert-deftest supertag-tag-change-old-writers-absent ()
  (should-not (fboundp 'supertag-rename-tag))
  (should-not (fboundp 'supertag-ops-delete-tag-everywhere)))

(ert-deftest supertag-tag-change-boundary-records-membership-node-locally ()
  "A registered boundary Tag updates one node without whole-file projection."
  (supertag-document-test-with-vault
    (with-current-buffer (find-file-noselect file)
      (erase-buffer)
      (dotimes (index 50)
        (insert (format "* Heading %d\n:PROPERTIES:\n:ID: boundary-%d\n:END:\nBody %d\n"
                        index index index)))
      (save-buffer))
    (should (eq 'complete (plist-get (supertag-reindex-org) :status)))
    (supertag-tag-create '(:id "registered" :name "registered"))
    (with-current-buffer (find-file-noselect file)
      (goto-char (point-max))
      (forward-line -1)
      (end-of-line)
      (insert " #registered ")
      (let ((project-calls 0)
            (parse-calls 0)
            (project (symbol-function 'supertag--project-node-from-org-text))
            (parse (symbol-function 'org-element-parse-buffer)))
        (cl-letf (((symbol-function 'supertag--project-node-from-org-text)
                   (lambda (&rest args)
                     (cl-incf project-calls)
                     (apply project args)))
                  ((symbol-function 'org-element-parse-buffer)
                   (lambda (&rest args)
                     (cl-incf parse-calls)
                     (apply parse args))))
          (supertag-completion--auto-record-on-boundary))
        (should (= 0 project-calls))
        (should (= 0 parse-calls)))
      (let ((node (supertag-node-get "boundary-49")))
        (should (member "registered" (plist-get node :tags)))
        (should
         (equal (plist-get node :tag-occurrences)
                (save-excursion
                  (org-back-to-heading t)
                  (supertag-node-tag-occurrences-at-point)))))
      (should (string-match-p "#registered "
                              (supertag-document-test-disk file))))))

(ert-deftest supertag-tag-change-boundary-ignores-unregistered-token ()
  "An unregistered boundary token does not save or change the Store."
  (supertag-document-test-with-vault
    (with-current-buffer (find-file-noselect file)
      (goto-char (point-max))
      (insert " #unregistered ")
      (let ((before-store (prin1-to-string supertag--store))
            (before-disk (supertag-document-test-disk file))
            (save-calls 0)
            (save (symbol-function 'save-buffer)))
        (cl-letf (((symbol-function 'save-buffer)
                   (lambda (&rest args)
                     (cl-incf save-calls)
                     (apply save args))))
          (supertag-completion--auto-record-on-boundary))
        (should (= 0 save-calls))
        (should (equal before-store (prin1-to-string supertag--store)))
        (should (equal before-disk (supertag-document-test-disk file)))))))

(ert-deftest supertag-tag-change-retry-after-save-failure ()
  (dolist (operation '(rename delete))
    (supertag-tag-change-test--vault
      (let ((save (symbol-function 'supertag-service-org--save-current-buffer))
            (failed nil) first-target
            (first-disk (supertag-document-test-disk file))
            (second-disk (supertag-document-test-disk plain)))
        (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "new"))
                  ((symbol-function 'yes-or-no-p)
                   (lambda (prompt)
                     (when (and failed (eq operation 'rename))
                       (should (string-prefix-p "Merge" prompt))
                       (should (string-match-p (regexp-quote first-target) prompt)))
                     t))
                  ((symbol-function 'supertag-service-org--save-current-buffer)
                   (lambda ()
                     (if (and (equal (buffer-file-name) plain) (not failed))
                         (progn (setq failed t) (error "Second file save fails once"))
                       (funcall save)))))
          (cl-flet ((run () (if (eq operation 'rename) (supertag-tag-rename "old")
                             (supertag-delete-tag-everywhere "old"))))
            (should-error (run))
            (when (eq operation 'rename)
              (setq first-target (supertag-tag-resolve-occurrence "new"))
              (should first-target))
            (should-not (equal first-disk (supertag-document-test-disk file)))
            (should-not (member "old" (plist-get (supertag-node-get "file-node") :tags)))
            (should (equal second-disk (supertag-document-test-disk plain)))
            (should (buffer-modified-p (find-file-noselect plain)))
            (should (member "old" (plist-get (supertag-node-get "alias-node") :tags)))
            (supertag-tag-change-preview "old" (and (eq operation 'rename) "new"))
            (with-current-buffer "*Supertag Tag Change*"
              (should (string-match-p "待保存/待投影 1" (buffer-string))))
            (run)
            (should-not (supertag-tag-get "old"))
            (should-not (supertag-find-nodes-by-tag "old"))
            (dolist (id '("file-node" "alias-node" "path-node"))
              (should (equal (and (eq operation 'rename) (list first-target))
                             (plist-get (supertag-node-get id) :tags))))
            (dolist (path (list file plain))
              (with-current-buffer (find-file-noselect path)
                (should-not (buffer-modified-p))
                (should (equal (buffer-string) (supertag-document-test-disk path)))))
            (should-not (supertag-tag-change-preview "old"))
            (with-current-buffer "*Supertag Tag Change*"
              (should (string-match-p "待保存/待投影 0" (buffer-string))))))))))

(ert-deftest supertag-tag-change-unrelated-draft-does-not-request-repair ()
  "A normal token requests no repair, even when the buffer has an unrelated draft."
  (dolist (operation '(rename delete))
    (supertag-tag-change-test--vault
      (with-current-buffer (find-file-noselect plain) (goto-char (point-max)) (insert "Unrelated draft"))
      (let ((writer (symbol-function 'supertag-service-org--update-buffer-and-resync)) (calls 0))
        (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "new"))
                  ((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
                  ((symbol-function 'supertag-service-org--update-buffer-and-resync)
                   (lambda (id function &optional repair tags-only)
                     (should-not repair) (cl-incf calls)
                     (funcall writer id function repair tags-only))))
          (if (eq operation 'rename) (supertag-tag-rename "old")
            (supertag-delete-tag-everywhere "old")))
        (should (= calls 3))))))

(ert-deftest supertag-tag-change-unowned-entities-can-change ()
  (supertag-tag-change-test--vault
    (let ((id (plist-get (supertag-tag-create '(:name "lonely")) :id))
          (disk (mapcar #'supertag-document-test-disk (list file plain)))
          new-id)
      (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "new-lonely"))
                ((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
        (setq new-id (supertag-tag-rename id))
        (should-not (supertag-tag-get id))
        (should (equal "new-lonely" (plist-get (supertag-tag-get new-id) :name)))
        (supertag-delete-tag-everywhere new-id))
      (should-not (supertag-tag-get new-id))
      (should (equal disk (mapcar #'supertag-document-test-disk (list file plain)))))))

(ert-deftest supertag-tag-change-canonical-change-rejects-before-writing ()
  (supertag-tag-change-test--vault
    (supertag-tag-create '(:id "other" :name "Canonical" :aliases ("destination")))
    (let (after-external-change)
      (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "destination"))
                ((symbol-function 'yes-or-no-p)
                 (lambda (prompt)
                   (should (string-match-p "Canonical" prompt))
                   (supertag-tag-update "other" (lambda (tag) (plist-put tag :name "Changed")))
                   (should (equal "Changed" (plist-get (supertag-tag-get "other") :name)))
                   (should (member "destination" (plist-get (supertag-tag-get "other") :aliases)))
                   (should (equal "other" (supertag-tag-resolve-occurrence "destination")))
                   (setq after-external-change (supertag-tag-change-test--snapshot (list file plain)))
                   t)))
        (let ((error (should-error (supertag-tag-rename "old") :type 'user-error)))
          (should (equal "Tag resolution changed; preview again" (error-message-string error)))))
      (should (equal after-external-change
                     (supertag-tag-change-test--snapshot (list file plain)))))))


;;; D1: real member writes and the existing compensation contract.
(ert-deftest supertag-tag-change-member-bulk-preserves-entity-and-write-counts ()
  (supertag-document-test-with-vault
    (with-current-buffer (find-file-noselect plain)
      (erase-buffer)
      (insert "* Second\n:PROPERTIES:\n:ID: second-node\n:END:\nSecond body\n")
      (save-buffer))
    (should (eq 'complete (plist-get (supertag-reindex-org) :status)))
    (supertag-tag-create '(:id "stable" :name "canonical" :aliases ("alias")))
    (let ((save (symbol-function 'supertag-service-org--save-current-buffer))
          (record (symbol-function 'supertag-service-org-save-and-record-tags-at-point))
          saves records ids)
      (cl-letf (((symbol-function 'supertag-service-org--save-current-buffer)
                 (lambda () (push (buffer-file-name) saves) (funcall save)))
                ((symbol-function 'supertag-service-org-save-and-record-tags-at-point)
                 (lambda (id) (push id records) (funcall record id))))
        (setq ids (supertag-capture-add-tags-to-nodes
                   '("document-node" "second-node") '("alias" "media/book"))))
      (should (equal (car ids) "stable"))
      (should (= (length ids) 2))
      (should-not (supertag-tag-resolve-occurrence "media"))
      (dolist (pair (list (cons "document-node" file) (cons "second-node" plain)))
        (should (= 1 (cl-count (car pair) records :test #'equal)))
        (should (= 1 (cl-count (cdr pair) saves :test #'equal)))
        (should (equal (sort (copy-sequence ids) #'string<)
                       (sort (copy-sequence (plist-get (supertag-node-get (car pair)) :tags)) #'string<)))
        (with-current-buffer (find-file-noselect (cdr pair))
          (should-not (buffer-modified-p))
          (should (equal (buffer-string) (supertag-document-test-disk (cdr pair))))
          (should (string-match-p "#canonical" (buffer-string)))
          (should (string-match-p "#media/book" (buffer-string))))))))

(defun supertag-tag-change-test--late-member-failure (fail-compensation)
  "Observe durable first write, then fail verification and optionally recovery."
  (supertag-document-test-with-vault
    (let* ((before (supertag-document-test-disk file))
           (tags-before (copy-tree (plist-get (supertag-node-get "document-node") :tags)))
           (real (symbol-function 'supertag-service-org-save-and-record-tags-at-point))
           (calls 0) saved error-data)
      (cl-letf (((symbol-function 'supertag-service-org-save-and-record-tags-at-point)
                 (lambda (id)
                   (cl-incf calls)
                   (when (and fail-compensation (= calls 2))
                     (error "D1 compensation save failed"))
                   (prog1 (funcall real id)
                     (when (= calls 1)
                       (setq saved (supertag-document-test-disk file))))))
                ((symbol-function 'supertag-capture--tag-membership-present-p)
                 (lambda (&rest _) nil)))
        (setq error-data
              (should-error (supertag-capture-add-tag-to-nodes
                             '("document-node") "d1-rollback") :type 'user-error)))
      (should (= calls 2))
      (should (string-match-p "#d1-rollback" saved))
      (should-not (equal before saved))
      (should (string-match-p "membership projection did not contain every Tag"
                             (error-message-string error-data)))
      (should-not (supertag-tag-resolve-occurrence "d1-rollback"))
      (should (equal tags-before (plist-get (supertag-node-get "document-node") :tags)))
      (with-current-buffer (find-file-noselect file)
        (should (equal before (buffer-string)))
        (if fail-compensation
            (progn
              (should (string-match-p "restoring the Org file also failed: D1 compensation save failed"
                                     (error-message-string error-data)))
              (should (equal saved (supertag-document-test-disk file)))
              (should (buffer-modified-p)))
          (should (equal before (supertag-document-test-disk file)))
          (should-not (buffer-modified-p)))))))

(ert-deftest supertag-tag-change-member-late-failure-restores-saved-org ()
  (supertag-tag-change-test--late-member-failure nil))

(ert-deftest supertag-tag-change-member-compensation-failure-reports-both-errors ()
  (supertag-tag-change-test--late-member-failure t))

(provide 'tag-rename-delete-test)

;;; D4 retained cleanup command: real selection, confirmation and facts.
(ert-deftest supertag-tag-change-orphan-command-confirms-only-selected-entity ()
  (supertag-tag-change-test--vault
    (let ((supertag--view-configs (make-hash-table :test 'eq)))
      (require 'supertag-view-framework)
      (dolist (id '("unused" "kept" "protected"))
        (supertag-tag-create (list :id id :name id)))
      (supertag-view-config-register '(:id d4-protected :valid-for ("protected")))
      (should-not (member "protected" (supertag-tag-orphaned-ids)))
      (let ((before (supertag-tag-change-test--snapshot (list file plain))))
        (dolist (confirm '(nil t))
          (let ((answers '("unused" "")))
            (cl-letf (((symbol-function 'completing-read)
                       (lambda (_prompt table &rest _)
                         (should-not (member "protected" (all-completions "" table)))
                         (pop answers)))
                      ((symbol-function 'yes-or-no-p) (lambda (&rest _) confirm)))
              (call-interactively #'supertag-cleanup-orphaned-tags)))
          (if confirm
              (progn
                (should-not (supertag-tag-get "unused"))
                (should (supertag-tag-get "kept"))
                (should (supertag-tag-get "protected"))
                (should (supertag-tag-get "old"))
                (should (equal (car before)
                               (car (supertag-tag-change-test--snapshot (list file plain))))))
            (should (equal before (supertag-tag-change-test--snapshot (list file plain))))))))))
